### ISSUE TITLE
Broken link in 3.6 Quantum Phase Estimation

### ISSUE THREAD

**Issue by Morcu** [qiskit-community/qiskit-textbook#1001]
**Describe the issue**
There is a broken link in the section [3.6 Quantum Phase Estimation](https://qiskit.org/textbook/ch-algorithms/quantum-phase-estimation.html) in [1.2 Mathematical Foundation](https://qiskit.org/textbook/ch-algorithms/quantum-phase-estimation.html#1.2-Mathematical-Foundation-).

The url of  `Quantum Fourier Transform and its Qiskit Implementation` leads  to a `Page Not Found`

**Describe what you expect to see**
Either the Quantum Fourier Transform Chapter or the Quantum Fourier Transform code implementation.

**Comment by divshacker** [comment]
Can I work on this @Morcu ?

**Comment by Morcu** [comment]
Sure!

**Comment by divshacker** [comment]
Done! @Morcu If it is fixed then feel free to close this Issue
