### ISSUE TITLE
[6.3] A mixup of kinetic and potential energy in the LC circuit?

### ISSUE THREAD

**Issue by mikaelhaglund** [qiskit-community/qiskit-textbook#1005]
**Describe the issue**
On page: content/ch-quantum-hardware/transmon-physics.ipynb

In the sentence "The Hamiltonian is the sum of the kinetic energy (represented by charge variable Q) and potential energy (represented by flux variable Φ)," I believe it should be the other way around.

**Describe what you expect to see**
"The Hamiltonian is the sum of the potential energy (represented by charge variable Q) and kinetic energy (represented by flux variable Φ), "

This fits better with my dusty old electrical engineer intuition, and seems to be how others have described it elsewhere.

**Comment by divshacker** [comment]
May I work on this @frankharkins ?

**Comment by divshacker** [comment]
Hey @frankharkins  can you assign me this issue. 
Thank you

**Comment by mikaelhaglund** [comment]
According to this video https://www.youtube.com/watch?v=SDiiFOham6Y (about 29 minutes in) I was wrong.

**Comment by divshacker** [comment]
Nope, you are right. @zlatko-minev

**Comment by frankharkins** [comment]
@divshacker thanks for looking into this

**Comment by divshacker** [comment]
Hey @frankharkins  I have closed the Pull request as told by @nbronn . Kindly close this issue also. 
Thank you
