### ISSUE TITLE
Can we Rename all content files with there chapter numbers given in Qiskit textbook

### ISSUE THREAD

**Issue by divshacker** [qiskit-community/qiskit-textbook#1007]
**Describe the solution you'd like**
Sometimes it's get hard to navigate the qiskit textbook file on github repo. Ofcourse github link is given in qiskit textbook to contribute. But if we rename all the content files according to chapter numbers on github then it would be lot easier to find the correct files. I am not saying to rename the files but wanted to add the chapter numbers also. 

**Additional context**
This thing is there in qiskit documentation repo. It would be better if we bring this here also

**Comment by frankharkins** [comment]
Thanks for the suggestion- I understand this can be a bit annoying, but I'm reluctant to make this change as I think it will be a lot of work for an inconvenience that only affects a handful of people.

Some (non-obvious) problems with this change are:
- Jupyter Book uses the filename to create the url, so the urls would all change, so we would need to add redirects for all pages to make sure we don't break links
- References to notebooks on the IBM Quantum Lab will need updating
- All entries in `_config.yml` will need changing
- If we ever change the order of notebooks, or add a new notebook mid-way through a chapter, this will require name changes and redirects too.

I'm pretty sure there are other things that will go wrong that I haven't thought of.

**Comment by divshacker** [comment]
Yeah, Make sense. 
Thanks
