### ISSUE TITLE
Qobj deprecated, notebook update needed.

### ISSUE THREAD

**Issue by omarcostahamido** [qiskit-community/qiskit-textbook#1025]
**Describe the issue**
As I was reading [this lesson](https://github.com/qiskit-community/qiskit-textbook/blob/master/content/ch-quantum-hardware/calibrating-qubits-pulse.ipynb), I just noticed that it uses Qobj which throws `Passing a Qobj to Backend.run is deprecated`

**Comment by frankharkins** [comment]
Closing as duplicate of #957
