### ISSUE TITLE
Replace usage of statevector & unitary simulators with AerSimulator

### ISSUE THREAD

**Issue by frankharkins** [qiskit-community/qiskit-textbook#1030]
**Describe the problem**

Usage of qasm_simulator is being replaced in #1012 & we will need to follow suit with the statevectors and unitary simulators.

**Comment by trietnb** [comment]
@frankharkins Can I give this a try? Thanks!

**Comment by frankharkins** [comment]
@trietnb yes actually, thank you. Please make the pull request to the [`qiskit-version-updates` branch](https://github.com/qiskit-community/qiskit-textbook/tree/qiskit-version-updates) instead of the master branch. Please also don't run any code cells (to keep the diff as small as possible).

**Comment by frankharkins** [comment]
@trietnb did you manage to take a look at this?

**Comment by trietnb** [comment]
@frankharkins I'm pushing it today, Frank. Been busy with other deadlines.
