### ISSUE TITLE
Example in Hybrid quantum-classical Neural Networks with PyTorch and Qiskit errors out locally

### ISSUE THREAD

**Issue by jwoehr** [qiskit-community/qiskit-textbook#1038]
**Describe the bug**
The example in https://qiskit.org/textbook/ch-machine-learning/machine-learning-qiskit-pytorch.html runs on the web but errors out if copied to a notebook in a virtual environment with an up-to-date local Qiskit installation.

**To Reproduce**
1. Copy first 3 cells of cited page to a local Jupyter notebook.
2. Run each cell
3. 3rd cell errors as follows:
---------------------------------------------------------------------------
```
QiskitError                               Traceback (most recent call last)
<ipython-input-3-06b09ff4dd69> in <module>
      2 
      3 circuit = QuantumCircuit(1, simulator, 100)
----> 4 print('Expected value for rotation pi {}'.format(circuit.run([np.pi])[0]))
      5 circuit._circuit.draw()

<ipython-input-2-227abd703128> in run(self, thetas)
     29                         parameter_binds = [{self.theta: theta} for theta in thetas])
     30         job = self.backend.run(qobj)
---> 31         result = job.result().get_counts(self._circuit)
     32 
     33         counts = np.array(list(result.values()))

~/work/QISKit/qiskit_dev_venv6/lib/python3.8/site-packages/qiskit_terra-0.18.0-py3.8-linux-x86_64.egg/qiskit/result/result.py in get_counts(self, experiment)
    261         dict_list = []
    262         for key in exp_keys:
--> 263             exp = self._get_experiment(key)
    264             try:
    265                 header = exp.header.to_dict()

~/work/QISKit/qiskit_dev_venv6/lib/python3.8/site-packages/qiskit_terra-0.18.0-py3.8-linux-x86_64.egg/qiskit/result/result.py in _get_experiment(self, key)
    368 
    369             if len(exp) == 0:
--> 370                 raise QiskitError('Data for experiment "%s" could not be found.' %
    371                                   key)
    372             if len(exp) == 1:

QiskitError: 'Data for experiment "circuit-1" could not be found.'
```

**Expected behavior**
Should run locally

**Version info**
Qiskit is master branch terra/ibmq/aer/ignis/aqua updated daily.

**Reported by**
User AP on Qiskit Slack https://qiskit.slack.com/archives/C88B13092/p1618105544125500

**Comment by jwoehr** [comment]
The above is my own testing confirming the user's report.

**Comment by 1ucian0** [comment]
It was also mentioned by https://quantumcomputing.stackexchange.com/questions/16946/pytorch-and-qiskit-example-from-the-qiskit-textbook-seems-broken/16948

The workaround when `run` has only one `theta` (for example `circuit.run([np.pi])[0])` is to remove the circuit from the `get_count`  (in the example `result = job.result().get_counts()`. 

If I understand correctly, the tutorial continues with more than one binding. In that case, the results need to fetch via a loop on the index.
