### ISSUE TITLE
Maximum number of function evaluations exceeded on Variational Quantum Linear Solver

### ISSUE THREAD

**Issue by TigrisCallidus** [qiskit-community/qiskit-textbook#1039]
**Observed behavior**

On the chapter VQLS https://qiskit.org/textbook/ch-paper-implementations/vqls.html when one runs the code above the text "As you can see, our cost function has achieved a fairly low value of 0.03273673575407443" one gets the message "Maximum number of function evaluations has been exceeded." after 200 runs. Further the last value one gets there is lower than the value specified in the text. 

![textbookbug](https://user-images.githubusercontent.com/20563847/114699193-452ca480-9d20-11eb-96de-6ba5042f98ff.JPG)

One also gets the same message when running the next code block, but there is no number specified in the text.

Further, I did not get any output when running the last code block in this chapter, even after several tries. I am not sure if this is connected with the bug above.

**Expected behavior**

I would expect the function running to succeed (give success True not False), and not have an error message. 
Further I would expect the result to be the same as in the text, if some value is specified in the text.

I also would expect the last code block to give output.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
