### ISSUE TITLE
[2.2] Multiple Qubits and Entangled States - Could have included more information on Bell states for a better understanding of the concept.

### ISSUE THREAD

**Issue by navaneethsdk** [qiskit-community/qiskit-textbook#1041]
[Section 2.2 ](https://qiskit.org/textbook/ch-gates/multiple-qubits-entangled-states.html#3.2-Entangled-States-) has done a great job in describing how a bell state can be obtained using the Hadamard gate and the CNOT gate. But since it discusses the operation only for one input configuration, |00⟩, there is a chance that a beginner in this field might misinterpret the state 1/√2(|00⟩+|11⟩) to be the only maximum entangled state. In fact, as Wikipedia formally defines it, the Bell states are four specific maximally entangled quantum states of two qubits. 
![Screenshot from 2021-04-16 09-16-34](https://user-images.githubusercontent.com/56035039/114987130-7046fd80-9eb2-11eb-830a-a3324639d475.png)
Here each Bell state corresponds to a different input configuration, ie |00⟩, |01⟩, |10⟩ and |11⟩.

Also, the behavior of the second qubit after measuring the first qubit could be considered for a detailed discussion, with the Bell states in the spotlight.
Again quoting from Wikipedia

> The result of a measurement of a single qubit in a Bell state is indeterminate, but upon measuring the first qubit in the z-basis, the result of measuring the second qubit is guaranteed to yield the same value (for the ϕ Bell states) or the opposite value (for the Ψ Bell states).

Clearly, the text seems to focus only on the first |ϕ+⟩ Bell state (although another Bell state is asked to be computed as an exercise).

### Expected solution 
1. Can incorporate the above-discussed concepts directly into the notebook
2. Can provide links like [this](https://en.wikipedia.org/wiki/Bell_state) one, for those requiring a detailed explanation on such concepts. 

I would love to hear what others think about this.

**Comment by dhruvbhq** [comment]
Hi! The discussions in #708 and #720 might be of help.

**Comment by agnel** [comment]
@navaneethsdk You are right. I was struggling to understand the exercise question that was asking to compute other bell state. I had to go through [Quantum Computation Construction of the Bell’s four states notes from Department of Physics, SUNY at Binghamton](https://bingweb.binghamton.edu/~suzuki/QuantumMechanicsFiles/11-1_Quantum_computation_I_Overview.pdf) and [Bell State wiki on Qunatiki](https://www.quantiki.org/wiki/bell-state).

But eventually resorted to trial and error method using `qiskit` playing in `IBM Quantum Lab` with the `qiskit` notebook to come up with a solution to the bell state from question 1 and the required unitary in question 2 from [Exercise 3.4](https://qiskit.org/textbook/ch-gates/multiple-qubits-entangled-states.html#3.4-Exercise:-)

Here are my solutions to [question 1](https://gist.github.com/agnel/dabc621fec0cec17cf2717c4b057151c) and [question 2](https://gist.github.com/agnel/26a6cb8841f701d9f49a1bdce6ae56e8). I'm doubtful whether my solution to question 2 is even correct. Any suggestions?

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
