### ISSUE TITLE
[4.1.3] QAOA labelling inconsistency

### ISSUE THREAD

**Issue by frankharkins** [qiskit-community/qiskit-textbook#1046]
**Describe the issue**
I received this email from a reader:

> The cost function in section 5.4 treats the first bit of the input bit string “x” as vertex number 0, however the first bit of x refers to the value of the last qubit q4, which in turn corresponds to the last vertex of the underlying graph, vertex number 4.
> 
> Simply reversing the input bit string resolves this issue.
>
> In fact, this inconsistency does not show up for the specific labelling of the vertices in the problem graph used in the textbook. The cost function for this labelling is symmetric with respect to reversing the bit string. Another labelling in which the central node with degree 4 does not happen to be vertex number 2 would reveal the bug.

**Comment by riya-m** [comment]
@frankharkins I would like to resolve the issue

**Comment by frankharkins** [comment]
Thanks, sorry I missed this. Closed via #1162
