### ISSUE TITLE
lassifaction reprot

### ISSUE THREAD

**Issue by rawanaziz** [qiskit-community/qiskit-textbook#1048]
**Describe the problem**
hi,

I am working , 5 classes using QNN classifier with circuit QNN , I  faced a problem when I print the classification   report i found that:

![image](https://user-images.githubusercontent.com/61630088/115973843-bd853800-a560-11eb-8a9c-156d3f4309bf.png)

 the score that I got is 0.86 ?

**Comment by aasfaw** [comment]
This is not an issue related to any of the content in the textbook, but a question about a quantum computation. This is not the place for these questions, and we use issues to specifically focus on improving the content and presentation in the textbook. You may consider asking your questions on Stack Exchange instead.
