### ISSUE TITLE
[3.2] Problem 2: dj_problem_oracle(3) seems to be neither balanced nor constant

### ISSUE THREAD

**Issue by Mietzsch** [qiskit-community/qiskit-textbook#1049]
In Problem 2 of Section 3.2 (Deutsch-Jozsa), when I try to find out if dj_problem_oracle(3) is constant or balanced, the result state seems to be neither 0000 nor 1111, but evenly distributed between all possible states. For the other dj_problem_oracle(i), i=1,2,4 my code seems to work.

Here's what I did (I just reused the code from cells above):
```
from qiskit_textbook.problems import dj_problem_oracle
oracle = dj_problem_oracle(3)

def dj_algorithm(oracle, n):
    dj_circuit = QuantumCircuit(n+1, n)
    # Set up the output qubit:
    dj_circuit.x(n)
    dj_circuit.h(n)
    # And set up the input register:
    for qubit in range(n):
        dj_circuit.h(qubit)
    # Let's append the oracle gate to our circuit:
    dj_circuit.append(oracle, range(n+1))
    # Finally, perform the H-gates again and measure:
    for qubit in range(n):
        dj_circuit.h(qubit)
    
    for i in range(n):
        dj_circuit.measure(i, i)
    
    return dj_circuit

n = 4
oracle_gate = oracle
dj_circuit = dj_algorithm(oracle_gate, n)
#dj_circuit.draw()

transpiled_dj_circuit = transpile(dj_circuit, qasm_sim)
qobj = assemble(transpiled_dj_circuit)
results = qasm_sim.run(qobj).result()
answer = results.get_counts()
plot_histogram(answer)
```

**Comment by frankharkins** [comment]
This is what I get from your code:

<img width="625" alt="Screenshot 2021-04-29 at 10 31 04" src="https://user-images.githubusercontent.com/36071638/116530486-024cfe00-a8d6-11eb-83fb-81b73f66abfa.png">

which works correctly as the probability of measuring |0000> is 0 (which means function is balanced). This is the reason I included this example (which was a bit harder to make) as most of the examples I've seen just give all-zeros or all-ones when input into the DJ algorithm.

**Comment by Mietzsch** [comment]
Ah, many thanks. I did not see that. My bad.

Then it is a great example. Thank you for the explanation.
