### ISSUE TITLE
[2.2] image outside of range

### ISSUE THREAD

**Issue by omarcostahamido** [qiskit-community/qiskit-textbook#1050]
**Describe the issue**
in section 2.2 [here](https://qiskit.org/textbook/ch-gates/multiple-qubits-entangled-states.html) there is an image that is partly behind the right hand menu.
It is when the text says: `The operation looks like this:`
I'm not sure these are exported to matrices. I tried to look up the notebook [here](https://github.com/qiskit-community/qiskit-textbook/blob/master/content/ch-gates/multiple-qubits-entangled-states.ipynb) to try and fix it myself, but it look a bit different than what I was expecting.

**Comment by divshacker** [comment]
I think that image is caused because of overlapping of Right hand content menu. If you just click on the arrow near the left hand menu. It will hide the left menu and causes the overlapping to disappear.  
![Screenshot from 2021-04-29 11-26-39](https://user-images.githubusercontent.com/55018955/116508393-e8fc7f80-a8de-11eb-88b4-3bd27fb9f92d.png)

**Comment by divshacker** [comment]
About what you saw on github link. I think that is already been fixed and updated on qiskit textbook. But maybe not on github

**Comment by frankharkins** [comment]
This equation should be broken up over three lines. I.e.:
```
X⊗H = [matrix]
    = 1/sqrt{2}[bigger matrix]
    = [final 4x4 matrix]
```

**Comment by QRiddler** [comment]
Can I work on this @frankharkins ?

**Comment by QRiddler** [comment]
@frankharkins is qiskit participating in hacktoberfest2021?

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
