### ISSUE TITLE
QSVM  running in real backend 

### ISSUE THREAD

**Issue by rawanaziz** [qiskit-community/qiskit-textbook#1053]
I am trying to run this for multiple times , there is no result how to run the QSVM classifier with real computer  
i am using the following 
![image](https://user-images.githubusercontent.com/61630088/116648076-d9377680-a984-11eb-9835-456113df87e0.png)

![image](https://user-images.githubusercontent.com/61630088/116647960-970e3500-a984-11eb-91bf-349f1b49c8fb.png)
kindly,help me

**Comment by rawanaziz** [comment]
may help me please also i found some limitations using limitation from source ,i will discuss but i need your help to use a real  computer

**Comment by jwoehr** [comment]
@rawanaziz this is the sort of question you want to ask on [Qiskit Slack](http://ibm.co/joinqiskitslack)

**Comment by frankharkins** [comment]
@rawanaziz I'm going to close this as I'm not sure what action you want to take. If you want to reopen, please make another issue following the template.
