### ISSUE TITLE
2 qubit universal variational form

### ISSUE THREAD

**Issue by epelaaez** [qiskit-community/qiskit-textbook#1056]
**Is your feature request related to a problem? Please describe.**
In the [simple variational forms](https://qiskit.org/textbook/ch-applications/vqe-molecules.html#Simple-Variational-Forms) section of Simulating Molecules using VQE, a universal variational form circuit is given for the 2 qubits case. The following circuit is given from [this](https://arxiv.org/pdf/quant-ph/0308033.pdf) paper. 

![image](https://user-images.githubusercontent.com/63567458/116729386-63182b80-a9e7-11eb-913b-aeeefe308858.png)

We know from [1] that 3 CNOT gates are needed to implement any arbitrary two qubit gate.  So the circuit above is optimal in that sense. In the same paper, we encounter an optimal implementation for any arbitrary gate in U(4).

![image](https://user-images.githubusercontent.com/63567458/116731045-83e18080-a9e9-11eb-8ed3-4976b404c72f.png)

The A_i gates at the beggining and at the end can be implemented as U3 gates. Therefore, this method would use one parameter for each R_j gate and three parameters for each A_i gate, adding put to a total of 15 parameters; which is better than the 24 parameters that the implementation in the textbook uses. Having less parameters would mean that the optimization process would be easier for the algorithm, therefore the implementation from [1] can be considered more optimal. 

**Describe the solution you'd like**
If my analysis is correct and the method presented in [1] is actually better than the one given in the textbook, it'd be great to see this explained since it is more efficient. Another efficient method could also be derived from papers [2] and [3].

From context, I understand that the purpose of this example is just to mention how the complexity for the universal variational form increases with the number of qubits. But I think that it'd be great to show the most efficient method anyways to give a better idea. It would also be great if references or information were given about how to construct the universal variatonal form for 2+ qubits. 

**Describe alternatives you've considered**
Since this appears in the section titled _Simple Variational Forms_, I understand that the complexity of the optimized circuit may not be what you are looking for to include. Therefore, maybe adding a section along the lines of _n Qubit Variational Forms_ would be great. 

**Additional context**
@the-legend-of-lia helped me gather resources on the topic. 

**References**
- https://arxiv.org/pdf/quant-ph/0308006.pdf [1]
- https://arxiv.org/pdf/quant-ph/0011050.pdf [2]
- https://arxiv.org/pdf/cond-mat/0609750.pdf [3]

**Comment by frankharkins** [comment]
Is a new explanation necessary? Or would a short note and a link to further reading suffice?

**Comment by epelaaez** [comment]
I think a short note would suffice since this doesn't play a major role on the example that the page focuses on. I agree that the VQE pages is already dense, so just a short note and references should be good.

**Comment by the-legend-of-lia** [comment]
May I suggest replacing the existing image with the optimal one, along with the half-sentence remark (with citation) that it optimally minimizes the number of parameters?

**Comment by epelaaez** [comment]
I think there are two ways of including this in the textbook. The first would be replacing the current image plus the sentence before for a new sentence plus image that shows the optimal variational form. The second would be adding a note after what is currently on the textbook clarifying that there is a more optimal variational form and linking to the paper: [Optimal Quantum Circuits for General Two-Qubit Gates](https://arxiv.org/pdf/quant-ph/0308006.pdf). Actually, the paper linked in the textbook shows the variational form I'm suggesting (Figure 2 [here](https://arxiv.org/pdf/quant-ph/0308033.pdf)), so I guess this was adapted to make it simpler. Either way, I think a change is needed since the U3 gates were deprecated and a warning shows when you used them on Qiskit. Therefore, I think one of the following changes should be made:

### Option 1: replace current variational form
Delete the second sentence (Based on the work presented...) and image from the following: 

![image](https://user-images.githubusercontent.com/63567458/121811943-59304c00-cc66-11eb-866b-5ebc2c773cd1.png)

And replace them with the sentence: "Based on the work presented by Farrokh Vatan and Colin Williams [3], the following is the optimal universal parameterized 2 qubit circuit:". Where [3] is the reference to this paper: https://arxiv.org/pdf/quant-ph/0308006.pdf. And the image would be the following.

![image](https://user-images.githubusercontent.com/63567458/121812377-e58f3e80-cc67-11eb-8a9e-3ca107316b9f.png)

### Option 2: add a note to current variational form
The other option would be to just add a note to the section of the chapter showed. Before or after the image of the circuit, the following could be added: "However, this is not the most optimal implementation of a 2-qubit gate. For an optimal implementation of a two-qubit gate in U(4), refer to Theorem 5 in [3]". Where [3] once again is the reference to:  https://arxiv.org/pdf/quant-ph/0308006.pdf.

### Final change

Furthermore, regardless of the change selected from above, I believe that the current image (if kept) should be replaced by the following:

![image](https://user-images.githubusercontent.com/63567458/121811891-25552680-cc66-11eb-921b-5af2311f79a2.png)

In which I've just replaced the U3 gates with U gates.

**Comment by epelaaez** [comment]
@frankharkins I've opened a pull request (#1173) implementing option 1 from my previous comment, please let me know if any changes should be made.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
