### ISSUE TITLE
[5.2] Measurement of second qubit missing throughout the code

### ISSUE THREAD

**Issue by diemilio** [qiskit-community/qiskit-textbook#1061]
**Describe the bug**
The last change to section 5.2 removed the use of registers (see [here](https://github.com/qiskit-community/qiskit-textbook/commit/c20c32bd1c07e1c9cb4f883fb7f523b62f811575#diff-ea77fec11436bf85febd83f8ba683ab60a8c74bd93cb089deba1edcdf75bf121)). Unfortunately, the change made only measures the first qubit in the code (qubit 0), but both qubits (qubit 0 and qubit 1) should be measured.

Error was not caught because it seems code was not reran before updating the section.

For more details, see this this [thread](https://qiskit.slack.com/archives/C7SJ0PJ5A/p1619762928113100) in slack channel.

**To Reproduce**
Re-run code cells. Results will differ from expected results.

**Expected behavior**
Previous code produced expected behavior.

**Version info***

**Comment by diemilio** [comment]
Here are some screenshots of one of the problems this issue is causing:

Old code (expected behavior):
![image](https://user-images.githubusercontent.com/65074936/116897190-fbd6c300-ac02-11eb-9b3c-f7bc481f1eaf.png)


New code (erroneous result):
![image](https://user-images.githubusercontent.com/65074936/116897066-d9dd4080-ac02-11eb-8402-6d43426a565e.png)

**Comment by rafal-pracht** [comment]
May I fix this issue?

**Comment by frankharkins** [comment]
@rafal-pracht yes! Thank you

**Comment by rafal-pracht** [comment]
@frankharkins I've just created pull request https://github.com/qiskit-community/qiskit-textbook/pull/1067
