### ISSUE TITLE
[1.3] Inconsistency in using the word 'initialize'

### ISSUE THREAD

**Issue by dhruvbhq** [qiskit-community/qiskit-textbook#1062]
**Describe the issue**
In 1.3 (https://qiskit.org/textbook/ch-states/representing-qubit-states.html), the British spelling _'initialise'_ (with an _s_) has been used extensively. However, other sections of the textbook (for eg 4.1.2 https://qiskit.org/textbook/ch-applications/vqe-molecules.html) use the American spelling, which is _'initialize'_ (with a _z_).

**Describe what you expect to see**
The usage should be consistent, and I think it might be good to use the American spelling everywhere. This is because even the initialization instruction in Qiskit has been named _'initialize'_ (https://qiskit.org/documentation/stubs/qiskit.extensions.Initialize.html).
Also, using grep, one can search for other notebooks in the textbook where _'initialise'_ has been used, and change that as well.

**Comment by divshacker** [comment]
May I work  on this @dhruvbhq  
Hey @frankharkins Can you assign me this ?

**Comment by divshacker** [comment]
Hey I have searched whole book and this spelling difference is not only in above linked chapter but also in many more.

**Comment by dhruvbhq** [comment]
From my side, you can go ahead with the fix @divshacker !

**Comment by frankharkins** [comment]
Yes you can make this change @divshacker, thank you
