### ISSUE TITLE
Qiskit textbook lab solutions

### ISSUE THREAD

**Issue by quantumAnsatz** [qiskit-community/qiskit-textbook#1074]
**Is your feature request related to a problem? Please describe.**
Quantum Computing Labs chapter of the texbook has no way to verify if the queries submitted are right.

**Describe the solution you'd like**
A separate file with the solutions similar to what is done in https://qiskit.org/learn/intro-qc-qh. 

**Describe alternatives you've considered**
An alternative solution is to add more content on what the results should "look like" or a way to automatically verify the results obtained.

**Comment by frankharkins** [comment]
FYI, we're working on this. We won't publicly release the lab solutions, but an automatic verification is on the cards.

**Comment by quantumAnsatz** [comment]
@frankharkins what cards?

**Comment by frankharkins** [comment]
It's a turn of phrase, means it's possible / likely to happen.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
