### ISSUE TITLE
Chapter 4.1.5: error "Data for experiment could not be found"

### ISSUE THREAD

**Issue by Fedacc** [qiskit-community/qiskit-textbook#1082]
**Description**
When executing the jupyter notebook for this chapter within the Quantum Lab, the implementation of the QuantumCircuit class returns one error when trying to retrieve the results from the execution of the experiment on the simulator.
On the other hand, in the textbook environment it works just fine.

**To Reproduce**
1. Go to https://qiskit.org/textbook/ch-machine-learning/machine-learning-qiskit-pytorch.html
2. Click on Open in IBM Quantum Lab
3. Execute the first 3 blocks of code (1: import of packages, 2: class definition, 3: test)
5. (optional) execute the code directly from the textbook and it works fine

As a possible solution, if I change the following line in the notebook running in IBM Quantum Lab the code works:
```
result = job.result().get_counts()
```
instead of having `.get_counts(self._circuit)`

**Version info**
On IBM Quantum Lab:
```
{'qiskit-terra': '0.17.1',
 'qiskit-aer': '0.8.2',
 'qiskit-ignis': '0.6.0',
 'qiskit-ibmq-provider': '0.12.3',
 'qiskit-aqua': '0.9.1',
 'qiskit': '0.25.3',
 'qiskit-nature': '0.1.1',
 'qiskit-finance': None,
 'qiskit-optimization': '0.1.0',
 'qiskit-machine-learning': None}
```

On qiskit textbook
```
{'qiskit-terra': '0.16.1',
 'qiskit-aer': '0.7.2',
 'qiskit-ignis': '0.5.1',
 'qiskit-ibmq-provider': '0.11.1',
 'qiskit-aqua': '0.8.1',
 'qiskit': '0.23.2'}
```

**Comment by rafal-pracht** [comment]
@Fedacc  Isn't this duplicate of https://github.com/qiskit-community/qiskit-textbook/issues/1038 ?

**Comment by Fedacc** [comment]
@rafal-pracht you are right, I did not see it before in my initial search.
I will close this as the issue is already covered there
