### ISSUE TITLE
[3.5] Recursion description is incorrect.

### ISSUE THREAD

**Issue by Mertcikla** [qiskit-community/qiskit-textbook#1090]
In chapter 3.5, under 8.2 General QFT Function implementation, it is mentioned that: 
"Using a function inside another function is called recursion." 

This is incorrect. Recursion refers specifically to a function calling itself.

**Comment by divshacker** [comment]
Hey I have done that editing and made the PR accordingly. Please let me know if any further changes needed
Thank you
