### ISSUE TITLE
Issue with notebook "Accessing Higher Energy States"

### ISSUE THREAD

**Issue by bachbao** [qiskit-community/qiskit-textbook#1091]
**Describe the issue**
The notebook  "Accessing Higher Energy States" in chapter 6: Investigating Quantum Hardware Using Microwave Pulses is having an error as the SamplePulse class was renamed qiskit.pulse.library.Waveform in August 2020. Therefore, this notebook needs updating. 
**Describe what you expect to see**
Expect to see the code using Waveform class instead of SamplePulse.

**Comment by divshacker** [comment]
Hey @bachbao I would like to work on this issue. By reading above you mean one just need to change name from "SamplePulse" to "WaveForm"? 
If yes then I am going to edit the code and just post the output screenshots here. Please let me know if I am right or not. Then After that I will push that accordingly. 
Thank you

**Comment by bachbao** [comment]
> Hey @bachbao I would like to work on this issue. By reading above you mean one just need to change name from "SamplePulse" to "WaveForm"?
> If yes then I am going to edit the code and just post the output screenshots here. Please let me know if I am right or not. Then After that I will push that accordingly.
> Thank you

I have already tried to replace the class SamplePulse by qiskit.pulse.library.Waveform but the result (graph) after executing still turns out to be wrong. Therefore, I don't know how to achieve the correct graph in the notebook rightnow

**Comment by divshacker** [comment]
> > Hey @bachbao I would like to work on this issue. By reading above you mean one just need to change name from "SamplePulse" to "WaveForm"?
> > If yes then I am going to edit the code and just post the output screenshots here. Please let me know if I am right or not. Then After that I will push that accordingly.
> > Thank you
> 
> I have already tried to replace the class SamplePulse by qiskit.pulse.library.Waveform but the result (graph) after executing still turns out to be wrong. Therefore, I don't know how to achieve the correct graph in the notebook rightnow

Yup same here I am also getting wrong graphs.  Hey @frankharkins  can you help or can you please tag someone who can help

**Comment by frankharkins** [comment]
Thanks for tagging me, I'm not sure what the solution is, but someone else is currently working on this.

**Comment by bachbao** [comment]
Great, thanks

**Comment by rupeshknn** [comment]
Can I give it a try?

**Comment by divshacker** [comment]
> Can I give it a try?

Sure you can.

**Comment by rupeshknn** [comment]
@frankharkins I was also thinking of replacing the sideband method using the more direct `SetFrequency` method to perform spectroscopy of |1> to |2>

**Comment by rupeshknn** [comment]
@divshacker @bachbao is this the correct graph you guys were referring to?
![image](https://user-images.githubusercontent.com/33568503/120095841-ce1f6400-c145-11eb-827f-1396217e47d6.png)

**Comment by bachbao** [comment]
The frequency sweep pulse schedule seems correct can you show me the graph of the frequecy sweep?

**Comment by rupeshknn** [comment]
Okay, so there are a couple of issues I found. 

1. Running the default `drive_power=0.3` gave 2 peaks for the 0-->1 spectroscopy (run on real `'ibmq_armonk'`)
![image](https://user-images.githubusercontent.com/33568503/120102035-c9b77300-c166-11eb-8072-cdedc0d42c2f.png)


After this point, I started using the Aer pulse simulator since I realised I had to change some parameters and the real device had a long queue
 `armonksim=PulseSimulator.from_backend(provider.get_backend('ibmq_armonk'))`

2. Running the simulator at `drive_power=0.1` gave a clean single peak Lorentzian:
![image](https://user-images.githubusercontent.com/33568503/120101953-63caeb80-c166-11eb-9c78-f5c412a12b6a.png)


and going on with the notebook a lot the values like 01 pi amplitude, also seem off. I'm running them all of them on the real backend one by one now... got to see...

**Comment by rupeshknn** [comment]
@frankharkins  is there anyone currently working on it or should i create a  new issue and start working on a PR?

**Comment by divshacker** [comment]
Hey the changes look good. I am curious about how the driver_power is giving wrong results for 0.3 and and working for 0.1 .
Is there any change done in SamplePulse to WaveForm that is affecting this ?

**Comment by rupeshknn** [comment]
No, this is before the sideband comes into the picture. This is Just the 01 spectroscopy.  
if you look at the 1 to 2 spectroscopy theory given in the textbook, there are 2 ways to achieve it:
![image](https://user-images.githubusercontent.com/33568503/120168263-4e17fd80-c21c-11eb-822d-7034899beede.png)
 the `drive_power=0.3` gives roughly two peaks, the 2nd peak stands for the 0 to 2 transition. So, I guess 0.3 was enough power to excite the 02 transition

**Comment by frankharkins** [comment]
Fixed, thanks!
