### ISSUE TITLE
Typo in section 1.2

### ISSUE THREAD

**Issue by shil-m** [qiskit-community/qiskit-textbook#1095]
This is what is given:
`The command qc.measure(j,j) adds a measurement to our circuit qc that tells qubit j to write an output to bit j.`
Expected is:
`The command qc_output.measure(j,j) adds a measurement to our circuit qc that tells qubit j to write an output to bit j.`

**Comment by bopardikarsoham** [comment]
Ohh yes! I would like to work on this issue!

**Comment by frankharkins** [comment]
@bopardikarsoham thank you! Assigned

**Comment by bopardikarsoham** [comment]
Yes I have a put a pull request #1100 for the same

**Comment by divshacker** [comment]
At last you did your first contribution @bopardikarsoham  
Congrats

**Comment by bopardikarsoham** [comment]
No mate @divshacker I have done one or two before. But anyways thanks!

**Comment by pritamsinha2304** [comment]
Is this fixed ?

**Comment by divshacker** [comment]
> Is this fixed ?

Yes it is fixed check #1100

**Comment by pritamsinha2304** [comment]
@divshacker Ok. But why is this still open ?

**Comment by divshacker** [comment]
> @divshacker Ok. But why is this still open ?

Well I don't know maybe @bopardikarsoham  would know it

**Comment by bopardikarsoham** [comment]
I have given a pull request regarding this issue and have informed the IBM team @divshacker @pritamsinha2304. They will give me a review on it and my PR #1100 will get merged.

**Comment by pritamsinha2304** [comment]
@bopardikarsoham Ok. cool.

**Comment by shil-m** [comment]
Sorry, it's closed now.
