### ISSUE TITLE
would like to add a new tutorials for quantum repeaters and quantum network!

### ISSUE THREAD

**Issue by SakibulIslamSazzad** [qiskit-community/qiskit-textbook#1102]
**What should the reader gain from this new content?**
Harnessing communication using quantum mechanics, there should be quantum internet. Hence there should be a tutorial using Qiskit for quantum Internet and communication. One of the key components of the quantum communication is quantum repeater, that I am missing in the textbook 

**Where do you expect this new content to fit in with the current content?**
 May be in ** chapter 4** where applications are described and it can be also fit in **chapter 3**. I think Quantum Repeaters best fit in after QKD tutorial [3.12] 

**What material should this new content be based on?**

- [](https://arxiv.org/abs/1509.08435) this article is based on quantum repeaters and also categorized into three generations of QR
- For quantum repeaters there needs some theory like entanglement distillation and purification, to employ them Nielsen and Chuang book can be followed. In 12.5.3 of 10th edition they are described
- another good resources will be this: [](https://arxiv.org/pdf/2009.04584.pdf) 

**Are you proposing to write this new content?** (y/n)
yes, I would like to work on this content and am proposing to work on it.

**Comment by frankharkins** [comment]
@SakibulIslamSazzad how do you propose to use Qiskit for this? I don't know anything about quantum repeaters so not sure what tools we have for it in Qiskit.

**Comment by SakibulIslamSazzad** [comment]
@frankharkins I shared some links the issue but it didn't came out. Whatever Quantum Repeaters (QR) is analogue to amplifiers in communications. I am using general explanations, technically may be incorrect. In classical communications, errors, noise etc happened after a certain amount of channel lengths, hence an amplifier is used to copy the initial the bit states. In Quantum Communication, we cant copy qubit states due to No Cloning theorem. Hence QR is used to generate high fidelity entangled states. Here is an article for QR initial understanding [[Link](https://arxiv.org/abs/1509.08435)]

To implement using IBM quantum here is another good article[[Link](https://arxiv.org/abs/2009.04584)]. I am looking on into things how can I implements this QR in qiskit, will after end of ongoing IQC2021. Let me know if want to know more about the initial idea.

**Comment by frankharkins** [comment]
@SakibulIslamSazzad ok, I think this should live in the 'demos' section. Can you please write a draft table of contents so we can see what the page will look like?

**Comment by SakibulIslamSazzad** [comment]
@frankharkins yes, I can do that. I am on it.

**Comment by pritamsinha2304** [comment]
@SakibulIslamSazzad So you are working on this also ?

**Comment by SakibulIslamSazzad** [comment]
@frankharkins I have written a draft about contents on overleaf. I am sharing it with you. Let me know if you can get access to it. [](https://www.overleaf.com/read/jssdttrgjnmz)

@pritamsinha2304 yes I am working on it.

**Comment by frankharkins** [comment]
@SakibulIslamSazzad thanks for writing up the proposal draft. The topics look well thought out and interesting, but after discussing with colleagues, I think this is out of scope of the textbook at the moment. We don't really have anywhere for it to live, and the textbook / qiskit is more focused on algorithms.
