### ISSUE TITLE
Typo, Content mismatch

### ISSUE THREAD

**Issue by kafee651** [qiskit-community/qiskit-textbook#1118]
**Content shown in the page https://qiskit.org/textbook/ch-states/single-qubit-gates.html is not matching with git page**

**Describe what you expect to see**
qiskit.org page: ![image](https://user-images.githubusercontent.com/3341517/119510633-4d501900-bd8f-11eb-9e1b-c74322eb72d6.png)
in Gethub page: ![image](https://user-images.githubusercontent.com/3341517/119510742-66f16080-bd8f-11eb-84cb-e87bbd3ed90a.png)

**Comment by divshacker** [comment]
May I work on this @kafee651 ?

**Comment by frankharkins** [comment]
Looks to be fixed on the site
