### ISSUE TITLE
Suggestion for a better way of representation of qiskit version info.

### ISSUE THREAD

**Issue by divshacker** [qiskit-community/qiskit-textbook#1121]
**Is your feature request related to a problem? Please describe.**
No it is not related to a problem.

**Describe the solution you'd like**
There is a last cell in every qiskit textbook file containing the version info of qiskit. I want to suggest a better way of representation. 
Use this 
> import qiskit.tools.jupyter
%qiskit_version_table

Instead of this 
> import qiskit
qiskit.__qiskit_version__

**Describe alternatives you've considered**
Nope nothing 

**Additional context**
It will improve the representation from 
![Screenshot from 2021-05-27 15-36-20](https://user-images.githubusercontent.com/55018955/119808415-b9528e80-bf01-11eb-9921-3faa011d20a2.png)

 To this

![Screenshot from 2021-05-27 15-36-23](https://user-images.githubusercontent.com/55018955/119808471-c7081400-bf01-11eb-8f14-6c5019473f0b.png)

**Comment by frankharkins** [comment]
I'm happy to use the version table, I think it's useful to see the OS. What does the `%qiskit_copyright` do? Is it necessary?

**Comment by divshacker** [comment]
I wiil remove it. It accidentally came with the screenshot. I will not pust it in my pr.Well If you see the code that I have given above apart from screenshot doesn't have the `%qiskit_copyright`.

**Comment by frankharkins** [comment]
I say let's leave it out

**Comment by divshacker** [comment]
Yeah sure, So do I start making PR?

**Comment by pritamsinha2304** [comment]
@divshacker Is it fixed ?

**Comment by divshacker** [comment]
I am working on it . 
@pritamsinha2304

**Comment by pritamsinha2304** [comment]
@divshacker Ok. Cool
