### ISSUE TITLE
In Japanese edition, there is no image about half adder of chapter 4.3

### ISSUE THREAD

**Issue by taketakeyyy** [qiskit-community/qiskit-textbook#1126]
**Describe the issue**
In Japanese edition, there is no image about half adder of Chapter "4.3 Qiskitで足し算を行う".

https://github.com/qiskit-community/qiskit-textbook/blob/master/i18n/locales/ja/ch-states/atoms-computation.ipynb

（日本語版において、"4.3 Qiskitで足し算を行う"章の半加算器に関する画像がありません。）

**Describe what you expect to see**
If you have the image, add it please. If you have no image, I think that it is ok to add following image:
qiskit-textbook/content/ch-states/images/half-adder.svg

（もし画像をお持ちの場合は、追加してほしいです。もしお持ちでない場合は、英語版の流用でも大丈夫だと思います）

**Comment by paniash** [comment]
@taketakeyyy Hi! Looks like a web-hosted image was being used in the notebook. The url however doesn't contain an image anymore. I have opened a PR for the same. Thanks for reporting this!

**Comment by frankharkins** [comment]
closing via #1131
