### ISSUE TITLE
Class QuantumCircuit conflicts with qiskit QuantumCircuit

### ISSUE THREAD

**Issue by khanalg44** [qiskit-community/qiskit-textbook#1136]
**Describe the bug**

When running the notebook on `Chapter 4.1.5` titled `Hybrid quantum-classical Neural Networks with PyTorch and Qiskit` the defined class `QuantumCircuit` clashes with the qiskit module `QuantumCircuit`

** Proposed Solution**
Rename the class `QuantumCircuit` as something else: for example `QuantumCircuitLocal`

**To Reproduce**
0. put `from qiskit import *` at the begining and run the code and it will give error as shown in the screenshot.
1. See error as a **Screenshots**

<img width="983" alt="Screen Shot 2021-06-02 at 10 29 02 AM" src="https://user-images.githubusercontent.com/40899146/120498622-5c395b80-c38d-11eb-8be6-4a102b4b0777.png">

**Expected behavior**

**Version info***
For qiskit problems, please provide the output of:
```
import qiskit
qiskit.__qiskit_version__
```
For website problems please state device / OS / browser.

**Additional context**

**Comment by divshacker** [comment]
Hey @khanalg44  can you please specify which environment you are using (Cloud/Local)? because I can not reproduce this error in my local machine

**Comment by paniash** [comment]
@khanalg44 Hi! In the chapter, we are not really using `QuantumCircuit` provided by qiskit but rather implementing our own. As such there are no clashes with importing. The clash only occurs if you import explicity (as you mentioned in the OP) but is not required in the code examples present in the chapter.

Hope this helps. :-)

**Comment by khanalg44** [comment]
@paniash Thanks for responding. You got my point. Working with qiskit circuits and having a class named QuantumCircuit confused me and the code itself to use which one. I solved it by renaming the class as QuantumCircuitLocal and it works.
