### ISSUE TITLE
[8.1] Vectors: "Down" the x-axis

### ISSUE THREAD

**Issue by shil-m** [qiskit-community/qiskit-textbook#1152]
**Describe the issue**
Section: Vectors and Vector Spaces
`This vector can be visualized as an arrow pointing in the direction of  3 units down the x axis and 5 units up the y axis:`
I think using "down" the x axis is ambiguous. It doesn't really tell about a particular direction especially when we are using "up" the y axis. So, it sounds a bit confusing.

**Describe what you expect to see**
In my suggestion I think it is better to use something more general like "along" the x axis and "along" the y axis.

I am open to suggestions. I am looking forward to make the changes.
![Screenshot (69)_LI](https://user-images.githubusercontent.com/61791872/121462127-bd84ae80-c9cd-11eb-848b-2befb9cda966.jpg)

**Comment by divshacker** [comment]
Hey @shil-m I think it is a great Idea. of using `along` instead of `up` or `down`. May I work on this issue or you want to take this also ?

**Comment by shil-m** [comment]
@divshacker Oh, I already made the changes. Just about to make a PR :)
