### ISSUE TITLE
Plotly graphing library for visualization of Bloch sphere.

### ISSUE THREAD

**Issue by Jwala-1908** [qiskit-community/qiskit-textbook#1158]
### **Describe the problem**

Sometimes it is difficult to pinpoint where the arrow denoting the statevector is pointing on a Bloch Sphere, 
like in the following case-

![bloch](https://user-images.githubusercontent.com/53686844/121589887-3f6bea80-ca55-11eb-8ebf-f5fc35bf3f23.png)

It is not clear (without additional input about the state) whether the arrow lies in the "xz"-plane or the "xy"-plane.

The above state has been generated by the following circuit:

```
qc = QuantumCircuit(1)
qc.h(0)
qc.rz(np.pi/4, 0)
```
---
### **Describe the expected solution**

I would like to suggest and contribute to using the Plotly graphing library to create visualizations of Bloch Sphere. Below is an example implementation I made using the [plotly library for Python](https://plotly.com/python/).

https://user-images.githubusercontent.com/53686844/121590791-5ced8400-ca56-11eb-90c3-d34b30ecb9d2.mp4

The interactivity of the graphs would aid in gaining strong intuition of Bloch Sphere representation.

---
Comments and suggestions are welcome!

**Comment by divshacker** [comment]
I think it is a great idea. But this issue is not at the right place. I think opening this issue in Qiskit/qiskit will be best I suppose.

**Comment by frankharkins** [comment]
@Jwala-1908 this looks really nice, but I agree with @divshacker. We did experiment with having visualizations available via a separate `qiskit-textbook` Python package but it just seemed to confuse people.

**Comment by Jwala-1908** [comment]
Thanks for your input @frankharkins ! I'll propose the enhancement to qiskit-terra then, since that's where the visualizations are implemented.

**Comment by frankharkins** [comment]
I'll close this issue then  :)
