### ISSUE TITLE
Wrong definition of RZ in qiskit textbook, it is the phase gate P

### ISSUE THREAD

**Issue by Costor** [qiskit-community/qiskit-textbook#1160]
Hi,
I believe the Qiskit textbook gives a wrong definition of RZ [here](https://qiskit.org/textbook/ch-states/single-qubit-gates.html#5.-The-R%CF%95-gate--) in the chapter on simple gates and Rphi alias RZ.
What is described there by the explicit matrix definition is actually the phase gate P [PhaseGate](https://qiskit.org/documentation/stubs/qiskit.circuit.library.PhaseGate.html#qiskit-circuit-library-phasegate). Also the statement RZ(pi)=Z is not true, it would be correct for P(pi)=Z.  The actual definition of the RZ-gate is [RZGate](https://qiskit.org/documentation/stubs/qiskit.circuit.library.RZGate.html#qiskit-circuit-library-rzgate).

So you might either correct every notion of Rphi or RZ into P at this location,  or correct the matrix representation and remove the statement RZ(pi)=Z.

Note that though RZ and P only differ by a phase factor they are not replacements of each other: the phase difference factor becomes crucial in qubit dimensions > 1, e.g. in controlled gates, see e.g. explanation in CRZ [documentation](https://qiskit.org/documentation/stubs/qiskit.circuit.library.CPhaseGate.html#qiskit-circuit-library-cphasegate) and CP [documentation](https://qiskit.org/documentation/stubs/qiskit.circuit.library.CPhaseGate.html#qiskit-circuit-library-cphasegate) on this.

**Comment by paniash** [comment]
@Costor Hi! Thanks for reporting this. Having a quick glance at the references, I would go with the former choice and replace all instances of Rphi with P. Let's see what others have to think about it. @frankharkins

**Comment by paniash** [comment]
I've made a PR for now, going with the former choice. Let's come to a common consensus and I'll modify the PR accordingly. :-)

**Comment by frankharkins** [comment]
@paniash @Costor is this fixed in #1161?

**Comment by paniash** [comment]
> @paniash @Costor is this fixed in #1161?

AFAIK, yes.

**Comment by frankharkins** [comment]
Thank you!
