### ISSUE TITLE
"Single Qubit Gates" section seems outdated

### ISSUE THREAD

**Issue by EgrettaThula** [qiskit-community/qiskit-textbook#1163]
**Is your feature request related to a problem? Please describe.**

The last two paragraphs in "Single Qubit Gates" section are:

> Before running on real IBM quantum hardware, all single-qubit operations are compiled down to  U1,  U2  and  U3. For this reason they are sometimes called the physical gates.

> It should be obvious from this that there are an infinite number of possible gates, and that this also includes Rx and Ry-gates, although they are not mentioned here. It must also be noted that there is nothing special about the Z-basis, except that it has been selected as the standard computational basis. That is why we have names for the S and T-gates, but not their X and Y equivalents (e.g.  √X [...]

My notes:
- U1, U2, and U3 are deprecated.
- This [page](https://quantum-computing.ibm.com/services), displays a different set of gates as the physical gates.
- Qiskit provides the square root of X a name since version 0.20.0 (SX gate)

**Describe the solution you'd like**
The two paragraphs need to be up to date.

**Comment by epelaaez** [comment]
Adding to the list of things outdated in that section, #1160 found that the definition of Rz is wrong and is actually the definition of P. 

And just one consistency/aesthetic comment. On the textbook, the U3 gate (that should be changed to U) is defined as follows:

![image](https://user-images.githubusercontent.com/63567458/121919620-7aad3880-cd37-11eb-8d54-f43c622bbb61.png)

And in the documentation for the U gate, it is defined as:

![image](https://user-images.githubusercontent.com/63567458/121919659-87319100-cd37-11eb-9035-43fdb640c61b.png)

Notice that on the textbook *i* from the exponent of the bottom right element isn't factored out but in the documentation it is. Just for consistency, I believe it should be the same in both places. And, personally, the *i* factored out looks better.

**Comment by tgag17** [comment]
Hi! Can I work on this issue? Thank you!
