### ISSUE TITLE
Update code in Japanese translation

### ISSUE THREAD

**Issue by frankharkins** [qiskit-community/qiskit-textbook#1170]
**Describe the issue**
Some of the code cells in the Japanese translation of the textbook are outdated and might not work with the latest version of Qiskit. These files need to be updated by a Japanese speaker to match the English version of the textbook (under `i18n/locales/ja/`):

- [ ] `ch-algorithms/shor.ipynb`
- [ ] `ch-algorithms/defining-quantum-circuits.ipynb`
- [ ] `ch-algorithms/simon.ipynb`
- [x] `ch-algorithms/deutsch-josza.ipynb` (assigned @taketakeyyy)
- [ ] `ch-prerequisites/python-and-jupyter-notebooks.ipynb`
- [ ] `ch-prerequisites/setting-the-environment.ipynb`
- [ ] `ch-states/representing-qubit-states.ipynb`
- [ ] `ch-ex/hello-qiskit.ipynb` (assigned @emi-aimy)
- [ ] `ch-quantum-hardware/measurement-error-mitigation.ipynb`
- [ ] `ch-quantum-hardware/transpiling-quantum-circuits.ipynb`
- [ ] `ch-quantum-hardware/transmon-physics.ipynb` (assigned @kUmezawa)
- [ ] `ch-quantum-hardware/cQED-JC-SW.ipynb`
- [ ] `ch-quantum-hardware/error-correction-repetition-code.ipynb`
- [ ] `ch-quantum-hardware/accessing_higher_energy_states.ipynb` (assigned @kUmezawa)
- [ ] `ch-quantum-hardware/calibrating-qubits-pulse.ipynb` (assigned @kUmezawa)
- [ ] `what-is-quantum.ipynb`
- [ ] `ch-appendix/qiskit.ipynb`
- [ ] `ch-appendix/linear_algebra.ipynb`
- [ ] `ch-applications/satisfiability-grover.ipynb`
- [ ] `ch-applications/hhl_tutorial.ipynb`
- [ ] `ch-machine-learning/machine-learning-qiskit-pytorch.ipynb`
- [ ] `ch-gates/multiple-qubits-entangled-states.ipynb`
- [ ] `ch-gates/more-circuit-identities.ipynb`

**Describe what you expect to see**
The code cells in the notebooks above should be changed to match those in the English translation, with any relevant markdown cells changed too so everything still makes sense.

> :exclamation: **Note:** If you want to work on this, please comment here with the files you are working on so we don't duplicate effort.

**Comment by emi-aimy** [comment]
@frankharkins 
I would like to do ch-ex/hello-qiskit.ipynb.

**Comment by kUmezawa** [comment]
@frankharkins
I would like to do ch-quantum-hardware/calibrating-qubits-pulse.ipynb , accessing_higher_energy_states.ipynb and transmon-physics.ipynb.

**Comment by taketakeyyy** [comment]
Hello, @frankharkins
I would like to do ch-algorithms/deutsch-josza.ipynb.

**Comment by taketakeyyy** [comment]
> Hello, @frankharkins
> I would like to do ch-algorithms/deutsch-josza.ipynb.

In relation to #1169, I think `ch-algorithms/deutsch-josza.ipynb` has already been done.
