### ISSUE TITLE
TSP using QPE and Quantum Coin Game

### ISSUE THREAD

**Issue by pritamsinha2304** [qiskit-community/qiskit-textbook#1172]
**What should the reader gain from this new content?**
Implementing Travelling Salesman problem using Quantum Phase Estimation and Quantum Coin Game. One can learn how to use QPE to solve problem and Quantum Coin Game using entanglement.

**Where do you expect this new content to fit in with the current content?**
In the Games and Demos Section.

**What material should this new content be based on?**
TSP: https://arxiv.org/abs/1805.10928
Quantum Coin Game: It is not not based on any papers, but concept and implementation.

**Are you proposing to write this new content?** (y/n)
Yes

**Comment by pritamsinha2304** [comment]
@frankharkins I would like to do this 2 projects for the contribution for Qiskit advocate. Is that okay ?

**Comment by frankharkins** [comment]
@pritamsinha2304 thanks for proposing to write this, can you share a draft table of contents for the chapter so we can see what you're planning on including please?

**Comment by pritamsinha2304** [comment]
@frankharkins Thanks for replying. I will share with a draft table of contents within 1-2 days.

**Comment by pritamsinha2304** [comment]
@frankharkins I have included a brief table of contents of what am I planning to introduce.
[https://www.overleaf.com/project/60d30c729bd20b1e646fbfa9](Link to Overleaf)

**Comment by SakibulIslamSazzad** [comment]
@pritamsinha2304, and me decided to work on together on this project. I think its okay, @frankharkins.
