### ISSUE TITLE
[3.10] Problems in simulator used in  content and code

### ISSUE THREAD

**Issue by divshacker** [qiskit-community/qiskit-textbook#1191]
**Describe the issue**
In this section of textbook clearly two simulation methods are used Statevector and Qasm . But there is a problem in content as these simulation method are part of `aer_simulator`. One can clearly see that only `aer_simulator` is defined in code but the statevector and qasm are used in content.  

**Describe what you expect to see**
I think one should fix the content and change all the simulators to `aer`  simulation methods and make it compatible with statevector and qasm

**Comment by frankharkins** [comment]
We need to change the text (not the code), e.g. "Using the statevector simulator" -> "Using statevector simulation"

**Comment by tgag17** [comment]
Hi! Can I work on this issue?

**Comment by divshacker** [comment]
Sure go ahead!
