### ISSUE TITLE
[3.3 ベルンシュタイン・ヴァジラニ アルゴリズム] s=11 -> s=011

### ISSUE THREAD

**Issue by taketakeyyy** [qiskit-community/qiskit-textbook#1196]
**Describe the issue**
https://qiskit.org/textbook/ja/ch-algorithms/bernstein-vazirani.html#4.-%E6%BC%94%E7%BF%92-

> 上記のベルンシュタイン・ヴァジラニの実装は、秘密のビット文字列 s=11 の場合のものです。

s=011 の間違いではないでしょうか？（英語版だとs=011です）

**Describe what you expect to see**
s=11 -> s=011

**Comment by divshacker** [comment]
May I try to work on this ?

**Comment by divshacker** [comment]
Done @taketakeyyy
