### ISSUE TITLE
[1.3 量子ビット状態を表現する] p ( | x ⟩ ) = | ⟨ x | ψ ⟩ | 2? or | ⟨ ψ | x ⟩ | 2?

### ISSUE THREAD

**Issue by taketakeyyy** [qiskit-community/qiskit-textbook#1198]
**Describe the issue**
こんにちは。日本語で失礼します。

https://qiskit.org/textbook/ja/ch-states/representing-qubit-states.html#2.1-%E9%9D%9E%E5%B8%B8%E3%81%AB%E9%87%8D%E8%A6%81%E3%81%AA%E3%83%AB%E3%83%BC%E3%83%AB-

上記のURLにおいて、

>  状態 |ψ⟩ を状態 |x⟩ で測定する確率を見つけるには、
> p(|x⟩)=|⟨ψ|x⟩|2

とありますが、英語版では、

> To find the probability of measuring a state  |ψ⟩  in the state  |x⟩  we do:
> p(|x⟩)=|⟨x|ψ⟩|2

となっています。そして、英語版のほうが正しいと思います。

確かに、`p(|x⟩)` の値を求めるのに `|⟨ψ|x⟩|2` と `|⟨x|ψ⟩|2` の値は同じになりますが、一般に `⟨ψ|x⟩=⟨x|ψ⟩*` であり、交換法則は成り立たないはずです。そして「状態 |ψ⟩ を状態 |x⟩ で測定する確率を見つける」という文脈においては、`|⟨x|ψ⟩|2`のほうが自然な書き方だと思います。

同様に、

> 状態 |q0⟩ を見ると、|0⟩ を測定する確率は確かに 0.5 であることがわかります。

以降に続く式も修正したほうがよいと思います。

どう思いますか？

**Describe what you expect to see**
* `⟨ψ|x⟩` を `⟨x|ψ⟩` に修正する
* `⟨q0|0⟩` を `⟨0|q0⟩` に修正する

**Comment by jonathan322021** [comment]
Can you type  in english the issue, the global community will be able to fix this?

**Comment by jwoehr** [comment]
Google Translate does a pretty good job. Slightly cleaned up:
---------------------------------------------------------------------------------------

**Describe the issue**
Hello. Excuse me in Japanese.

https://qiskit.org/textbook/ja/ch-states/representing-qubit-states.html#2.1-%E9%9D%9E%E5%B8%B8%E3%81%AB%E9%87%8D % E8% A6% 81% E3% 81% AA% E3% 83% AB% E3% 83% BC% E3% 83% AB-

At the above URL

    To find the probability of measuring state | ψ⟩ in state | x⟩
    p (| x⟩) = | ⟨ψ | x⟩ | 2

However, in the English version, it reads:

    To find the probability of measuring a state | ψ⟩ in the state | x⟩ we do:
    p (| x⟩) = | ⟨x | ψ⟩ | 2

And I think the English version is more correct.

Sure, the values ​​of | ⟨ψ | x⟩ | 2 and | ⟨x | ψ⟩ | 2 are the same to find the value of p (| x⟩), but in general ⟨ψ | x⟩ = ⟨x | ψ⟩ *, and the commutative law should not hold. And in the context of "finding the probability of measuring state | ψ⟩ with state | x⟩", I think | ⟨x | ψ⟩ | 2 is a more natural way of writing.

Similarly

    Looking at the state | q0⟩, we can see that the probability of measuring | 0⟩ is certainly 0.5.

I think you should also modify the formulas that follow.

What do you think?

**Describe what you expect to see**

    Modify ⟨ψ | x⟩ to ⟨x | ψ⟩
    Modify ⟨q0 | 0⟩ to ⟨0 | q0⟩

**Comment by jonathan322021** [comment]
In my opinion I think that's correct,how want to modify the formula.

**Comment by mohitd** [comment]
I agree with @taketakeyyy on the inconsistency and proposed bug fix. From my understanding, a general Hilbert space's inner product is not symmetric but rather conjugate symmetric (as previously stated in equation form). I didn't see anything earlier in the article assuming the amplitudes were real numbers so the arbitrary wavefunction needs to be a ket/vector and the particular state we're interested in should be bra/covector; I think the English version is correct, but maybe the Japanese version accidentally switched the two in this instance.

I don't mind making a PR to fix the equations in the Japanese translation, but I'm not a Japanese speaker so I don't know if the surrounding text describing the equations would still be accurate if I did. Can someone more fluent in Japanese than I verify that we can just change the equation without changing any of the Japanese around it?

**Comment by taketakeyyy** [comment]
Thank you everyone for your opinion. I will make a PR to fix it.
