### ISSUE TITLE
Deploying `master` no longer makes sense

### ISSUE THREAD

**Issue by delapuente** [qiskit-community/qiskit-textbook#1205]
**Describe the bug**
Deploy scripts of the textbook still check if deploying on `master` but `master` has been renamed to `main` and the below checks are out of date:
https://github.com/qiskit-community/qiskit-textbook/blob/ae4fac52accd499df8df40a286831e4c55f110c2/.github/workflows/deploy.workflow.yml#L15

@frankharkins do you still need more than one deployment? 

This is related to https://github.com/Qiskit/qiskit.org/issues/1965#issuecomment-878590296

**Comment by vabarbosa** [comment]
@delapuente when i look at the GitHub action i see it reference `main` (not `master`):

https://github.com/qiskit-community/qiskit-textbook/blob/main/.github/workflows/deploy.workflow.yml#L15

**Comment by frankharkins** [comment]
I didn't even know we were deploying master. It would be quite useful to view the main branch - where is the link for this?

**Comment by delapuente** [comment]
Haha, I think we are no longer doing it but we will have previews in the new textbook @frankharkins !

**Comment by frankharkins** [comment]
@delapuente @vabarbosa can I close this issue?
