### ISSUE TITLE
Wrong text in Qiskit-Learning-material: CX-Gate revisited

### ISSUE THREAD

**Issue by j125330** [qiskit-community/qiskit-textbook#1213]
I think there is an error in the Qiskit Learning material
In https://learn.qiskit.org/course/introduction/entangled-states#the-cx-gate-revisited-20-0
the sentence „If we do the cx now, we will see an effect. It flips the target qubit to as well.“ may be wrong.
I think it is the control Qubit that flips also. So the text should be: „If we do the cx now, we will see an effect. It flips the control qubit to as well.“

**Comment by divshacker** [comment]
Hey I would like to work on it. This Entangle state chapter is not in Old qiskit-textbook and added in qiskit-textbook beta only.
Am I right?
Because If this bug is from the beta version then it can't be fixed by contributors as beta version of textbook code is not public yet

**Comment by j125330** [comment]
Hi Divanshu
I think you're right. It's an Issue in the Beta-Version.

**Comment by frankharkins** [comment]
Should be fixed now.
