### ISSUE TITLE
Deutsch-Jozsa Algorithm: Sec 2. Worked example

### ISSUE THREAD

**Issue by nepomechie** [qiskit-community/qiskit-textbook#1214]
## Describe the Issue
1. The function corresponding to the specified oracle has not been provided. I believe that the function in question is f(x_0,x_1) = x_0 \oplus x_1 (see the attached note DJ_oracle)
2. A check that the proposed circuit indeed
[DJ_oracle.pdf](https://github.com/qiskit-community/qiskit-textbook/files/6832689/DJ_oracle.pdf)
 implements the corresponding phase oracle is not provided. (Again, see the attached note  DJ_oracle.)
3. Qiskit conventions for labeling qubits is not respected, either in the formulas or in the corresponding circuit diagram.

## Expected Solution
See attached note.

**Comment by divshacker** [comment]
Hey @nepomechie  
I found that the function you suggested for the oracle in qiskit textbook is correct. Also your phase oracle is correct. May you please  tell where you are suggesting these changes to add ? 
Also may I work in this  issue?  🙂

**Comment by nepomechie** [comment]
Hello,

Thank you for responding to the “issue" that I posted.

It is my first “issue", so I am not familiar with the process.

Regarding your questions:

> May you please tell where you are suggesting these changes to add ?

As noted in the post, I am suggesting to add this in the part of the textbook on Deutsch-Jozsa Algorithm: Sec 2. Worked example. 

In the worked example, the oracle function is given without any explanation. My suggestions are to: 

(1) provide a proper explanation of the oracle function in the  worked example

(2) rewrite the entire worked example using proper qiskit conventions.


> Also may I work in this issue?


Sure, why not? 

I was not planning to work on this issue myself, but I would be happy to take a look before you submit it.

RN
