### ISSUE TITLE
Content bug in [1.3[2.1]]

### ISSUE THREAD

**Issue by shil-m** [qiskit-community/qiskit-textbook#1215]
**Describe the issue**
In the "Reminder: The Inner Product" section, the elements of the bra vector-matrix in the inner product notation have been separated by commas.
![Screenshot (140)_LI](https://user-images.githubusercontent.com/61791872/126042458-49841072-03cd-4521-a3f7-2d88f15d588d.jpg)

**Describe what you expect to see**
Since in a matrix, the elements are not supposed to be separated by commas, so the COMMAS needs to be REMOVED.

**Comment by divshacker** [comment]
Done
