### ISSUE TITLE
Quantum String Matching Algorithm

### ISSUE THREAD

**Issue by pritamsinha2304** [qiskit-community/qiskit-textbook#1218]
**What should the reader gain from this new content?**
How we can implement quantum side of string matching algorithm.

**Where do you expect this new content to fit in with the current content?**
Algorithms/Applications

**What material should this new content be based on?**
There is 2 different approach of quantum string matching. I intend to implement both-
1. Using Cyclic Shift Operator - https://www.nature.com/articles/s41534-021-00369-3.pdf
2. Using Probabilistic Quantum Memories (PQM) - https://arxiv.org/abs/2106.16173

**Are you proposing to write this new content?** (y/n)
Yes

**Comment by frankharkins** [comment]
I'm happy to go ahead with (1), I think it would fit nicely in the applications chapter. I have some reservations about including (2); I can't see any mention of runtimes for the quantum algorithm, and I'm not sure about 'probabilistic quantum memory'.

**Comment by frankharkins** [comment]
@pritamsinha2304 any news on this? If not I will close the issue

**Comment by frankharkins** [comment]
Please reopen if you want to continue with this.
