### ISSUE TITLE
conjugate transpose of Pauli Y matric is wrong 

### ISSUE THREAD

**Issue by mayankkaizen** [qiskit-community/qiskit-textbook#1273]
Please refer to [this section of The Density Matrix & Mixed states](https://qiskit.org/textbook/ch-quantum-hardware/density-matrix.html#3.-Properties-of-the-Density-Matrix--). in the example under "Unitary Evolution", conjugate transpose of Pauli Y matrix is wrong. 

It should be `[[0, -i],[i,0]]` in place of `[[0, i],[-i,0]]` because Pauli's matrices are Hermitian which means they are their own conjugate-transpose.
![screenshot](https://user-images.githubusercontent.com/11568906/130328703-ec0dc04f-6fbb-4964-8478-00fab9629522.png)

**Describe what you expect to see**

**Comment by divshacker** [comment]
May I work on this ?

**Comment by jwoehr** [comment]
> May I work on this or you are working ?

First one who opens a PR wins :)

**Comment by frankharkins** [comment]
>First one who opens a PR wins :)

While I know this is light hearted, it's best to always check first to avoid duplication of effort :)

**Comment by jwoehr** [comment]
> > First one who opens a PR wins :)
> 
> While I know this is light hearted, it's best to always check first to avoid duplication of effort :)

You're right, of course, Frank, but in this case @divshacker and I had discussed PR life-in-general in Slack DM and I was pretty sure the road was clear on this one. Thanks for the reality check!
