### ISSUE TITLE
2.4: Code snippet says %qiskit_version_table but output shows dict

### ISSUE THREAD

**Issue by dhruvbhq** [qiskit-community/qiskit-textbook#1279]
**Describe the issue**
The code snippet at the end of [section 2.4](https://qiskit.org/textbook/ch-gates/more-circuit-identities.html) seems to be intended to display the Qiskit version table. However, what currently appears is the Qiskit (and component) versions in a dictionary.
![image](https://user-images.githubusercontent.com/61590679/131416912-ca85fdc2-b1af-4d2c-b4d0-963b6abb0b05.png)

**Describe what you expect to see**
The version table, like at the end of [section 3.2](https://qiskit.org/textbook/ch-gates/phase-kickback.html).

If this is picked up, the assignee would need to take care to execute the notebook with the latest version of Qiskit.

**Comment by divshacker** [comment]
Done
