### ISSUE TITLE
[6.1]: Could it be good to have a "gentle" introduction before/in 6.1 Calibrating Qubits with Qiskit Pulse?

### ISSUE THREAD

**Issue by dhruvbhq** [qiskit-community/qiskit-textbook#1291]
**Describe the problem**
The first notebook in chapter 6. Investigating Quantum Hardware Using Microwave Pulses is about the calibration of qubits with Qiskit Pulse [(here)](https://qiskit.org/textbook/ch-quantum-hardware/calibrating-qubits-pulse.html). This chapter is very rich in content and covers a variety of important experimental techniques.

However, going by the general "flow" of the textbook, wouldn't it be good to have a gentle introduction to the world of pulses before [6.1]? I think that can provide the reader with the necessary (although perhaps a bit high-level) motivation for studying pulse level control. (Maybe to just give the reader a feel of the things?)

**Describe the expected solution**
Just curious to know if it could be good to add the suggested content, or to re-order some existing material?

**Comment by frankharkins** [comment]
I agree this would be nice, if you (or anyone else) wants to have a go at this, you should speak to @nbronn and @amirhassank who wrote a lot of these chapters.

**Comment by dhruvbhq** [comment]
Thanks, I would love to contribute. (I am an MSc student at TU Delft in Applied Physics (Quantum computing track)).

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
