### ISSUE TITLE
[Atoms of Computation] Classical bit explanation for measurements

### ISSUE THREAD

**Issue by kevinhartman** [qiskit-community/qiskit-textbook#1309]
**Is your feature request related to a problem? Please describe.**
Currently, it isn't mentioned that measurements are performed into classical bits, and thus the measurement timeline part of the circuit timing diagram can be confusing for newcomers.

For instance, when I was completing [this section](https://qiskit.org/textbook/ch-states/atoms-computation.html#4.3-Adding-with-Qiskit-), I got tripped up and assumed that the `creg` index annotations on the combined measurement timeline were the actual measurement results. This of course does not make sense, since no simulation is involved at that point, but new users (hi 👋) might make that mistake since the expected measurement results would be 0 or 1, and only two `cregs` are used with indices 0 and 1.

![Screen Shot 2021-10-18 at 5 20 06 PM](https://user-images.githubusercontent.com/1374024/137812790-4a747885-6992-4dce-aece-d7ad468db968.png)

**Describe the solution you'd like**
Add a note to the half adder section that the measurement annotations are the classical bit register indices, and briefly mention that measurements are stored in classical registers.

**Describe alternatives you've considered**
Annotate the anatomy of a quantum circuit diagram in the [diagram introduction section](https://qiskit.org/textbook/ch-states/atoms-computation.html#2.-Computation-as-a-diagram-).

**Comment by tansaku** [comment]
I am finding this section confusing, specifically what it means to "execute" the circuit:

```
qc = QuantumCircuit(2,2)
qc.x(0)
qc.cx(0,1)
qc.measure(0,0)
qc.measure(1,1)
qc.draw()
```

this code introduced two new parameter calls which might be explained - I now caught up from the docs:

https://qiskit-test.readthedocs.io/en/latest/api/qiskit.circuit.QuantumCircuit.html

>  E.g.: QuantumCircuit(4) # A QuantumCircuit with 4 qubits
         QuantumCircuit(4, 3) # A QuantumCircuit with 4 qubits and 3 classical bits
         
>  measure(qubit, cbit)
Measure quantum bit into classical bit (tuples).
Parameters:qubit (QuantumRegister|list|tuple) – quantum register
cbit (ClassicalRegister|list|tuple) – classical register

but so executing this circuit involves running a simulation?

**Comment by tansaku** [comment]
ah, I see it does ...
![Screenshot 2022-05-17 at 12 31 52](https://user-images.githubusercontent.com/30216/168801323-e657ef44-a7ed-4fa5-95fb-464947c46e33.png)

**Comment by tansaku** [comment]
but any particular reason to use `measure(qbit_id, classical_id)` instead of `measure_all` here?
