### ISSUE TITLE
[QFT] Quantum Fourier Transform Mistake

### ISSUE THREAD

**Issue by ronf6co** [qiskit-community/qiskit-textbook#1338]
### Describe the issue

In this file:
https://github.com/qiskit-community/qiskit-textbook/blob/main/content/ch-algorithms/quantum-fourier-transform.ipynb 
There is a mistake.
This formula is wrong:
![image](https://user-images.githubusercontent.com/13406570/145023369-dc53be27-6227-4066-814a-7f59e38ea369.png)

### Describe what you expect to see

it should be:
![image](https://user-images.githubusercontent.com/13406570/145023400-dc9a58b3-7826-4858-86e2-f5830987ec09.png)
where:
![image](https://user-images.githubusercontent.com/13406570/145023424-c46b55d2-45a9-4692-9783-aabf4b66cc9b.png)

**Comment by ronf6co** [comment]
also here:
![image](https://user-images.githubusercontent.com/13406570/145024326-55b01b35-357c-4036-a3a0-1cb091ee7db1.png)

**Comment by ronf6co** [comment]
Actually, this is not a mistake, but there is a mathematical identity that is skipped.
It should be more clear

**Comment by paniash** [comment]
Hi! If you'd like, make a PR for the steps that you think are missing. :-)

For now, I am closing this issue.
