### ISSUE TITLE
Citing the textbook

### ISSUE THREAD

**Issue by quantumjim** [qiskit-community/qiskit-textbook#1339]
### Describe the problem

I can't find a guide to citing the textbook or a doi, as there are for other parts of Qiskit. For example, the Authors and Citation guide here
https://github.com/Qiskit/qiskit-terra/blob/main/README.md

### Describe the expected solution

Make a citation guide and doi. Include mention of the paper written on the textbook
https://ieeexplore.ieee.org/document/9605279

**Comment by pandasa123** [comment]
Hey James, I think this can be solved with an auto-generated `Qiskit_Textbook.bib` by the [Qiskit Bot](https://github.com/Qiskit/qiskit-bot) by collecting contributors from the [Qiskit Textbook repo](https://github.com/qiskit-community/qiskit-textbook) and the [Platypus repo](https://github.com/Qiskit/platypus)? 

@javabster, any ideas how to do this?

**Comment by 1ucian0** [comment]
Github has some integration to this: https://github.com/qiskit-community/qiskit-textbook/issues/1339 . I agree that qiskit bot should keep the update.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
