### ISSUE TITLE
[ch-quantum-hardware] OR -> XOR

### ISSUE THREAD

**Issue by ronf6co** [qiskit-community/qiskit-textbook#1341]
### Describe the issue

In the file of [error-correction-repetition-code](https://qiskit.org/textbook/ch-quantum-hardware/error-correction-repetition-code.html#Graph-theoretic-decoding)
"It is therefore the bitwise OR of the syndrome..." It seems that OR is not correct

### Describe what you expect to see

I think that you were meaning XOR
Since if the syndrome is not changing, XOR between current and one before will be 0000 in case of no change. and not OR

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
