### ISSUE TITLE
[2.4.3] CZ/CY instead of CNOT 

### ISSUE THREAD

**Issue by plancker** [qiskit-community/qiskit-textbook#1349]
## Describe the Issue

1. In section 2.4.3 on Controlled Rotations, the line "A controlled R_x(θ) could similarly be made using CNOT gates." seems incorrect. 
2. I assume that the line claims that replacing R_y(θ/2) by R_x(θ/2) (similarly for the -θ case), in the circuit above, we would get a controlled R_x(θ). This is incorrect.
3. Passing |1> through q_0, we get X R_x(-θ/2) X R_x(θ/2)q_1, for q_1, which is just a rotation of 2π around the x-axis (i.e. Identity). Instead we should get R_x(θ)q_1.

## Expected Solution

The line should be replaced by either "A controlled R_x(θ) could similarly be made using CZ gates." or "A controlled R_x(θ) could similarly be made using CY gates."

**Comment by gramolin** [comment]
A controlled R_x(π) gate can be obtained using two CNOT gates as follows:
![image](https://user-images.githubusercontent.com/8160203/147792622-675d01d2-af81-4d80-8b85-94b6af61037f.png)
For an arbitrary rotation angle θ, i.e. for the gate R_x(θ), replace R_y(±π/2) with R_y(±θ/2).

It is shown in section 2.4.3 how to implement an arbitrary controlled-V gate using two controlled-Z gates and single-qubit gates. However, it would be better to use a decomposition with two CNOT gates instead (see Figure 4.6 in [Nielsen and Chuang](http://mmrc.amss.cas.cn/tlb/201702/W020170224608149940643.pdf), for example). In this case, the controlled-V case would be a direct generalization of the controlled R_y, R_z, and R_x gates discussed earlier in that section. Any opinions?

**Comment by plancker** [comment]
Hi, Sorry about the late comment. 

I agree with you that the circuits you provided do indeed give the controlled Rx.

But my issue is about the specific phrasing of this sentence "This method works because the x and y axis are orthogonal, which causes the x gates to flip the direction of the rotation. It therefore similarly works to make a controlled Rz(θ). A controlled Rx(θ) could similarly be made using CNOT gates." This sentence leads the reader to believe that replacing Ry(θ) by Rx(θ) in the following circuit would yield the controlled Rx(θ). This would be incorrect. 

![image](https://user-images.githubusercontent.com/12885576/150982495-966c1a54-0778-474b-b68c-5256b73c1dac.png)

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
