### ISSUE TITLE
Translate the textbook into Chinese

### ISSUE THREAD

**Issue by Beattion** [qiskit-community/qiskit-textbook#1352]
### Describe the problem

No official Chinese version.

### Describe the expected solution

I would like to help translate it into Chinese.

**Comment by bopardikarsoham** [comment]
@Beattion The Chinese translation of the Qiskit Textbook is currently in progress.
More information about joining the Qiskit translation team can be found here:https://github.com/qiskit-community/qiskit-translations

**Comment by bopardikarsoham** [comment]
This issue can be closed now.
