### ISSUE TITLE
Cannot run any examples in section 1.4

### ISSUE THREAD

**Issue by accursoft** [qiskit-community/qiskit-textbook#1357]
### Describe the bug

After pressing any *try* button, it gets stuck in "Waiting for kernel...".

### To Reproduce

Press the *try* button in a code example.

### Expected behavior

Code is run.

### Version info

can't run

### Additional context

Dev tools shows an error `The '6novenvpy3810' kernel is not available. Please pick another suitable kernel instead, or install that kernel.`

**Comment by jwoehr** [comment]
Hmm, I can't get any example to run in any chapter I have tried.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
