### ISSUE TITLE
Code not rendered properly in Beta Version of Qiskit Textbook Chapter - 6.7 Hamiltonian Tomography 

### ISSUE THREAD

**Issue by bopardikarsoham** [qiskit-community/qiskit-textbook#1358]
### Describe the bug

Bugs:-
1) The heading "Fitting Functions" has a typo.
2) In this notebook, equations do not appear to be rendered correctly.

Such errors do not exist in the older version of Qiskit Textbook, but they do exist in the beta version.

### To Reproduce

Changes to this notebook might fix the problem: https://github.com/qiskit-community/qiskit-textbook/blob/main/content/ch-quantum-hardware/hamiltonian-tomography.ipynb

### Expected behavior

The content of the older version and the beta version should be identical.

### Version info

-

### Screenshots

Old version:
![NoerrorHamiltonianTomography](https://user-images.githubusercontent.com/77266161/148772989-cafa46a4-4d32-4673-bad1-cce199f3db0d.jpg)

Beta version: 
![ErrorHamiltonianTomography](https://user-images.githubusercontent.com/77266161/148773034-0fdb5824-aa58-4b26-b386-771ce5bde0e5.jpg)

**Comment by paniash** [comment]
Hi! For any issues related to the beta textbook, please report it in the issue tracker at https://github.com/qiskit/platypus.

I'm closing this for now.
