### ISSUE TITLE
Lab 7. Quantum Simulation as a Search Algorithm

### ISSUE THREAD

**Issue by j125330** [qiskit-community/qiskit-textbook#1360]
### Describe the issue

In Part 1: Hamiltonian Simulation the Time evolution operator is exp(-i x Theta x (|0><0| + |+><+|)). In the follwing sections the circuits are constructed from the operators H1 and H2 which are H1 = exp(-i x Theta x (|0><0|) and  H2 = exp(-i x Theta x ( |+><+|)). But I think the evolution operator is not equal to H1 x H2 because |0><0| and  |+><+| do not commute. And therfore the Circuits for H1 and H2 do not represent the given Hamiltonian, at least not exact. 
I tried to caclulate the states with an exact spectral decomposition of the time evolution operator. But my results are far away from the results showed in the Bloch-Sphere of the Lab in setion 2 of Part A.

### Describe what you expect to see

There should be an explenation why the H1 x H2 can represent the time evolution operator and to what accuracy.

**Comment by ptrcklv** [comment]
You are right, exp[i*theta*(A+B)] != exp(i*theta*A)exp(i*theta*B). Basically that's Trotter's approximation. The error vanishes with O(theta**2).
Would this be what you expect to find? I personally also think it makes sense to mention that briefly in a sentence and refer to "Trotter approximation" or something like that for everyone who wants more details.

**Comment by j125330** [comment]
Thx for your Feedback. Yes, that would help a lot.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
