### ISSUE TITLE
[4.1.3] Content error in the section "The QAOA circuit"

### ISSUE THREAD

**Issue by iR150463** [qiskit-community/qiskit-textbook#1362]
### Describe the issue

Book Section: https://qiskit.org/textbook/ch-applications/qaoa.html#The-QAOA-circuit

In QAOA - The QAOA circuit, I noticed the circuits were appended to the main circuit with the wrong order,

```
qc_qaoa = QuantumCircuit(nqubits)

qc_qaoa.append(qc_0, [i for i in range(0, nqubits)])
qc_qaoa.append(qc_mix, [i for i in range(0, nqubits)])
qc_qaoa.append(qc_p, [i for i in range(0, nqubits)])

qc_qaoa.decompose().decompose().draw()
```
and the wrong circuit were displayed: 
![image](https://user-images.githubusercontent.com/51822951/150329911-cbe8f030-1cd7-4c65-9f11-02110005bb43.png)

### Describe what you expect to see

The correct code should be
```
qc_qaoa = QuantumCircuit(nqubits)

qc_qaoa.append(qc_0, [i for i in range(0, nqubits)])
qc_qaoa.append(qc_p, [i for i in range(0, nqubits)])
qc_qaoa.append(qc_mix, [i for i in range(0, nqubits)])

qc_qaoa.decompose().decompose().draw()
```
and the correct output should be
![image](https://user-images.githubusercontent.com/51822951/150331282-34efca3d-0e87-4bc0-bf38-7ff56da9f740.png)

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
