### ISSUE TITLE
[3.4] Modification to increase clarity

### ISSUE THREAD

**Issue by plancker** [qiskit-community/qiskit-textbook#1365]
### Describe the issue

The issue is more about readability and clarity rather than inaccuracy. The line "Measuring the first register will give an output only if: " is slightly confusing. The measurement will always give an output. I realize that the book wants to convey that most of the terms will cancel, so we can obtain the state |z> only if the given condition holds. 

I realize that this might be nitpicking, but I had to spend some extra time on the sentence to realize what it meant.

### Describe what you expect to see

"Measuring the first register will give an output z only if:" or to be even more clear "Notice that out of the $2^n$ terms only some have nonzero coefficients. Measuring the first register will give an output z only if:"

**Comment by paniash** [comment]
Hi! I understand that you're being pedantic about it but I think the sentence is already clear as it is. It is indeed true that you will get **any** output only if the given condition is satisfied.

**Comment by plancker** [comment]
What happens if I measure in the case, where this condition isn't satisfied?

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
