### ISSUE TITLE
[1.4] Terms 'axis' and 'basis' are mixed up

### ISSUE THREAD

**Issue by 4erf** [qiskit-community/qiskit-textbook#1371]
### Describe the issue

At the beginning of section _4. Digression: Measuring in Different Bases_ we can see the following text:

> We have seen that the Z-axis is not intrinsically special, and that there are infinitely many other bases. Similarly with measurement, we don’t always have to measure in the computational basis (the Z-basis), we can measure our qubits in any basis.

### Describe what you expect to see

I feel instead of the `Z-axis` it was meant to refer to the `Z-basis`, as the topic of discussion is gates & bases, and at the end of the sentence we can see the following reference to bases:

> ...and that there are infinitely many other bases.

We can see a reference to the `Z-basis` on the second sentence as well.

If `Z-axis` is actually correct, then I would suggest a rephrase to improve coherence and not start mentioning axes and then conclude the sentence with bases.

**Comment by paniash** [comment]
@4erf Hi! Thanks for pointing this out. I agree that it should be `Z-basis` instead.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
