### ISSUE TITLE
Quantum Machine Learning Course

### ISSUE THREAD

**Issue by Morcu** [qiskit-community/qiskit-textbook#1379]
### Describe the issue

There are several broken links:

1. Parametrized quanum circuits --> [Parameterized quantum circuits for machine learning](https://learn.qiskit.org/course/machine-learning/parameterized-quantum-circuits#parameterized-16-0) --> Try it --> [IBM Quantum Lab](https://learn.qiskit.org/course/machine-learning/quantum-computing.ibm.com/lab)
2. Training parameterized quantum circuits --> 2 broken links [Natural gradients](https://learn.qiskit.org/course/machine-learning/training-quantum-circuits#training-31-0) --> We can evaluate the natural gradient in Qiskit using the [NaturalGradient](https://qiskit.org/documentation/stubs/qiskit.aqua.operators.gradients.NaturalGradient.html) instead of the [Gradient](https://qiskit.org/documentation/stubs/qiskit.aqua.operators.gradients.Gradient.html)
3. Quantum Feature maps and kernels --> [Quantum feature maps](https://learn.qiskit.org/course/machine-learning/quantum-feature-maps-kernels#quantum-6-0)  --> Let's have a look at the [adhoc](https://qiskit.org/documentation/stubs/qiskit.ml.datasets.ad_hoc_data.html) dataset
4. All the [#textbook-projects](https://join.slack.com/share/enQtMjcxMjMyNzczMzg1Ni02ZDQ5NTAwZGIwMzJhOTQzMzUzZDNjOTg3ZTM3YzY2ZTRmZTRiMWMwZjZmMTczYTEyMTE0NThiMGNiOTFiOWQ0) in  [Project](https://learn.qiskit.org/course/machine-learning/project) 

### Describe what you expect to see

The links should be:

1.  [IBM Quantum Lab](https://quantum-computing.ibm.com/lab)
2. We can evaluate the natural gradient in Qiskit using the [NaturalGradient](https://qiskit.org/documentation/stubs/qiskit.opflow.gradients.NaturalGradient.html) instead of the [Gradient](https://qiskit.org/documentation/stubs/qiskit.opflow.gradients.Gradient.html)
3. Let's have a look at the [adhoc](https://qiskit.org/documentation/machine-learning/stubs/qiskit_machine_learning.datasets.ad_hoc_data.html) dataset
4.  For this link you have to create a permanent link to the channel, normally slack links expire after 14 days

**Comment by divshacker** [comment]
This issue belongs to [Qiskit/platypus](https://github.com/Qiskit/platypus)
Please reopen this issue there

**Comment by frankharkins** [comment]
Thank you! Closed via https://github.com/Qiskit/platypus/pull/795
