### ISSUE TITLE
A new chapter on a hidden shift problem

### ISSUE THREAD

**Issue by BStar14** [qiskit-community/qiskit-textbook#1394]
### What should the reader gain from this new content?

The hidden shift problem relates to the dihedral hidden subgroup problem, just as the factorization relates to the abelian hidden subgroup problem. The algorithm on a boolean function shows exponential speedup on query complexity, while the generalized algorithm on an integer function shows superexponential speedup. We can widely employ concepts on the derivation of orthogonal states, like Simon's algorithm, and the Fourier transform, like Shor's algorithm. After reading this chapter, the student will have more insights into highly efficient quantum algorithms, making connections between Simon's and Shor's algorithms.

### Where do you expect this new content to fit in with the current content?

Chapter 3. After Simon's algorithm, since we employ a similar strategy as in Simon's algorithm.

### What material should this new content be based on?

The main references are on the hidden shift problem on boolean functions [1, 2].  
The extended research on the hidden shift problem on integer functions can be found in reference [3], which also proposes its main application on breaking the Poly1305 encryption.  
Other references present how previous works employed the algorithm to benchmark quantum computers [4, 5].

1. M. Roetteler (2008), "Quantum algorithms for highly non-linear Boolean functions", Proceedings of the 21st Annual ACM-SIAM Symposium on Discrete Algorithms (SODA'10), pp. 448-457, [arXiv:0811.3208](https://arxiv.org/abs/0811.3208) [quant-ph]
2. D. Gavinsky, M. Roetteler & J. Roland (2011), "Quantum Algorithm for the Boolean Hidden Shift Problem", 17th International Computing & Combinatorics Conference (COCOON'11), Lecture Notes in Computer Science 6842 (Springer), pp. 158-167, [doi:10.1007/978-3-642-22685-4_14](https://doi.org/10.1007/978-3-642-22685-4_14), [arXiv:1103.3017](https://arxiv.org/abs/1103.3017) [quant-ph]
3. X. Bonnetain & M. Naya-Plasencia (2018), "Hidden Shift Quantum Cryptanalysis and Implications", In: T. Peyrin , S. Galbraith (eds) Advances in Cryptology – ASIACRYPT 2018, Lecture Notes in Computer Science, vol 11272, Springer, Cham, [doi:10.1007/978-3-030-03326-2_19](https://doi.org/10.1007/978-3-030-03326-2_19)
4. K. Wright, K. M. Beck, S. Debnath et al. (2019), "Benchmarking an 11-qubit quantum computer", Nat Commun 10, 5464, [doi:10.1038/s41467-019-13534-2](https://doi.org/10.1038/s41467-019-13534-2)
5. S. Bravyi & D. Gosset (2016), "Improved classical simulation of quantum circuits dominated by Clifford gates", Phys. Rev. Lett. 116, 250501, [doi:10.1103/PhysRevLett.116.250501](https://doi.org/10.1103/PhysRevLett.116.250501), [arXiv:1601.07601](https://arxiv.org/abs/1601.07601) [quant-ph]

### Are you proposing to write this new content? (y/n)

Yes, we are continuing this project after the Qiskit Hackathon Korea 2022 - [issue #13](https://github.com/qiskit-community/qiskit-hackathon-korea-22/issues/13) - [GitHub repo](https://github.com/Team-Hidden-Name/hidden-shift-problem). We are looking for some feedbacks on complementing the project and making PR.

**Comment by frankharkins** [comment]
Thanks for making an issue. For context, we've discussed this via Slack ([link](https://qiskit.slack.com/archives/C024ELK40TW/p1646896122518039)).
