### ISSUE TITLE
[3.5.4] The Quantum Fourier transform (difficult to understand)

### ISSUE THREAD

**Issue by alan23273850** [qiskit-community/qiskit-textbook#1405]
### Is your feature request related to a problem? Please describe.

The original derivation relies on binary expansions only from texts instead of from figures. I personally think it difficult to understand, so I've found another YouTube [video](https://www.youtube.com/watch?v=zzUMn3ykey8&t=776s), which supplements this part. And I hope it would improve the original content.

### Describe the solution you'd like

Another presentation based on clear binary expansion like this:
![image](https://user-images.githubusercontent.com/10044077/162870471-5be2875d-f24f-4ffa-b7c9-11a24d8a6a6d.png)

If possible, I hope the authors can also explain the correctness of each step.
This figure is of course extracted from https://www.youtube.com/watch?v=zzUMn3ykey8.

### Describe alternatives you've considered

None.

### Additional context

Thank you very much!

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
