### ISSUE TITLE
[3.6.1.2] Quantum Phase Estimation - Mathematical Foundation

### ISSUE THREAD

**Issue by alan23273850** [qiskit-community/qiskit-textbook#1406]
### Is your feature request related to a problem? Please describe.

The explanation of phase kickback in controlled-U gates is not very clear.

### Describe the solution you'd like

I suggest to derive it from the definition of controlled U-gates as explained on [Wikipedia](https://en.wikipedia.org/wiki/Quantum_logic_gate#Controlled_gates),
![image](https://user-images.githubusercontent.com/10044077/163113903-2aa6b0bf-8b7f-4ecc-86a5-bf69cebc1dc8.png)

instead of this one.
![image](https://user-images.githubusercontent.com/10044077/163113974-f42e89dc-29e4-4078-a102-a17e9d7d42d3.png)

### Describe alternatives you've considered

None.

### Additional context

Besides, section [2.3 Phase Kickback](https://qiskit.org/textbook/ch-gates/phase-kickback.html) only uses two specific gates to illustrate the phenomenon of phase kickback. I think a derivation in the case of a universal controlled-U gate should be provided in that section. Otherwise, it makes people hard to realize that a universal controlled-U gate can also have phase kickback.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
