### ISSUE TITLE
[3.10.2] New section on continuous time quantum walks

### ISSUE THREAD

**Issue by Anantha-Rao12** [qiskit-community/qiskit-textbook#1409]
### Is your feature request related to a problem? Please describe.

Chapter 3.10 provides a very concise description of quantum walks and then goes on to implement a search algorithm using quantum phase estimation with the Szedgedy quantum walk. However, not much is mentioned about the two main types of quantum walks that are used in algorithm development, namely:
1. Discrete-time quantum walks (coined walks obtained from discrete-time Markov chain models)
2. Continuous-time quantum walks (based on continuous-time Markov chain models)

The chapter only talks about discrete-time walks (Szedgedy walk is a type of discrete walk)

### Describe the solution you'd like

1. A section that discusses the origin of discrete-time quantum walks (Y. Aharonov et al 1993) and continuous-time quantum walks (Farhi et al 1998) and their physical significance. 
2. If possible a section that implements continuous-time quantum walks on hypercube graphs using qiskit. [[Ref1](https://arxiv.org/pdf/2012.14386.pdf), [Ref2](https://iopscience.iop.org/article/10.1088/1361-6455/ab63ad/meta)]

References:
[1] Kempe, J. (2003). Quantum random walks an introductory overview. Contemporary Physics, 44(4), 307-327.
[2] Portugal, R. (2013). Quantum walks and search algorithms (Vol. 19). New York: Springer.

### Describe alternatives you've considered

- A Section 2. D in chapter 5.10 on continuous-time quantum walks

### Additional context

- Continuous-time quantum walks (CTQW) have been observed in many physical systems (Ex: A quantum kicked rotor performs a CTQW in momentum space) and such physical systems can be used as testbeds for analog quantum searches ([Reference](https://arxiv.org/abs/2002.09139)). 
- A section on CTQW in the Qiskit textbook will benefit the reader and provide a complete picture of quantum walks and search algorithms.

**Comment by frankharkins** [comment]
Hi, sorry for the slow response. Thanks for offering to contribute to the textbook, unfortunately we're not accepting new content at this time. We still think community-driven content is really valuable, and we're working to create an appropriate place for it within the textbook platform. Until then, I highly encourage you to continue to share your work through other channels. 

I'm going to close this issue, but please let me know if I can support or help in any way.
