### ISSUE TITLE
New Section on Brassard Hoyer Tapp (BHT) Algorithm

### ISSUE THREAD

**Issue by Gopal-Dahale** [qiskit-community/qiskit-textbook#1422]
### What should the reader gain from this new content?

After reading this chapter, the student will understand the application of Grover's search in finding collisions in cryptographic hash functions. The student will learn how efficient this is and also its limitations. The student will understand that not every quantum algorithm described is the best suitable and sometimes classical algorithms with the help of parallelization can outperform them (in this case it is the Parallel Rho algorithm). 

### Where do you expect this new content to fit in with the current content?

Either in Chapter 4, section 4.2 Implementations of Recent Quantum Algorithms, or a separate section needs to be created in chapter 4 specifically for applications of quantum algorithms in cryptanalysis.

### What material should this new content be based on?

The content is based of the paper by [Gilles Brassard](https://link.springer.com/chapter/10.1007/BFb0054319?noAccess=true#auth-Gilles-Brassard), [Peter HØyer](https://link.springer.com/chapter/10.1007/BFb0054319?noAccess=true#auth-Peter-H_yer) & [Alain Tapp](https://link.springer.com/chapter/10.1007/BFb0054319?noAccess=true#auth-Alain-Tapp) namely [Quantum cryptanalysis of hash and claw-free functions](https://link.springer.com/chapter/10.1007/BFb0054319?noAccess=true). Also, [Analysis of several algorithms for the collision problem](https://blog.cr.yp.to/20171017-collisions.html) by Bernstein will be used to discuss the limitations of the BHT algorithm.

### Are you proposing to write this new content? (y/n)

Yes, I have studied applications of Grover's algorithm in quantum cryptanalysis in depth during a course called "Quantum Symmetric-key cryptanalysis" in my BTech at [IIT Bhilai](https://www.iitbhilai.ac.in/).

**Comment by frankharkins** [comment]
Hi, sorry for the slow response. Thanks for offering to contribute to the textbook, unfortunately we're not accepting new content at this time. We still think community-driven content is really valuable, and we're working to create an appropriate place for it within the textbook platform. Until then, I highly encourage you to continue to share your work through other channels. 

I'm going to close this issue, but please let me know if I can support or help in any way.
