### ISSUE TITLE
[4.1.4] Bug in Verifier code

### ISSUE THREAD

**Issue by woodsp-ibm** [qiskit-community/qiskit-textbook#1423]
### Describe the bug

https://qiskit.org/textbook/ch-applications/satisfiability-grover.html

Copying the code out to a file, and creating a dimacs file from the SAT given there fails as follows

```
    lit_eval = guess[int(literal)-1]
ValueError: invalid literal for int() with base 10: ''
```

See here where it was reported https://stackoverflow.com/questions/72190973/boolean-n-sat-compatibility-issue

### To Reproduce

Copying the code out to a file, and creating a dimacs file from the SAT given, there fails as follows.

It seems that the trailing `\n` causes an issue in the verifier (maybe the example DIMACS it was used on the \n on the last line was removed - I did not check the file that is checked into examples here).

This is the line in question that splits the DIMACS and will end up with an empty last entry/line which it further then go on to act upon

>         for line in self.dimacs.split('\n'):

I changed it to strip the last character from the file

>         for line in self.dimacs[:-1].split('\n'):

which works around the problem. One can also skip line if its empty in the loop which might be a bit more robust.

### Expected behavior

Should be more robust to the user creating their own DIMACS file from the sample there and using that.

### Version info

Latest qiskit version - I was using all development branches from repos.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
