### ISSUE TITLE
[3.4] An image of the Japanese version is wrong.

### ISSUE THREAD

**Issue by taketakeyyy** [qiskit-community/qiskit-textbook#1424]
### Describe the issue

An image of Simon's algorithm in the Japanese version does not match the description.

Corresponding page: 
https://qiskit.org/textbook/ja/ch-algorithms/simon.html#%E9%87%8F%E5%AD%90%E7%9A%84%E3%81%AA%E8%A7%A3%E6%B3%95

### Describe what you expect to see

The image of the Japanese version is below.

https://github.com/qiskit-community/qiskit-textbook/raw/55d1ba6d2bb5ef38b1ee0831eedb65224c8f136d/i18n/locales/ja/ch-algorithms/images/simon_steps.jpeg

The image of the English version is below.

https://qiskit.org/textbook/ch-algorithms/images/simon_steps.png

<br>

The Japanese version of the image only has steps up to step 5, but this makes the description, which has up to step 6, not make sense.

If you replace it with the English version of the image, the meaning will make sense.

Best regards.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
