### ISSUE TITLE
New Section on Simulation of the 1D Schrodinger Equation

### ISSUE THREAD

**Issue by Mostafa-Atallah2020** [qiskit-community/qiskit-textbook#1434]
### What should the reader gain from this new content?

By reading this section the reader should be able to simulate the one-dimensional Schrodinger equation for any position-dependent potential on quantum computers using a few numbers of qubits (six qubits or more). Also, he will be able to calculate the ground state energy eigenvalue for the quantum system under investigation. The results can be extended to three dimensions easily. I will solve, in particular, the one-dimensional quantum harmonic oscillator problem. Then, I use the Variational Quantum Eigensolver to obtain the ground state energy for the quantum harmonic oscillator. 

### Where do you expect this new content to fit in with the current content?

Inside of section 4.1 or inside a new chapter for quantum simulations. 

### What material should this new content be based on?

References [1-3] for simulation of wavefunctions and [4] for energies. 

1. Giuliano Benenti and Giuliano Strini. Quantum simulation of the single-particle Schrodinger equation. arXiv:Quantum Physics, 2007.

2. Afonso Miguel Fernandes Rodrigues. Validation of quantum simulations: assessing effciency and reliability in experimental implementations, 2018.

3. Mohamed Abouelela and Tarek Sayed. Quantum simulation of the schrodinger equation using ibm’s quantum computers, 2021.

4. Raffaele Miceli and Michael McGuigan. Quantum computation and visualization of hamiltonians using discrete quantum mechanics and ibm qiskit. 2018 New York Scientifc Data Summit (NYSDS), Aug 2018.

### Are you proposing to write this new content? (y/n)

Yes, I have written the code already.

**Comment by frankharkins** [comment]
Hi, sorry for the slow response. Unfortunately we're not accepting new content at the moment, but I hope you continue to work on this and share via other channels.

I'm going to close this issue, but let me know if I can support in any way.
