### ISSUE TITLE
3.1.5

### ISSUE THREAD

**Issue by InfamousPlatypus** [qiskit-community/qiskit-textbook#1440]
### Is your feature request related to a problem? Please describe.

3.1.5 has an unclear section. It says
"When we measure the qubit, we collapse its state and destroy a lot of the information. Since all measurement does is destroy information, we can in theory always measure last and lose no computational advantage. In reality, measuring early offers many practical advantages."

This feels like a tautology. As I think about it it seems to be correct, but it doesn't seem clearly explained.

### Describe the solution you'd like

Rewording would be nice.

### Describe alternatives you've considered

None

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
