### ISSUE TITLE
2.2.1

### ISSUE THREAD

**Issue by InfamousPlatypus** [qiskit-community/qiskit-textbook#1441]
### Describe the issue

Textbook calls a 1D-Vector 4D.
![Uploading 4d1dvec.png…]()

### Describe what you expect to see

I expected to see 1D vector. It should have four elements, not four dimentions.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
