### ISSUE TITLE
[4.1.3] analytical formulas of the Japanese version is wrong

### ISSUE THREAD

**Issue by yoshioka1128** [qiskit-community/qiskit-textbook#1449]
### Describe the issue

In the last equations in section [5.2](https://qiskit.org/textbook/ja/ch-applications/qaoa.html#5.2-最適な試行状態のパラメーター-), the right hand side of f<sub>A</sub>, f<sub>B</sub>, and F<sub>1</sub> are incorrect.
Results that rely on this are also incorrect.

The modified formulas are as follows:
<img width="524" alt="eqfAfB" src="https://user-images.githubusercontent.com/88071178/176557528-6568ad2f-8800-42ba-9c82-1cba5198a911.png">
<img width="545" alt="eqF1" src="https://user-images.githubusercontent.com/88071178/176557652-a299ebb2-4a4f-4d32-9bb0-189dc757d6f2.png">

These analytical expressions were verified by two independent calculations, a numerical state vector calculation and a quantum circuit calculation. 

### Describe what you expect to see

The modification improves the calculation results.
The maximal expectation value obtained by grid search is improved from 3.431 to 3.927.
The simulated mean value M1_sampled is improved from 3.29 to 3.93.

**Comment by yoshioka1128** [comment]
Here are the results of the modifications made to the figure of the probability vs cost.
before the correction
<img width="521" alt="before_probcost" src="https://user-images.githubusercontent.com/88071178/176470943-a376ce92-84b9-4443-8f03-5c816958a9a9.png">

after the correction
<img width="521" alt="after_probcost" src="https://user-images.githubusercontent.com/88071178/176471062-3abfb98b-451f-48e7-94d1-6c96aee6319b.png">

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
