### ISSUE TITLE
[4.2.4] Travelling Salesman Problem with QPE: Error in the Hamiltonian Cycles

### ISSUE THREAD

**Issue by nquetschlich** [qiskit-community/qiskit-textbook#1451]
### Describe the bug

https://qiskit.org/textbook/ch-paper-implementations/tsp.html#general_strategy

At the end of the "General Strategy" Section, all three Hamiltonian cycles are listed as:
Sequence path | Eigenstates
-- | --
1−2−3−4 |\|11000110 ⟩
1−4−2−3 |\|10001101 ⟩
1−3−2−4 |\|11001001 ⟩

I think that the last two sequences describe the same Hamiltonian cycle, because a Hamiltonian Cycles ends at the starting node. As a consequence, cycle three is equal to cycle two in reversed order.

I suggest to substitute cycle three with the sequence 1-2-4-3 and its eigenvalue |10000111 ⟩.

### To Reproduce

The error becomes clear when drawing the cycles as shown in the screenshot provided under "Expected behavior". 

### Expected behavior

![image](https://user-images.githubusercontent.com/23012802/176662431-d729b7d1-9fc3-4b5d-9176-7a03cd303ded.png)

As one can see, the Hamiltonian cycles two and three are equivalent. If cycle 3 is substituted as suggested, the resulting three cycles would be: 
![image](https://user-images.githubusercontent.com/23012802/176662672-e4738062-d641-4dc0-b420-5648ec4264e0.png)

### Version info

No coding necessary.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
