### ISSUE TITLE
[5.3] Randomized Benchmarking

### ISSUE THREAD

**Issue by mkselvan** [qiskit-community/qiskit-textbook#1456]
### Describe the issue

https://qiskit.org/textbook/ch-quantum-hardware/randomized-benchmarking.html#

I think, there is typo in the section 5.3 Randomized Benchmarking. 

In the subsection "Intuition behind RB (5.3.3)", in the equation defining twirl, "equal to ($=$)" symbol is missing and the summation index must be $U \in G$ not $u \in G$. 

### Describe what you expect to see

I think, it should be  $$W_G (\bar{\Lambda}) = \dfrac{1}{\vert G \vert} \sum_{U \in G} U^{\dagger} \circ \Lambda \circ U$$ instead of $$W_G (\bar{\Lambda}) \dfrac{1}{\vert G \vert} \sum_{u \in G} U^{\dagger} \circ \Lambda \circ U$$

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
