### ISSUE TITLE
[Query] qiskit_textbook.tools.array_to_latex vs qiskit.visualization.array_to_latex

### ISSUE THREAD

**Issue by RSwarnkar** [qiskit-community/qiskit-textbook#1465]
### Describe the problem

As `qiskit` beginner, wanted to know just for my understanding why do we have two similar methods in `qiskit` platform: 

`qiskit_textbook.tools.array_to_latex` vs `qiskit.visualization.array_to_latex`? 

### Describe the expected solution

Checking difference between the similar methods in different packages from `qiskit` api offering

**Comment by frankharkins** [comment]
Originally, we created `qiskit_textbook.tools.array_to_latex` as a tool specifically for the textbook to help people read quantum states and unitary matrices. After a while this was moved to qiskit terra and became `qiskit.visualization.array_to_latex`. Essentially, `qiskit_textbook.tools.array_to_latex` is the old function and should be replaced with `qiskit.visualization.array_to_latex`.
