### ISSUE TITLE
[3.11 Quantum Teleportation] Chapter uses Ignis (unmaintained since July 2022)

### ISSUE THREAD

**Issue by 1ucian0** [qiskit-community/qiskit-textbook#1470]
The code example in https://qiskit.org/textbook/ch-algorithms/teleportation.html uses `qiskit.ignis`, which is unmaintained since July 2022 after being deprecated in Dec 2021.

```
from qiskit.ignis.verification import marginal_counts
```

I think `qiskit.ignis.verification.marginal_counts` was replaced by [`qiskit.result.marginal_counts`](https://qiskit.org/documentation/stubs/qiskit.result.marginal_counts.html). If so, this should be an easy fix and a `good first issue`. If not the case, please remove the label.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
