### ISSUE TITLE
[5.2 Measurement Error Mitigation] Chapter uses Ignis (unmaintained since July 2022)

### ISSUE THREAD

**Issue by 1ucian0** [qiskit-community/qiskit-textbook#1471]
The code example in https://qiskit.org/textbook/ch-quantum-hardware/measurement-error-mitigation.html uses `qiskit.ignis`, which is unmaintained since July 2022 after being deprecated in Dec 2021.

```python
from qiskit.ignis.mitigation.measurement import complete_meas_cal, CompleteMeasFitter
```

I think `qiskit.ignis.mitigation` was replaced by [qiskit.utils.mitigation](https://qiskit.org/documentation/apidoc/utils_mitigation.html). If so, this should be an easy fix and a `good first issue`. If not the case, please remove the label.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
