### ISSUE TITLE
[5.3 Randomized Benchmarking] Chapter uses Ignis (unmaintained since July 2022)

### ISSUE THREAD

**Issue by 1ucian0** [qiskit-community/qiskit-textbook#1474]
The code example in https://qiskit.org/textbook/ch-quantum-hardware/randomized-benchmarking.html uses `qiskit.ignis`, which is unmaintained since July 2022 after being deprecated in Dec 2021.

```python
# Import the RB Functions
import qiskit.ignis.verification.randomized_benchmarking as rb
```

I think `qiskit.ignis.verification.randomized_benchmarking` was replaced by [qiskit_experiments.library.randomized_benchmarking	](https://qiskit.org/documentation/experiments/apidocs/mod_randomized_benchmarking.html). If so, this should be an easy fix and a `good first issue`. If not the case, please remove the label.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
