### ISSUE TITLE
[Lab 6. Grover's search with an unknown number of solutions] Lab uses Ignis (unmaintained since July 2022)

### ISSUE THREAD

**Issue by 1ucian0** [qiskit-community/qiskit-textbook#1477]
The code example in https://qiskit.org/textbook/ch-labs/Lab06_Grover_search_with_an_unknown_number_of_solutions.html uses `qiskit.ignis`, which is unmaintained since July 2022 after being deprecated in Dec 2021.

```python
from qiskit.ignis.mitigation.measurement import *
```

I think `qiskit.ignis.mitigation` was replaced by [qiskit.utils.mitigation](https://qiskit.org/documentation/apidoc/utils_mitigation.html). If so, this should be an easy fix and a `good first issue`. If not the case, please remove the label.

**Comment by Arifkurdi** [comment]
i would like to jump on this man
can I?

**Comment by divshacker** [comment]
Sure feel free

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
