### ISSUE TITLE
[Textbook beta - Describing quantum computers - Amplitudes] amplitude arrow in the incorrect direction

### ISSUE THREAD

**Issue by husayngokal** [qiskit-community/qiskit-textbook#1481]
### Describe the issue

According to the amplitude addition widget in "What is quantum - Beyond probabilities", I expect a phase of 270 Degrees to look downwards, not towards the left like it is in the chapter. Or maybe it's the other way around? If you set the second Qubit to have a magnitude of 0 and an arbitrary phase, you can reproduce this error for yourself.

### Describe what you expect to see

Fix the arrow to point towards the correct direction.

**Comment by frankharkins** [comment]
Hi @husayngokal, am I looking at the right thing? If so, I can't reproduce this. Do you have screenshots?

![Screenshot 2022-09-05 at 17 55 04](https://user-images.githubusercontent.com/36071638/188492117-e469b2ee-e52f-4a77-8825-6d782bb2467d.png)

Also, for future reference, you can make issues for the textbook beta here: https://github.com/Qiskit/platypus/issues

**Comment by husayngokal** [comment]
Sorry if I made myself unclear. I'm talking about this:

<img width="383" alt="Phase Inconsistency" src="https://user-images.githubusercontent.com/92259277/188492709-89958447-044b-4c30-9e56-851180f053f3.png">

Compared with this:

<img width="695" alt="Inconsistent Phase (Widget)" src="https://user-images.githubusercontent.com/92259277/188493072-4af17595-4e8c-46d3-b8a9-5f4b023b7b24.png">

You can clearly see that something is wrong here. Both have the same phase, yet the arrows are pointing in different directions.

I took the first image from "Describing quantum computers - Amplitudes", and the second image from the widget at "What is quantum - Beyond probabilities".

**Comment by frankharkins** [comment]
Ohh I see, thanks
