### ISSUE TITLE
[Textbook beta - What is quantum - Beyond probabilities] amplitude addition widget doesn't round phase properly

### ISSUE THREAD

**Issue by husayngokal** [qiskit-community/qiskit-textbook#1482]
### Describe the issue

I've noticed that when experimenting with single-qubit phases (regardless of the magnitude), sometimes the final result isn't rounded properly. I've attached a screenshot showing what I mean.

![Amplitude Addition Widget Rounding Error](https://user-images.githubusercontent.com/92259277/188320504-0b8f22b3-3ac6-4473-8c6e-829d4b1b5362.png)

### Describe what you expect to see

Fix the final result not rounding in the amplitude addition widget.

**Comment by frankharkins** [comment]
Thanks for making this issue, I've moved it here: https://github.com/Qiskit/platypus/issues/1523
