### ISSUE TITLE
[Linear Algebra-8.1] A mistake statement about Hilbert spaces needed to be fixed

### ISSUE THREAD

**Issue by ohadlev77** [qiskit-community/qiskit-textbook#1490]
### Describe the issue

In the [linear algebra appendix chapter](https://qiskit.org/textbook/ch-appendix/linear_algebra.html#Hilbert-Spaces,-Orthonormality,-and-the-Inner-Product) (8.1) the following claim appears:

> The surface of this sphere, along with the inner product between qubit state vectors, is a valid Hilbert space.

To my knowledge, the surface of the Bloch sphere is not a Hilbert space (one can easily show that it is not a vector space.. By scaling any pure quantum statevector we can get vectors pointing outside of the sphere, for example).

### Describe what you expect to see

There are 2 options:

1. We can provide an explanation about what the surface of the Bloch sphere really is regarding to Hilbert spaces - i.e a projective Hilbert space - but I think that might be too complicated in the context of this chapter.
2. Removing this specific paragraph:

> Let's consider the Bloch sphere:
> 
> --BLOCH SPHERE PICTURE--
> 
> The surface of this sphere, along with the inner product between qubit state vectors, is a valid Hilbert space. In addition, the normalization condition holds true, as the radius of the Bloch sphere is 1, and thus the length squared of each vector must also equal 1.

**Comment by MonitSharma** [comment]
A Bloch sphere is the geometrical representation of an arbitrary two-dimensional Hilbert space.  From what I think a 2D Hilbert space and a Bloch sphere are equivalent.   For a two-dimensional Hilbert space, the space of all such states is the complex projective line in CP^1. This is the Bloch sphere, which can be mapped to the Riemann sphere. So, I agree with this answer on [Quantum Stack Exchange](https://quantumcomputing.stackexchange.com/questions/27191/how-is-the-surface-of-a-bloch-sphere-a-hilbert-space), it's rather a projective Hilbert space and not a Hilbert space.
