### ISSUE TITLE
[1] Inaccurate calculation in qiskit textbook (beta) cracking 20 and 30 digit PIN

### ISSUE THREAD

**Issue by maheboobp** [qiskit-community/qiskit-textbook#1500]
### Describe the issue

In the first section "why quantum computing?" , calculation for cracking a 20 digit PIN is mentioned as 5,000,000,000 seconds.
That seems incorrect and it should be 10, 000,000, 000 seconds!

20 digit PIN has 100,000,000,000,000,000,000 combinations. On average we try half of that which will be 50,000,000,000,000,000,000.
As computer in question can do 5,000,000,000 calculations per second, if we divide, answer will be 10,000,000,000 seconds!

### Describe what you expect to see

We would expect this computer using this algorithm to take roughly **10**,000,000,000 seconds (**~300** years) to find a 20-digit PIN. Adding another 10 digits increases this to around **3,000**,000,000,000 years (**~200x** the age of the universe)

**Comment by maheboobp** [comment]
![Bug](https://user-images.githubusercontent.com/115867513/195978474-8581e091-85f2-4a2e-b80d-2a858664066b.jpg)

**Comment by divshacker** [comment]
Nice catch. 
Feel free to open a PR.

**Comment by frankharkins** [comment]
Just FYI, the notebook for this page is in https://github.com/Qiskit/platypus, any fixes will need a PR there.

**Comment by maheboobp** [comment]
Thanks Frank and Divyanshu,
I don't see an option to create a branch. shall i creare fork and then PR?

Maheboob

**Comment by frankharkins** [comment]
Fixed via https://github.com/Qiskit/platypus/pull/1696
