### ISSUE TITLE
Deutsch-Josza algorithm.  dj_oracle() is broken

### ISSUE THREAD

**Issue by fyellin** [qiskit-community/qiskit-textbook#1504]
### Describe the bug

The function dj_oracle() in this section is supposed to be an algorithm that generates the two constant oracles, and 2^n different balanced oracles.  In fact, the code generates only 2 different balanced oracles.  The generator is nothing but a parity checker that returns 0 on even parity and 1 on odd parity, or vice versa.  If you look at the 2 tables at the start of Section 3, the only difference between no X gates and one X gate is that the left and right sides have swapped.  Add one more X gate, and they swap again.

There is an easy way of getting 2 * (2^n - 1) different balanced oracle.  A small fraction of the choose(2^n, 2^(n-1)) possible balanced algorithms, but a lot better than what we have now.

Either set the "result" bit to 0 or 1 at random.  Pick a random non-empty subset of the input bits, and only CNOT those bits into the result bit.  (Net result is you're taking the parity of a subset of the bits.). Not great, but better than what's there.

### To Reproduce

Problem already shown in text book.

### Expected behavior

Expect more than  possible functions.2 

### Version info

Not relevant

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
