### ISSUE TITLE
[What is Quantum?] off-by-one in coin toss simulator

### ISSUE THREAD

**Issue by RahulGopan0** [qiskit-community/qiskit-textbook#1512]
### Describe the issue

While tossing the coin with the simulator, the initial no: of coin/s is set to 0, which is obscured, and the simulator goes on to toss '0' coin/s and still gives a result, which in reality should not be the case. This is the [link](https://qiskit.org/textbook/what-is-quantum.html).

### Describe what you expect to see

It would be better if the initial no: of coin/s is set to 1 rather than 0. This should also automatically solve the issue of running the simulator with 0 coin/s.

Hoping to see the issue fix.

**Comment by 1ucian0** [comment]
There seems to be an off-by-one in the coin toss simulator in https://qiskit.org/textbook/what-is-quantum.html#Experiment-#1:-Single-Coin-Toss

![Screenshot 2022-11-13 at 18 17 15](https://user-images.githubusercontent.com/766693/201534957-f5e5cc39-3dd5-4120-9763-9de785927bde.png)

When the screen loads, it's in 0, which actually means 1. if you put the dial into 1, it simulates twice.

Tagging as a `good first issue`.

**Comment by RahulGopan0** [comment]
>
