### ISSUE TITLE
[4.1.2] Equations are rendered incorrectly

### ISSUE THREAD

**Issue by SooluThomas** [qiskit-community/qiskit-textbook#1521]
### Describe the issue

The equations in chapter 4.1.2 are rendered incorrectly https://qiskit.org/textbook/ch-applications/vqe-molecules.html#Mathematical-Background

### Describe what you expect to see

Properly rendered equation

**Comment by alan23273850** [comment]
Maybe you need to clearly indicate which equations are rendered incorrectly!

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
