### ISSUE TITLE
6.3 Introduction to Transmon Physics

### ISSUE THREAD

**Issue by dryicecube** [qiskit-community/qiskit-textbook#1527]
### Describe the issue

Section 6: Mentions the creation and annihilation operators, however, in the example $σ^+|0⟩=|1⟩$ and $σ^+|1⟩=|0⟩$.This is incorrect. 

### Describe what you expect to see

Either one of two should be changed. 
I prefer that we make it e $σ^+|0⟩=|1⟩$ and $σ^-|1⟩=|0⟩$

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
