### ISSUE TITLE
[3.8] Grover's algorithm - 2. Example: 2 Qubits

### ISSUE THREAD

**Issue by alan23273850** [qiskit-community/qiskit-textbook#1542]
### Describe the issue

The circuit implementation of $U_0$ is incorrect, since $(Z \otimes Z)|11\rangle = Z|1\rangle\otimes Z|1\rangle = -|1\rangle\otimes -|1\rangle = |1\rangle\otimes |1\rangle = |11\rangle$ which remains the same even after the two qubits are swapped. This circuit fails to flip the sign of |11⟩.

### Describe what you expect to see

The correct implementation!

**Comment by themathqueen** [comment]
You are right, the example is incorrect. It is also badly written.
The third example looks far clearer in comparison.

You can assign me to fix this, unless you want to fix it.

**Comment by alan23273850** [comment]
@themathqueen Thanks, I don't know how to fix it so please go ahead!

**Comment by themathqueen** [comment]
Cool! @alan23273850, I drafted something up (brief notes to add to section 1 in the textbook and the fixed example). Let me know if something is unclear or if I should change anything else: [grover-qiskit-notes.pdf](https://github.com/themathqueen/grover/blob/main/grover-qiskit-notes.pdf).

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
