### ISSUE TITLE
[Chapter-5.5] Quantum Hardware / The Density Matrix & Mixed States

### ISSUE THREAD

**Issue by caitaozhan** [qiskit-community/qiskit-textbook#1544]
### Describe the issue

In Chapter 5 Investigating Quantum Hardware Using Quantum Circuits, Section 5.5 The Density Matrix & Mixed States, and Subsection 2.1, the following sentence has an error (bold text).

> The remaining 20% of the times, the pulse applied to rotate the state is either too short or too long by π/6 radians about the **x-axis**.

### Describe what you expect to see

I think it should be y-axis, instead of x-axis.

> The remaining 20% of the times, the pulse applied to rotate the state is either too short or too long by π/6 radians about the **y-axis**

**Comment by divshacker** [comment]
Do you have anything to support your statement?

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
