### ISSUE TITLE
2.3 Phase Kickback

### ISSUE THREAD

**Issue by FelixXu35** [qiskit-community/qiskit-textbook#1558]
### Describe the bug

For `IN[6]`, `IN[7]`, `IN[8]`, `IN[12]` and `IN[13]`, maybe `qc.save_statevector` and `qc.save_unitary` should be put after `aer.get_backend`. There will be errors if I run those blocks individually. There will not if I run in a sequence, because `IN[3]` called the simulator properly.

### To Reproduce

Run `IN[1]` and then run one block of `IN[6]`, `IN[7]`, `IN[8]`, `IN[12]` and `IN[13]`.

### Expected behavior

In each code block, I was wondering if it is possible to put `qc.save_statevector` and `qc.save_unitary` after `aer.get_backend`.

### Version info

{'qiskit-terra': '0.23.2', 'qiskit-aer': '0.11.2', 'qiskit-ignis': None, 'qiskit-ibmq-provider': '0.20.1', 'qiskit': '0.41.1', 'qiskit-nature': None, 'qiskit-finance': None, 'qiskit-optimization': None, 'qiskit-machine-learning': None}

### Screenshots

<img width="812" alt="Screenshot 2023-03-07 at 10 50 10" src="https://user-images.githubusercontent.com/61252303/223401338-1c4e7606-6079-4ed2-adbd-d5169f3aa4fd.png">

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
