### ISSUE TITLE
[4.2.1] Code and example for Special Hadamard Test do not match

### ISSUE THREAD

**Issue by abhamra** [qiskit-community/qiskit-textbook#1560]
### Is your feature request related to a problem? Please describe.

Code to reference: https://github.com/qiskit-community/qiskit-textbook/blob/main/content/ch-paper-implementations/vqls.ipynb

The problem I am bringing up is related to the special_had_test method. When the method is brought up for the first time, note that the for loop iterates through gate_type and compares gate_type[ty] to an _**integer.**_ When we look at the input example below the function definition, gate_type is given as a _**list of lists**_, implying that gate_test[ty] is equal to a list, not an integer.
![Screenshot 2023-03-12 212927](https://user-images.githubusercontent.com/33864884/224733579-53fe4c5a-857c-4f59-a044-46ec04e9ae43.png)

When we then go to the cost function definition further on in the VQLS textbook article, there is this very interesting (and to me, not required) formulation which uses extra and a for loop to selectively pick inputs for special_had_test. 
![image](https://user-images.githubusercontent.com/33864884/224736735-807bd545-c71e-463d-b1d3-e4ec499c5b04.png)

I am not sure why this formulation (of the loop and if-else) is used instead of correctly passing in gate_type as a whole to special_had_test and modifying the function to use a list of lists.

### Describe the solution you'd like

The ideal solution I'd like is to implement the special_had_test code so that it functions with a list of lists. On my own personal device, I have modified it as such (please ignore the comments):
![image](https://user-images.githubusercontent.com/33864884/224745223-ee0933fa-f5c1-4c90-b45d-2462f0a39f59.png)

This solution iterates through the list of lists correctly, and will place the CZ at the correct index with this iteration. An example circuit is shown below for the example given in the article: A = 0.55III + 0.45IIZ:

![image](https://user-images.githubusercontent.com/33864884/224745563-dfdd3de3-8ecf-4377-9b6f-784bfc7914a9.png)
I want to note the CZ that this circuit creates before the application of the control_b function.
![image](https://user-images.githubusercontent.com/33864884/224747744-e833b8ef-6787-49ff-8594-15a75b421d9b.png)

Also notice that in the official textbook article (shown above), there is no application of the CZ gate, when I believe there should be.

### Describe alternatives you've considered

I don't currently have any alternative solutions, but I am looking into the Pennylane article as well for comparisons.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
