### ISSUE TITLE
[Quantum Counting]

### ISSUE THREAD

**Issue by HannesGitH** [qiskit-community/qiskit-textbook#1578]
### Describe the bug

the $|s'\rangle$ isnt rendered on the [website](https://learn.qiskit.org/course/ch-algorithms/quantum-counting) (section 1.2, first row)

but it is here on [github](https://github.com/qiskit-community/qiskit-textbook/blob/main/content/ch-algorithms/quantum-counting.ipynb)

### To Reproduce

go to https://learn.qiskit.org/course/ch-algorithms/quantum-counting#closer_look

### Expected behavior

rendered mathjax like $|s'\rangle$, but instead shows as plaintext

### Version info

latest published

### For website problems please state device / OS / browser.

firefox 112.0.1; m1 pro mac

### Screenshots

![Screenshot-2023-04-25-at-14 01 56](https://user-images.githubusercontent.com/33062605/234270403-dc6e4a63-382f-4e2f-b475-f08ac45f9d23.jpg)

**Comment by divshacker** [comment]
Hey @HannesGitH, 
This issue is related to new textbook as you mentioned it in the issue. Please re-open this issue in [github.com/Qiskit/textbook](https://github.com/Qiskit/textbook)
