### ISSUE TITLE
Pinpoint the page number and chapter in references when possible

### ISSUE THREAD

**Issue by HuangJunye** [qiskit-community/qiskit-textbook#227]
## Describe the Issue
The textbook often cite Nielson & Chuang without specifying the page and chapter for the specific topic that is cited for. For example, on https://qiskit.org/textbook/ch-states/states-many-qubits.html, Nielson & Chuang is referred to the reader as further reading for tensor product, but no page number of chapter name is provided. It can be difficult to find the content in Nielson & Chuang as it is a thick textbook.

## Expected Solution
Pinpoint the page number and chapter in references when possible

**Comment by exAClior** [comment]
Hello, can I take on this? I am currently going through many chapters in the textbook, I would probably go find the referred points in the book either way. And if I see other books referenced, I could also cite the page number?

**Comment by charmerDark** [comment]
I could also help in this process. I am also working my way through the book right now. And considering the scale of the task, I suppose it will take quite a few contributors too.

**Comment by exAClior** [comment]
> I could also help in this process. I am also working my way through the book right now. And considering the scale of the task, I suppose it will take quite a few contributors too.

Assuming we will be working together on this, I guess we should fix the version of  Chuang we are referring to? I have the 10th-anniversary version. And will likely be referring to chapters instead of exact chapter numbers just in case others have different versions?

**Comment by charmerDark** [comment]
I'm also working with the 10th Anniversary edition. I guess it would be better to mention chapter numbers as well.
