### ISSUE TITLE
Provide freely accessible references when possible

### ISSUE THREAD

**Issue by HuangJunye** [qiskit-community/qiskit-textbook#228]
## Describe the Issue
Related to issue #227. For the spirit of open source textbook, I would like to suggest to provide freely accessible references (e.g. Wikipedia pages, arXiv articles) instead of (or in addition to) content that are behind the paid wall or require purchasing a physical book (like Nielson & Chuang). 

## Expected Solution
Provide freely accessible references instead of (or in addition to) existing references whenever possible.

**Comment by aasfaw** [comment]
Hi @HuangJunye -- great idea! can you open a PR with pages where you think such resources are applicable?

**Comment by HuangJunye** [comment]
Sure, I will do that.

**Comment by charmerDark** [comment]
I've been recently going through some of these papers and have the links for a few of the papers that are freely available such as the quantum teleportation paper by Charles Bennet and the Quantum Key Distribution (BB84) by Bennet and Brassard and so on. Should I open a new issue for this or can I just continue here itself. Also would it be alright to provide them in the end as references or would it be better to incorporate them into the material?

**Comment by frankharkins** [comment]
@charmerDark sorry I missed this comment. Yes, please make a PR if you are still keen to.

**Comment by frankharkins** [comment]
I am going to close this issue as it is more of a guideline than a specific problem or task that can be achieved.
