### ISSUE TITLE
multi-language/translation support?

### ISSUE THREAD

**Issue by 1ucian0** [qiskit-community/qiskit-textbook#23]
I think it make sense to have a look to multi-language support. Start exploring tools to maintain translations and the like.

Something like https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/nbTranslate/README.html

**Comment by 1ucian0** [comment]
Other documentation in Qiskit seems to have some solutions! https://medium.com/qiskit/qiskit-in-my-language-is-qiskit-73d4626a99d3

**Comment by mtreinish** [comment]
Right, you can see there is an open issue for how to do translations for notebooks on the documentation repo. The best path forward IMO is to convert the notebook to something you can extract the strings to (either with a sphinx plugin, like nbsphinx, or as a script that calls nbconvert directly) and then use that as an input tohttps://github.com/Qiskit/qiskit/issues/573 The issue after that is to take the output from crowdin translations and use them with the notebooks. If nbTranslate works with .po files then that will work, or if you're using a sphinx plugin then that will just work with the existing translation hosting solution. We'll just need to start hosting a statically rendered version of the notebook using sphinx.
