### ISSUE TITLE
4.1.1hhl 4A the implementation of the simulating is soon deprecated

### ISSUE THREAD

**Issue by HTransistor** [qiskit-community/qiskit-textbook#308]
## Describe the Issue
In 4.1.1hhl 4A the implementation example soon deprecated.
![4 1 1hhl_4A_deprecation](https://user-images.githubusercontent.com/43704364/78181706-1e793400-7465-11ea-8f4a-da0e3f7f453f.png)

## Expected Solution
Use the classes as the warning suggests.

**Comment by frankharkins** [comment]
This was fixed in #450
