### ISSUE TITLE
4.1.1hhl 2D approximation wrong?

### ISSUE THREAD

**Issue by HTransistor** [qiskit-community/qiskit-textbook#312]
## Describe the Issue
On the wiki page to QPE it is discussed that the state |x> (|L> in qiskit textbook) is not changed when regarding approximation in contrast to the qiskit textbook.
![hhl_2D_eigenvalue_error_wiki](https://user-images.githubusercontent.com/43704364/78189335-1d9acf00-7472-11ea-85bc-1d6ede0af669.png)

![hhl_2D_eigenvalue_error](https://user-images.githubusercontent.com/43704364/78188844-39ea3c00-7471-11ea-8ca2-1fb0e991d7d9.png)
In the same way the amplitude is different.

## Expected Solution
I would suggest when relabeling using lambda = lambda_error + delta, where lambda_error is the best bit approximation (so |L> stays).

**Comment by zyzhang1992** [comment]
Please assign this to me

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
