### ISSUE TITLE
Additional algorithms / demos proposal

### ISSUE THREAD

**Issue by asakhnenko** [qiskit-community/qiskit-textbook#328]
Hi everyone.
I would like to propose possible additions to the book content:

**Quantum Machine Learning**
- [ ] Probability approximation with quantum algorithms
- [ ] Unsupervised methods (e.g. clustering)
_(methods that have the potential to outperform classical approaches)_

**Demos**
- [ ] Traveling salesman problem with quantum phase estimation

**Comment by frankharkins** [comment]
@asakhnenko these look like good suggestions! are you proposing you write them? Or are they suggestions for someone else?

**Comment by asakhnenko** [comment]
@frankharkins I would like to work on them if you think it fits the scope of the book.

**Comment by frankharkins** [comment]
Hi @asakhnenko, sorry for the late reply. I think the travelling salesman demo would be great, are you basing it on a paper? If so I would be interested to read it. I don't know much about QML though so I'll need to ask someone else about those chapters.

**Comment by pritamsinha2304** [comment]
@frankharkins Is anyone working on the traveling salesman problem ?

**Comment by pritamsinha2304** [comment]
@frankharkins Any comment on this one.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
