### ISSUE TITLE
[4.1.1] HHL doesn't give the right answer

### ISSUE THREAD

**Issue by yulunwang** [qiskit-community/qiskit-textbook#335]
## Describe the Issue
Hi I am using HHL function in Aqua. Here are two examples I tested:
![image](https://user-images.githubusercontent.com/37082255/79156429-7afb1e00-7d98-11ea-89ad-0d62f82b847a.png)
For the second example, HHL failed giving me correct answer.

It gives me [4,4] instead of  [-4 -4]

And also I tried these two cases:
![image](https://user-images.githubusercontent.com/37082255/79156486-9b2add00-7d98-11ea-932b-731b2d91efeb.png)
The second case here are much less accurate comparing to the first one. The codes are the same and borrowed from qiskit textbook
Thanks!

## Expected Solution
Produce correct results

**Comment by frankharkins** [comment]
@yulunwang, thanks for raising this issue. We are having a few issues with the HHL chapter and I'm looking into it.

**Comment by hykavitha** [comment]
@frankharkins : could you please assign this issue to me. I would like to take a look at it.

**Comment by zyzhang1992** [comment]
Looks like it has to do with the negative eigen values. In the case of [[-1/2, 0], [0, -1/2]], the eigenvalues are all negative and we need to set the eigs-negative parameter for the HHL module to true to get the correct answer. If that is set to be the default false, we will not get the correct answer.
In the other case of [[0, -1/2], [-1/2, 0]], there will be one positive and one negative eigenvalues and, as it is implemented now, there is no way to get the correct answer, neither with eigs-negative set to positive nor negative. The correct implementation of HHL doesn't have a way to handle this correctly.

**Comment by rht** [comment]
Fixed in https://github.com/Qiskit/qiskit-terra/pull/6971.

**Comment by divshacker** [comment]
As it is fixed in Qiskit/qiskit-terra/pull/6971, closing this for now. 
Please feel free to re-open if there's any problem.
