### ISSUE TITLE
A section on Oracles should be added

### ISSUE THREAD

**Issue by quantumjim** [qiskit-community/qiskit-textbook#338]
## Describe the Issue

1a
* The bit strings in are not expressed in the standard Qiskit order.
* The notation for strings in is strange.
* There is mention 
There is no single reference for what oracles are, how they are implemented, why they are used.

## Expected Solution

Write one!

In my course, I used  [some of my old lecture notes](https://github.com/quantumjim/Quantum-information-course-Basel/blob/master/extra/Oracle-Intro.pdf).

**Comment by frankharkins** [comment]
Have you seen PR#32? might be relevant. But I think a short explanation in DJ or BV is appropriate too.

**Comment by quantumjim** [comment]
I’ll do this, and look into how to incorporate PR 32.

**Comment by frankharkins** [comment]
closed via #439
