### ISSUE TITLE
Transpiling Quantum Circuits missing from index

### ISSUE THREAD

**Issue by starktech23** [qiskit-community/qiskit-textbook#36]
I couldn't find the index page on the repo so if admins can add to it here's the link: https://community.qiskit.org/textbook/ch-quantum-hardware/transpiling-quantum-circuits.html

**Comment by aasfaw** [comment]
Thanks @starktech23 -- we removed it from index to add more content to the notebook. How did you get to it without index?

**Comment by starktech23** [comment]
I found the Jupyter Notebook for this in the repo but no corresponding link on the index page, so I just did a Google search and found it, and also I think this link was one of the references on the Qiskit Advocates resources too.

**Comment by abhik-99** [comment]
@aasfaw , it would be very helpful if you guys could include a link to the circuit transpiler and show what is being done behind the scenes in the textbook

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
