### ISSUE TITLE
Dark Reading Mode

### ISSUE THREAD

**Issue by frankharkins** [qiskit-community/qiskit-textbook#377]
## Describe the Issue

Some readers would like to be able to enable a dark reading mode. 

## Expected Solution

Light mode should be default, and dark mode toggled through a button somewhere.

## Anything else we should know?

This should not be worked on until we have stablised the site's themeing in general.

**Comment by ArenaGrenade** [comment]
@frankharkins I can pick this issue once the site's themeing is completed?

**Comment by frankharkins** [comment]
@ArenaGrenade I would like to say yes, but we will soon be moving to a new version of Jupyter Book and I am not sure what that will mean for this functionality. I will keep you updated.

**Comment by ArenaGrenade** [comment]
@frankharkins As the upgrade is done shall I get to work on it?

**Comment by 3yakuya** [comment]
Not sure if this would justWork but we could use Jupyter Books' themes, and just have a ui switch switching those? Not entirely sure if Jupyter plays nicely with Latex in different themes.

**Comment by Aniruddha120** [comment]
@3yakuya previously I have tried to add dark mode through the developing the webpage. But , dont know why I cant understand the structure and seem too complicated. If we use Jupyter theme it will only be possible from our individual env, not from the main server(i guess so ,or maybe i am wrong..), what do you say?

**Comment by frankharkins** [comment]
We are investigating moving platforms, of which one possibility is the latest version of [Jupyter Book](https://jupyterbook.org/intro.html). Once we have successfully moved platforms, we can start investigating things like dark mode. Until then, please do not work on this issue as it's unlikely your work can be used.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
