### ISSUE TITLE
Add mathematical details for teleportation chapter

### ISSUE THREAD

**Issue by HuangJunye** [qiskit-community/qiskit-textbook#382]
## Describe the Issue

The chapter doesn't contain mathematical details for teleportation algorithm. It's hard to understand why Bob needs to do those operations in order to get Alice's state to teleport. (Step 4) Something like this would be more clear: https://en.wikipedia.org/wiki/Quantum_teleportation#Formal_presentation

## Expected Solution

Add mathematical details

**Comment by rochisha0** [comment]
I think this issue, can be closed now through PR #651 @frankharkins @HuangJunye

**Comment by frankharkins** [comment]
Yes, sorry I missed this.
