### ISSUE TITLE
Need to better emphasise motivations for quantum computing

### ISSUE THREAD

**Issue by frankharkins** [qiskit-community/qiskit-textbook#386]
## Describe the Issue

There is surprisingly little explaining the motivations of quantum computing early on in the textbook.

## Expected Solution

I think something that should be covered first is big-O-notation and why different algorithm run times are so important. I would then follow this with a short list of applications which are limited in classical computing but have potential to be solved with QC.

**Comment by quantumjim** [comment]
I can do this.
