### ISSUE TITLE
Misleading image

### ISSUE THREAD

**Issue by nonhermitian** [qiskit-community/qiskit-textbook#400]
In the below image, "classical bits" are being represented by a Bloch sphere with a non-classical statevector, i.e a statevector not at the poles.

![image](https://user-images.githubusercontent.com/1249193/82752823-c4bf2700-9d8e-11ea-94d5-604be8cca5ee.png)

**Comment by frankharkins** [comment]
@nonhermitian would something similar to this suffice?
![tele](https://user-images.githubusercontent.com/36071638/82877649-603ccd00-9f32-11ea-801b-11a9ab341d3a.png)

Bear in mind the image will be redrawn professionally.

**Comment by nonhermitian** [comment]
Yes, better.  Thanks

**Comment by JRussellHuffman** [comment]
Updated with new illustration style

![teleportation v2](https://user-images.githubusercontent.com/7633881/85886336-806ae080-b7ab-11ea-8771-55617791ee52.jpg)
