### ISSUE TITLE
The possiblity of some mistakes in Sec 2.5 

### ISSUE THREAD

**Issue by kifumi** [qiskit-community/qiskit-textbook#432]
## Describe the Issue
(1) " 𝑒^𝑖𝛼𝐴𝑍𝐵𝑍𝐶=𝑈" in text, but the circuit picture is using V.
(2) In the circuit picture of Toffoli, the last part of circuit is swapped in q1 and q2, but the text doesn't explain why it is swapped. 
(3) Text says "So far, we only have the power to do these arbitrary rotations around one axis. For a second axis, we simply do the 𝑅𝑧(𝜋/4) and 𝑅𝑥(𝜋/4) rotations in the opposite order." but the circuit order is same; HTHT.

## Expected Solution
(1) V in the the picture should be changed to U.
(2) I guess the connectivity of qubits is the cause of this. I think more explanation should be included. 
(3) The circuit might be changed to THTH.

**Comment by realistix30** [comment]
Hi, I'd like to make this as my first contribution.
I'm still new to python and Jupyter.

For (1), maybe it is okay to change it to  "𝑒^𝑖𝛼𝐴𝑍𝐵𝑍𝐶=**V**" so we don't need to change the picture.
Also for this sentence, "We can also make a controlled version of any single-qubit rotation,  **V**"
I think it is okay to change it to "V" since it is used for this section "3. Controlled Rotations"

**Comment by frankharkins** [comment]
@realistix30 that proposal sounds good to me! Let me know if you need any guidance.

**Comment by realistix30** [comment]
@frankharkins Thanks!
For (2) the expected solution is to add more explanation, I'm not sure what it means that "the connectivity of qubits cause of this". Why was it swapped? it wouldn't have mattered right? 
![Toffoli_Swapped](https://user-images.githubusercontent.com/65805697/85914083-bae88200-b86c-11ea-8829-873605139354.PNG)
These two will produce same output.
![Tofolli_q1q2](https://user-images.githubusercontent.com/65805697/85914304-000db380-b86f-11ea-9e38-003477348bd7.PNG)
For (3) Understood, It needs to be changed to THTH.

**Comment by kifumi** [comment]
@realistix30 Hi, as for (2), I thought it supposes the specific device that q0 is connected q2, but q0 is not connected to q1, so the circuit is swapped.  We need more explanation or change the circuit without swap.
Thank you for the good proposal for (1) and (3).

**Comment by realistix30** [comment]
Hi, For (2) I checked again the textbook and the example in Toffoli circuit is also shown in 2.1 Introduction.
I haven't check all the sections but maybe the are still other instances of this circuit, the fix should be also applied to other instances. Maybe It is possible to just add a footnote on the image to explain about the connection of the qubits in this device.
something like "Toffoli circuit: This circuit shows a device with 3 qubits q0, q1, q2. In these 3 qubits, q0 is connected to q2 but q0 is not connected to q1." What do you think?
