### ISSUE TITLE
Add "Quantum Coin Game" to the Games & Demos chapter

### ISSUE THREAD

**Issue by JanLahmann** [qiskit-community/qiskit-textbook#434]
## Describe the Issue
The Qiskit Community tutorials included a tutorial "How Quantum Power Helps to Win a Coin Game" based on David A. Meyer's "PQ Penny Flip Game": https://github.com/qiskit-community/qiskit-community-tutorials/blob/master/games/Quantum-Coin-Game.ipynb

This tutorial was used very successfully in several Quantum meetups in 1H2020. 
It illustrates the power of quantum superposition and interference.

## Expected Solution
We think the Quantum Coin Game would be a nice addition to the Qiskit Textbook and propose to update the above tutorial and add it to the textbook.

**Comment by divshacker** [comment]
I suppose it maybe fulfilled by #1282
