### ISSUE TITLE
Index required

### ISSUE THREAD

**Issue by quantumjim** [qiskit-community/qiskit-textbook#448]
## Describe the Issue

Textbooks usually include an index, which allows the reader to determine where in the book they can find certain topics. Just searching the text is not a good substitute for this.

## Expected Solution

Add keywords to each section, and use this to automatically create an index.

**Comment by Vismai-Khanderao** [comment]
I feel like this may be a good addition to the textbook backlog project

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
