### ISSUE TITLE
Add "GHZ Game" to Games & Demo Chapter

### ISSUE THREAD

**Issue by redisa** [qiskit-community/qiskit-textbook#459]
## Describe the Issue

Add a new game to the Games&Demo section which illustrates the power of Quantum Entanglement based on the GHZ state: https://github.com/JanLahmann/Fun-with-Quantum/blob/master/GHZ-Game.ipynb

## Expected Solution

The game could be a nice addition to the textbook. Therefore, it should be updated/adapted to the requirements and added to the games & demo.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
