### ISSUE TITLE
General fixes

### ISSUE THREAD

**Issue by zmohammad01** [qiskit-community/qiskit-textbook#475]
## Describe the Issue

1) Section 1.3 - piece is spelled wrong in paragraph 2

2) Section 1.3 the first section fails to compile in the safari browser

## Expected Solution

peice -> piece spelling fix

## Anything else we should know?

Was using Safari on the latest version of OSX; consistently kept getting a `waiting on kernal error`

**Comment by a-kapila** [comment]
Working on it.

**Comment by a-kapila** [comment]
I could not replicate your second issue in Safari on iPad or MacBook. This may be a local issue.
