### ISSUE TITLE
Un-captioned version code snippets at the end of most chapters.

### ISSUE THREAD

**Issue by ArenaGrenade** [qiskit-community/qiskit-textbook#482]
## Describe the Issue
The problem is in the many pages of the qiskit textbook. For example, [link to problematic page](https://qiskit.org/textbook/ch-prerequisites/qiskit.html)

The very last code snippet which essentially is printing the version of the qiskit distribution used in the guide has no caption describing the reason why it is being there at all.

## Expected Solution
It could be captioned off in some pages where it is necessary, while could be removed from other places.
Caption:

**The version of qiskit being used throughout the textbook: (You can find out the version of of qiskit you have by using the following command)**
```python
import qiskit
qiskit.__qiskit_version__
```
>{'qiskit-terra': '0.14.1',
'qiskit-aer': '0.5.1',
'qiskit-ignis': '0.3.0',
'qiskit-ibmq-provider': '0.7.1',
'qiskit-aqua': '0.7.1',
'qiskit': '0.19.2'}

## Anything else we should know?
Even if it has some use, it can either be made inline at the top with default run so that readers will always know what version they are working with. Or better still it can be a captioned code snippet that is attached to the top of each chapter instead of it being at the bottom. So, the users know which version is required to run the code present on that page. 

Is there some other use for it?

**Comment by nonhermitian** [comment]
It serves a purpose to let the user know what version the chapter was executed with. 

This would not be needed if changes to the textbook triggered automatic notebook evaluation in CI , eg 

execute_notebooks: force

In the config.yaml

However, currently there are still some calls to real devices in places that prevent this at the moment

**Comment by ArenaGrenade** [comment]
Automatic execution will indeed remove the code snippet itself. But temporarily, the caption would only maximize usability.

Well, what you are saying is understandable @nonhermitian. While reading the page, it just seems out of place. Giving it a caption will essentially provide it with some reason why it is being there and let users utilize it much better. 

If a complete beginner to programming uses the guide, then there is very little chance to know why this snippet exists and is bound to be overlooked. In the case that it is overlooked, the learners might run into some issues due to version mismatches.

To keep the textbook more versatile and understandable to the larger audience, it would be better to add a caption so it becomes usable even by complete beginner.

It is just a temporary cosmetic improvement.

**Comment by ArenaGrenade** [comment]
Furthermore it can also be moved to the top where the libraries are imported. So before running the code on local systems, users would know what version is used in the specific page. Else, users might run into version mismatch issue before even reading what is the version that is used in the page. Though having it at the end would not cause any issues on the page itself. But, on the other hand if users want to run the code locally, then version mismatch is a probable situation.

**Comment by frankharkins** [comment]
Closing as the code snippets are now explained in the environment setup guide.
