### ISSUE TITLE
Small drawing issue in geometric interpretation of Grover's algorithm

### ISSUE THREAD

**Issue by veenaiyuri** [qiskit-community/qiskit-textbook#483]
## Describe the Issue
The [drawing](https://qiskit.org/textbook/ch-algorithms/images/grover_step3.png) included in chapter [3.10](https://qiskit.org/textbook/ch-algorithms/grover.html), which represents the geometric interpretation of the first iteration of Grover's algorithm is possibly incorrect.  I believe the 2θ should start from |s> and not |s'>.
## Expected Solution
To ensure consistency in drawing style, the image in question can be retouched or, if replacing the entire set of images to a different style is acceptable, perhaps they can be replaced by [this image](https://user-images.githubusercontent.com/24409087/86313211-8eaf7580-bc5f-11ea-85eb-5c1987581701.png) I created before to explain diffusion.
## Anything else we should know?
FYI. All images used to explain Grover's algorithm are available in a different style here:
https://github.com/quantum-challenge/2019/blob/master/problems/week2/week2_en.ipynb

**Comment by frankharkins** [comment]
I have retouched the image in PR #484. Thanks for suggesting the new images, I will leave them for now as the images will be redrawn professionally in the style of the textbook soon.
