### ISSUE TITLE
Suggestion for a chapter dedicated to Bloch Sphere

### ISSUE THREAD

**Issue by ArenaGrenade** [qiskit-community/qiskit-textbook#490]
## Describe the Issue
All gates and the related explanation very much depends on bloch sphere visualization. Moreover, the bloch sphere is a very important visualization tool for anyone writing quantum programs.

## Expected Solution
A dedicated chapter to explaining the Bloch Sphere would be a good choice.

## Anything else we should know?
This could be placed right after the present [chapter](https://qiskit.org/textbook/ch-states/single-qubit-gates.html) on single qubit gates, explaining the representation of qubits and gate operations over them with focus on the bloch sphere alone.

**Comment by frankharkins** [comment]
Bloch spheres already feature quite heavily in the Single Qubit Gates Chapter, with the gates related to their rotations. Can you be more specific about what information you'd add please?

**Comment by diemilio** [comment]
I think with the introduction provided in the [Bloch Sphere](https://qiskit.org/textbook/ch-states/representing-qubit-states.html#3.-The-Bloch-Sphere-) section under ["1.3 Representing Qubit States"](https://qiskit.org/textbook/ch-states/representing-qubit-states.html), and the examples mentioned by Frank under ["Single Qubit Gates"](https://qiskit.org/textbook/ch-states/single-qubit-gates.html), there is probably enough information to explain how statevectors can be represented in the Bloch sphere. 

I think what might be missing is more advanced concepts, like representing mixed states via the Bloch vector. I know the scope for future chapters is still yet tbd, but I think it would be nice to include this under the section on density matrices. I will be more than happy to work on it too.

**Comment by ArenaGrenade** [comment]
@diemilio exactly.

**Comment by diemilio** [comment]
Now, if there is a common believe that readers are having a little bit of a hard time understanding the concept of global and relative phase, and how they show up (or don't) in the Bloch sphere, maybe a few lines can be added under [Bloch Sphere](https://qiskit.org/textbook/ch-states/representing-qubit-states.html#3.-The-Bloch-Sphere-) section to address that. I can also help with that. This has been brought up here #415 too

**Comment by frankharkins** [comment]
@ArenaGrenade do you feel the content covered in the new density matrices chapter is sufficient to close this issue?

**Comment by frankharkins** [comment]
I'm going to close this since the density matrix chapter is merged and there have been no updates on this for a while. Please reopen or make a new issue if you disagree with this decision.
