### ISSUE TITLE
No Linear Algebra in Prerequisites

### ISSUE THREAD

**Issue by rochisha0** [qiskit-community/qiskit-textbook#497]
## Describe the Issue
Basic Linear Algebra should be included in the Prerequisites section. Right now it only consists of Python basics but topics like matrix multiplication are equally important.

**Comment by rochisha0** [comment]
I also found this in the Quantum States and Qubits' Introduction Chapter- 
This chapter will be most effective for readers who are already familiar with vectors and matrices. Those who aren't familiar will likely be fine too, though it might be useful to consult our **Introduction to Linear Algebra for Quantum Computing** from time to time.This chapter will be most effective for readers who are already familiar with vectors and matrices. Those who aren't familiar will likely be fine too, though it might be useful to consult our Introduction to Linear Algebra for Quantum Computing from time to time.

This link leads nowhere.

**Comment by diemilio** [comment]
The [Linear Algebra](https://qiskit.org/textbook/ch-appendix/linear_algebra.html) section was moved from the Prerequisites Chapter to the Appendix. 

See #491 and #409 

Links do need to be updated.
