### ISSUE TITLE
Wrong circuit in Shor

### ISSUE THREAD

**Issue by ozlemsalehi** [qiskit-community/qiskit-textbook#503]
## Circuit should be replaced with the one in QPE notebok.

![image](https://user-images.githubusercontent.com/44723115/86973177-d3b23b00-c17c-11ea-91ca-fbb13319be91.png)

![image](https://user-images.githubusercontent.com/44723115/86973255-fa707180-c17c-11ea-80f5-130653b761fc.png)

**Comment by ozlemsalehi** [comment]
Furthermore, it would have been better if the controlled gates in QPE started with U^{2^0}.

**Comment by frankharkins** [comment]
I think this is correct, but the Shor circuit uses qiskit's qubit ordering, whereas the QPE circuit uses the other ordering.

**Comment by ozlemsalehi** [comment]
Yes, you are right. I edited my comment. Better to say not consistent. In QPE notebook, the other circuit is given and later on when doing the implementation it is mentioned that qiskit uses the reverse order. The circuit can be changed or at least it can be pointed out that the given circuit uses Qiskit order.

**Comment by frankharkins** [comment]
@ozlemsalehi I have added a comment on this in PR #511, please let me know if you think this is sufficient to close the issue.

**Comment by ozlemsalehi** [comment]
Yes, thanks. You can close the issue.
