### ISSUE TITLE
module `qutip` not installed (transmon physics chapter)

### ISSUE THREAD

**Issue by aasfaw** [qiskit-community/qiskit-textbook#510]
## Describe the Issue
The transmon physics chapter throws an error that the module `qutip` could not be found. Probably because `qutip` isn't installed in the kernels.

## Expected Solution
Adding `qutip` to the config yaml pre-installs.

## Anything else we should know?
Here is the chapter for reference.
https://qiskit.org/textbook/ch-quantum-hardware/transmon-physics.html

**Comment by frankharkins** [comment]
I believe this is now fixed in `a0afbe9542b39447d009d128a5a96ebcdbbde718`. 

<img width="563" alt="Screenshot 2020-07-20 at 10 35 57" src="https://user-images.githubusercontent.com/36071638/87923104-e37f2880-ca74-11ea-8335-9401151e0130.png">
