### ISSUE TITLE
Inconsistency in images in Superdense Coding notebook

### ISSUE THREAD

**Issue by Sahel13** [qiskit-community/qiskit-textbook#517]
## Describe the Issue
In the notebook Superdense Coding, there are inconsistencies in the way quantum states are represented in the images in sections 2.2 (Resulting State) and 2.3 (Bob Receives). For the message of '11', there is a global phase of '-1' between the previously mentioned columns. This may cause unnecessary confusion for readers (it did for me).

## Expected Solution
Change the 'Resulting State' for the 'Intended Message' of '11' in the table in section 2.2 by adding a global phase of '-1'.

**Comment by VANRao-Stack** [comment]
Hey @Sahel13! Is this the table you were talking about within the Superdense coding notebook that didn't have the global phase?
 
![Capture](https://user-images.githubusercontent.com/42447962/88088996-f09d3400-cba8-11ea-94cc-b4ca74250e2b.JPG)

Well, if it is then you can clearly see that, it has been mentioned at the bottom of the table that global phase has been ignored, I think this should counteract the chances of any confusion.

**Comment by Sahel13** [comment]
Hey.

This is one of the two tables that had I mentioned. While it is given that global phases are ignored, I do not see why two tables that lie immediately one after the other should have different representations of the same thing. It’s not a big issue though, but I believe this would make the reading experience cleaner, particularly for the more attentive readers.
