### ISSUE TITLE
Incorrect encoded qubit string in example illustration in Sec 3.12?

### ISSUE THREAD

**Issue by wakarasi** [qiskit-community/qiskit-textbook#518]
## Describe the Issue
In '2 Protocol overview' of '3.12 Quantum Key Distribution',  the document says the bits 1000101011010100 and the bases ZZXZXXXZXZXXXXXX would produce the encoded qubits |−⟩|0⟩|+⟩|0⟩|1⟩|0⟩|1⟩|+⟩|1⟩|−⟩|+⟩|−⟩|0⟩|−⟩|0⟩|+⟩.

## Expected Solution
I assume the encoding rule is as follows: 
  - In Z-basis, 0 and 1 are encoded to |0> and |1> respectively
  - In X-basis, 0 and 1 are encoded to |+> and |-> respectively

According to this, the encoded result should be |1>|0>|+>|0>|->|+>|->|0>|->|1>|+>|->|+>|->|+>|+> instead of the above.

**Comment by Abhigyan-Mishra** [comment]
I feel like this is correct and should be fixed.

**Comment by Abhigyan-Mishra** [comment]
Yes , this seem to be correct observation .

**Comment by Abhigyan-Mishra** [comment]
I would like to fix this typo.
