### ISSUE TITLE
Suggestion to add a chapter for Quantum Annealing

### ISSUE THREAD

**Issue by Hirmay** [qiskit-community/qiskit-textbook#532]
## Describe the Issue
I can't seem to find any information on quantum annealing in the qiskit textbook at least in term of a chapter or a subtopic.

## Expected Solution
Quantum Annealing is somewhat relevant to quantum computing and I think the learners should have at least some knowledge of the field which would benefit them.

**Comment by frankharkins** [comment]
@Hirmay do you have any expectations of what this chapter should cover? Or any ideas on how it should be approached?

**Comment by Hirmay** [comment]
I think the basic description of it, how promising does it seem, what are the flaws of it and maybe some examples of problems that can be used to solve with Quantum Annealing.

**Comment by nonhermitian** [comment]
This is well outside the scope of the textbook.

**Comment by Hirmay** [comment]
Ok I thought it was relevant but whatever you feel is the best for the textbook.

**Comment by nonhermitian** [comment]
Being that it is the Qiskit textbook and Qiskit only supports gate based quantum computing, it is a bit out of scope here.

**Comment by frankharkins** [comment]
I think it's worth acknowledging quantum annealing, even if it's just a line or two. Maybe could fit somewhere in proving universality.

**Comment by frankharkins** [comment]
I am closing this but continuing the discussion in #635
