### ISSUE TITLE
Minor mismatch in code vs diagram in section 3  "qc_output.draw()"

### ISSUE THREAD

**Issue by PuranBughani** [qiskit-community/qiskit-textbook#544]
## Minor mismatch in - https://qiskit.org/textbook/ch-states/atoms-computation.html

The output of `qc_output.draw()` is incorrect. 
The code output the above page is the output of `qc_output.draw(output='mpl')`

Either the command, `qc_output.draw()` must be changed to  qc_output.draw(**output='mpl'**)
, or else the diagram must be replaced .

## Anything else we should know? - Example of section 3
![Screenshot 2020-07-18 at 7 58 51 PM](https://user-images.githubusercontent.com/33637404/87854682-2932d880-c931-11ea-9599-14db933fc6a0.png)

Code to map the current diagram should be  "qc_output.draw(output='mpl'
![Screenshot 2020-07-18 at 8 02 17 PM](https://user-images.githubusercontent.com/33637404/87854755-b0804c00-c931-11ea-913c-0d0d18a2500d.png)
)"

**Comment by rochisha0** [comment]
Should I fix this issue? @PuranBughani

**Comment by frankharkins** [comment]
Hi, this depends on what qiskit's default drawer is set to. On the textbook website it is set to `'mpl'` so the `output='mpl'` line is redundant. You can see how to change your default here: https://qiskit.org/documentation/getting_started.html#step-4-visualize-the-circuit, maybe something that should be included is a mention in the textbook (probably in prerequisites) that explains this and shows how to set it up.

Please see #327.

**Comment by frankharkins** [comment]
I have opened an issue with an expected solution I believe will resolve this (#561).
