### ISSUE TITLE
Environment Setup Guide Needed

### ISSUE THREAD

**Issue by frankharkins** [qiskit-community/qiskit-textbook#561]
## Describe the Issue

Users have environments setup differently which can cause confusion when results differ to those seen in the textbook. Many users are also confused that the `qiskit_textbook` package does not come built-in with Qiskit.

## Expected Solution

We need a short explanation in the textbook prerequisites explaining:

- How to install the qiskit_textbook package ([see the Readme](https://github.com/qiskit-community/qiskit-textbook#installing-the-qiskit_textbook-package))
- How to set default drawer to MatPlotLib ([see here](https://qiskit.org/documentation/getting_started.html#step-4-visualize-the-circuit))
- Maybe explain how to set default draw type to svg which is preferred for the website (need to make [this modification to `ipython_kernel_config.py`](https://github.com/qiskit-community/qiskit-textbook/blob/62ce988152405acfbe4339ca8b62f09453041a7b/.ipython/profile_default/ipython_kernel_config.py#L1))
- Can also explain why we display the Qiskit version at the bottom of the page (to help with reproducing code - see #482)

**Comment by rochisha0** [comment]
@frankharkins Yes, I would like to take this issue.
