### ISSUE TITLE
Born's rule has the elements inverted in Section 2.1 of Chapter 1.3

### ISSUE THREAD

**Issue by MahatKC** [qiskit-community/qiskit-textbook#571]
**Describe the issue**
Throughout the Section, the probability to measure x in state psi is shown to be the square of the absolute value of the inner product of row vector psi and the vector x. However, in all sources I've found, the inner product is inverted: it's the inner product of row vector x and vector psi.

This inversion does not change the final value in the examples used in the textbook (or in any other examples I could come up with), but it creates an inconsistency with other sources and other chapters of the textbook (Chapter 1.4, Section 4 uses the "standard" order).

**Describe what you expect to see**
 This inconsistency might lead to confusion in the reader and I believe it should be avoided.

**Comment by frankharkins** [comment]
I'm in favour of this change.

**Comment by diemilio** [comment]
Hi @MahatKC, 

Is your intention to fix this yourself? If not, I will be happy to take care of it.

**Comment by MahatKC** [comment]
> Hi @MahatKC,
> 
> Is your intention to fix this yourself? If not, I will be happy to take care of it.

Thank you, but I believe it's a simple enough fix that I can do by myself.

**Comment by MahatKC** [comment]
> I'm in favour of this change.

I'll make a pull request then.

**Comment by frankharkins** [comment]
Fixed in PR#575
