### ISSUE TITLE
 Inconsistency for Quantum Fourier Transform's Qubit Order

### ISSUE THREAD

**Issue by Chriscrosser3310** [qiskit-community/qiskit-textbook#579]
**Describe the issue**

In the qiskit textbook's Quantum Fourier Transform section (https://qiskit.org/textbook/ch-algorithms/quantum-fourier-transform.html), the QFT is performed in the reversed order:

![image](https://user-images.githubusercontent.com/31495624/88240164-330f5100-cc3b-11ea-8ee8-e7bb6685ff4a.png)

This is inconsistent with the documentation (https://qiskit.org/documentation/stubs/qiskit.circuit.library.QFT.html), where the QFT is performed in the default order:

![image](https://user-images.githubusercontent.com/31495624/88240252-6fdb4800-cc3b-11ea-91b0-fc31a6b87a91.png)

This might be a mistake since the qiskit textbook implementation adds SWAP gates at the end of the circuit, which means the intention is to transform QFT into default order.

**Describe what you expect to see*

Remove the SWAP gates in the qiskit textbook implementation, or first perform reversed QFT and then add SWAP gates.

**Comment by abhik-99** [comment]
The Qiskit Textbook QFT is applied in the reverse order because of the positioning of the qubits I believe. It's mentioned in the Textbook as 

```
 Note: Remember that Qiskit's least significant bit has the lowest index (0), thus the circuit will be mirrored through the horizontal in relation to the image in section 5.
```

This is why when implementing the QFT, the swap gates are applied. However, the QFT from circuits library takes care of that by right out of the box.
Hope that helps.

**Comment by Chriscrosser3310** [comment]
@abhik-99 Thanks for the comment, I see what you mean. After doing some experiments, I think the textbook's QFT should be correct; but then I don't understand why the documentation implements QFT in that way? Is it consider qubit-0 as the most significant bit?

Take a 2-qubit gate as an example:
![image](https://user-images.githubusercontent.com/31495624/88261169-a2586580-cc7a-11ea-97c5-6710015c3b93.png)


The initial state of the circuit is |01> or [0, 1, 0, 0], so the QFT should transform [0, 1, 0, 0] to [0.5 ,0.5j, -0.5, -0.5j] based on the definition (eg. https://en.wikipedia.org/wiki/Quantum_Fourier_transform). However, the QFT in the circuit library transforms |01> to [0.5 ,0.5, -0.5, -0.5], which is in fact applying SWAP on the state [0.5, -0.5, 0.5, -0.5] or QFT|10>.

Changing do_swaps to False doesn't help, since the circuit treats q0 as the most significant bit and the final state is still QFT|10> instead of QFT|01>:
![image](https://user-images.githubusercontent.com/31495624/88261481-3fb39980-cc7b-11ea-998f-413e3b025d1a.png)

The only way that makes this work is by adding a SWAP gate before QFT:
![image](https://user-images.githubusercontent.com/31495624/88261926-0e879900-cc7c-11ea-8246-1cefe5cdc3d9.png)

It just seems a little inconsistent to me. Any clarification would be helpful.

**Comment by Chriscrosser3310** [comment]
I learned that there's an ongoing change in QFT which changes it to the little-endian convention, so I'll close this issue.
