### ISSUE TITLE
Code incorrect in 3.1 in Grover's Algorithm

### ISSUE THREAD

**Issue by Hirmay** [qiskit-community/qiskit-textbook#582]
**Describe the bug**
![error_tb](https://user-images.githubusercontent.com/56473003/88310507-5fa39580-cd2d-11ea-90c9-f457dcf11d2a.PNG)
I maybe wrong but as far I know here in the second line it should be circuit.cz(0,1)

**To Reproduce**
1. Go to 'https://qiskit.org/textbook/ch-algorithms/grover.html#3.1-Qiskit-Implementation-'

**Expected behavior**
Here the code in second line should be circuit.cz(0,1)

**Version info***
For qiskit problems, please provide the output of:
```
import qiskit
qiskit.__qiskit_version__
{'qiskit-terra': '0.14.1',
 'qiskit-aer': '0.5.1',
 'qiskit-ignis': '0.3.0',
 'qiskit-ibmq-provider': '0.7.1',
 'qiskit-aqua': '0.7.1',
 'qiskit': '0.19.2'}
```
For website problems please state device / OS / browser.

**Screenshots**

**Additional context**

**Comment by Hirmay** [comment]
if this is bug can someone assign it to me?

**Comment by frankharkins** [comment]
It's quite late here, but I think the existing code is correct? Remember in Qiskit the leftmost qubit in the ket corresponds to the most significant bit, i.e. |q2 q1 q0>. I think this is confirmed by the fact the code correctly amplifies `101` and `110`.

**Comment by aasfaw** [comment]
Yes, this seems like a bit ordering confusion. Closing for now.

**Comment by Hirmay** [comment]
so sorry, my bad.
