### ISSUE TITLE
Circuit decomposition of exp(-gamma*Hamiltonian) matrix

### ISSUE THREAD

**Issue by CodieKev** [qiskit-community/qiskit-textbook#599]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. "The explanation of X is [...]"
In chapter 4. Quantum Algorithms for Applications, section 1.3  that is "Solving combinatorial optimization problems using QAOA". 
5.3 Quantum Circuit
The matrix of `Exp(- gamma * Hamaltone(k,l))` denoted as `U_kl(gamma)` is a matrix given by 
```
[[1, 0, 0, 0],
 [0, Exp(-i*gamma), 0, 0],
 [0, 0, Exp(-i*gamma), 0],
 [0, 0, 0, 1]]
```
and its decomposition has been given by
```
QAOA.cu1(-2*gamma, k, l)
QAOA.u1(gamma, k)
QAOA.u1(gamma, l)
```
this gives us the correct result but is hard to wrap your head around. 
I suggest using
```
QAOA.cx( l, k)
QAOA.u1(-gamma, k)
QAOA.cx( l, k)
```
as quite easy to follow.
**Describe the solution you'd like**
A clear and concise description of what you want to happen, and how it fits with the existing content.
replace the messy
```
QAOA.cu1(-2*gamma, k, l)
QAOA.u1(gamma, k)
QAOA.u1(gamma, l)
```
with much more simpler 
```
QAOA.cx( l, k)
QAOA.u1(-gamma, k)
QAOA.cx( l, k)
```
decomposition. Doing this will help the student follow up on the decomposition and he/she will be able to decompose another different hamiltonian with ease.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions you've considered, e.g. linking to external resources.

**Additional context**
Add any other context or screenshots about the request here.

**Comment by QRiddler** [comment]
Hi! @frankharkins can you assign it to me? I would like to work on it

**Comment by QRiddler** [comment]
👀🙄🥱 @frankharkins
