### ISSUE TITLE
Subscript Error for Quantum Volume

### ISSUE THREAD

**Issue by exAClior** [qiskit-community/qiskit-textbook#601]
**Describe the issue**
In Step 6 when we are defining the achievable depth, we have 
![CodeCogsEqn](https://user-images.githubusercontent.com/10986218/88481100-84635d00-cf27-11ea-90a7-747ffdc3f3b6.gif)
**Describe what you expect to see**
In the paper referenced, I see 
![CodeCogsEqn (1)](https://user-images.githubusercontent.com/10986218/88481124-9ba24a80-cf27-11ea-9154-25521516b3a8.gif)
 which makes more sense since we want to take the width of the circuit the same while trying to get the largest depth r.s.t that width.

**Comment by Vismai-Khanderao** [comment]
Good catch on that one
