### ISSUE TITLE
[4.1.3] Mixed Up between U(dag) ,U and X(dag), X

### ISSUE THREAD

**Issue by CodieKev** [qiskit-community/qiskit-textbook#617]
#Describe the issue
4. Quantum Algorithms for Applications,
4.1.3 Solving combinatorial optimization problems using QAOA,
5.3 Quantum circuit
The decomposition of   Uk,l(γ) and Xk(β) is given as 
Uk,l(γ)=Cu1(−2γ)k,lu1(γ)ku1(γ)
Xk(β)=Rx(2β)k
which has been then used in the circuit design and that works as well.
But if we see how |ψp(γ,β)⟩  was described we get 
|ψp(γ,β)⟩ = e−iβ1Be−iγ1H|+n⟩.
which led to the formulation of 
|ψ1(γ,β)⟩ = X†1(β)X†0(β)U†01(γ)U†02(γ)U†12(γ)|+3⟩
so according to this, we were supposed to use the decomposition of U† and  X† in the circuit. But in qiskit notebook, U and X have been used. 
#Describe what you expect to see
The initial statement (5.2 Optimal trial state parameters) that 
|ψ1(γ,β)⟩ = X†1(β)X†0(β)U†01(γ)U†02(γ)U†12(γ)|+3⟩
so it makes 
Uk,l(γ)=exp[iγ/2*(1−ZkZl)]  and
Xk(β)=exp(iβXk)
which concludes to 
Uk,l(γ)=Cu1(2γ)k,lu1(-γ)ku1(-γ)
Xk(β)=Rx(-2β)k.

My suggestion will be to correct this problem starting from the root statement.

In 4.2.2 Computing the expectation value, the |ψp(γ,β)⟩ is defined as 
|ψp(γ,β)⟩ = e−iβ1Be−iγ1H|+n⟩.
we should take the Ukl in place of U†kl as that would make more sense that
|ψ1(γ,β)⟩ = X1(β)X0(β)U01(γ)U†02(γ)U12(γ)|+3⟩
and 
|ψ1(γ,β)⟩† = <ψ1(γ,β)| =⟨+3|U†21(γ)U†02(γ)U†01(γ)X†0(β)X†1(β)
by using this we will eliminate all the confusions related to conjugate transpose as in quantum all terms are defined this way 
If we choose this definition of |ψ1(γ,β)⟩ then the issue is solved by defining the Ukl and Xm as 
Uk,l(γ)=exp[-iγ/2*(1−ZkZl)]  and
Xk(β)=exp(-iβXk)
and redefine 
Uk,l(γ)=Cu1(2γ)k,lu1(-γ)ku1(-γ)
Xk(β)=Rx(-2β)k
as this will go with the flow of the quantum notations. As the operator|state> and its conjugate transpose <state| operator† have been used as the general notations in quantum.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
