### ISSUE TITLE
Use teleportation to deepen understanding of quantum concepts

### ISSUE THREAD

**Issue by frankharkins** [qiskit-community/qiskit-textbook#618]
**Is your feature request related to a problem? Please describe.**
The teleportation chapter currently describes what quantum teleportation is, and provides an example. The protocol is not explained, and this does not teach the reader anything new about quantum mechanics.

**Describe the solution you'd like**
I would like to see the teleportation chapter include an explanation of how the protocol works (as suggested in #382), but also to go further and use the chapter to teach / consolidate quantum concepts. In particular, I would like to show that (assuming `|psi> = a|0> + b|1>`), measuring the two qubits projects any superposition onto a state containing both amplitudes `a` and `b`. E.g:

`1/sqrt(2)( a|1>|10> + b|0>|10> )`

From which we can regain the teleported state through a combination of `X` and `Z` gates. This effect is seen in Simon's algorithm which currently follows shortly after, so this could be a good stepping stone.

If this goes well, we can perhaps even move the chapter to chapter 2 as an early example. (Including examples earlier has been suggested by multiple sources).

**Describe alternatives you've considered**
Alternatively, we can go the opposite direction and turn this into an exercise, where we guide the reader through working this out for themselves. Exactly how this might fit in with the labs and current exercises is not clear.

**Comment by rochisha0** [comment]
Hey,! If you need help can I work on this issue?

**Comment by frankharkins** [comment]
@rochisha0 yes, thanks for offering. I think the best course of action would be to come up with a draft plan for the new section. I imagined this new content would go between the current sections 3 & 4, so the chapter would read:

- 1. Overview
- 2. The Quantum Teleportation Protocol
- 3. Simulating the Teleportation Protocol
- **4. Understanding Quantum Teleportation**
- 5. Teleportation on a Real Quantum Computer

Do you have any preferences in how to approach this?

**Comment by rochisha0** [comment]
Hey, @frankharkins ! I think it is a nice idea to create a new section. But I think it would be better within Section 3 or before it. Or is it okay, that a 'text' section is sandwiched between two 'implementation' sections?

**Comment by frankharkins** [comment]
I think it is fine. If you want to put it in another section, I think section 2 would be more appropriate (like with superdense coding).
