### ISSUE TITLE
Some typos/grammar in new hardware section

### ISSUE THREAD

**Issue by livlanes** [qiskit-community/qiskit-textbook#620]
**Describe the issue**

Just some small errors with grammar and I see places the organization could be improved.

**Describe what you expect to see*

For instance, the transom section talks about the CPB, then real atoms, and then jumps back into SC qubits. I think this could easily be improved with a bit more organization. But I am going to take care of it, just posting here for clarity.

**Comment by livlanes** [comment]
Going to take care of this 👍

**Comment by frankharkins** [comment]
Fixed in #622
