### ISSUE TITLE
Repeated text reference in Shor's Algorithm

### ISSUE THREAD

**Issue by shadab-entrepreneur** [qiskit-community/qiskit-textbook#625]
**Describe the issue**
A line giving reference for QFT has been duplicated on [Shor's Algorithm](https://qiskit.org/textbook/ch-algorithms/shor.html#3.-Qiskit-Implementation) Page.

![image](https://user-images.githubusercontent.com/10863620/89080299-1e9f2700-d3a6-11ea-9726-1abeb58542de.png)

**Describe what you expect to see**
The first line is duplicate which should be removed.

**Comment by frankharkins** [comment]
Fixed in #626
