### ISSUE TITLE
A new chapter for application/solving problems of quantum gravity using quantum computing

### ISSUE THREAD

**Issue by Aniruddha120** [qiskit-community/qiskit-textbook#630]
**What should the reader gain from this new content?**
Quantum gravity is still theory-based and the problems can only be solved by quantum computers. The readers can understand the basics of quantum gravity, it's equations and how the quantum computers can be used for solving it's problems.

**Where do you expect this new content to fit in with the current content?**
Discussion needed.
*Are you proposing to write this new content?* (y/n)
No, but I want to(if I can manage myself understanding enough of the quantum logics and operations)

Additional [link](https://uwaterloo.ca/institute-for-quantum-computing/news/revealing-quantum-gravity-quantum-computer-simulation
)  [link2](https://www.quantamagazine.org/john-preskill-quantum-computing-may-help-us-study-quantum-gravity-20200715/)

**Comment by frankharkins** [comment]
I think this could be out of the scope of the textbook, but as I don't know anything about quantum gravity I'm willing to explore if this could be worked into a chapter.

If this chapter were to go ahead it should fit as a single, self-contained chapter in 4.2 and the focus of the chapter should be demonstrating experiments, for example those in [the paper referred to in link 1](https://www.nature.com/articles/s41534-019-0145-z.pdf).

If you (or someone else reading this) wants to write this chapter, can you please investigate the topic and propose a plan for the chapter. A good guideline is:
- An introduction to quantum gravity (roughly 500 words, 1000 maximum).
- An explanation / background necessary for the specific experiments featured in the chapter (500-1000 words).
- (optional) A simplified / worked through experiment using one or two qubits.
- An larger or more general implementation of the experiment in qiskit.
- A short conclusion interpreting the results and pointing to further reading.

It may be that the topic is too big to summarise in the introduction / background in which case it will be out of scope, but the investigation should reveal this for us.

**Comment by Aniruddha120** [comment]
> 
> 
> I think this could be out of the scope of the textbook, but as I don't know anything about quantum gravity I'm willing to explore if this could be worked into a chapter. If this chapter were to go ahead it should fit as a single, self-contained chapter in 4.2 and the focus of the chapter should be demonstrating experiments, for example those in [the paper referred to in link 1](https://www.nature.com/articles/s41534-019-0145-z.pdf).
> 
> If you (or someone else reading this) wants to write this chapter, can you please investigate the topic and propose a plan for the chapter. A good guideline is:
> 
>     * An introduction to quantum gravity (roughly 500 words, 1000 maximum).
> 
>     * An explanation / background necessary for the specific experiments featured in the chapter (500-1000 words).
> 
>     * (optional) A simplified / worked through experiment using one or two qubits.
> 
>     * An larger or more general implementation of the experiment in qiskit.
> 
>     * A short conclusion interpreting the results and pointing to further reading.
> 
> 
> It may be that the topic is too big to summarise in the introduction / background in which case it will be out of scope, but the investigation should reveal this for us.

Thank you for your reply. I have just got a good direction from you about how it should be. I am trying to make it happen..

**Comment by Aniruddha120** [comment]
I think I should try to give you a draft of it..

**Comment by Aniruddha120** [comment]
> 
> 
> I think this could be out of the scope of the textbook, but as I don't know anything about quantum gravity I'm willing to explore if this could be worked into a chapter. If this chapter were to go ahead it should fit as a single, self-contained chapter in 4.2 and the focus of the chapter should be demonstrating experiments, for example those in [the paper referred to in link 1](https://www.nature.com/articles/s41534-019-0145-z.pdf).
> 
> If you (or someone else reading this) wants to write this chapter, can you please investigate the topic and propose a plan for the chapter. A good guideline is:
> 
>     * An introduction to quantum gravity (roughly 500 words, 1000 maximum).
> 
>     * An explanation / background necessary for the specific experiments featured in the chapter (500-1000 words).
> 
>     * (optional) A simplified / worked through experiment using one or two qubits.
> 
>     * An larger or more general implementation of the experiment in qiskit.
> 
>     * A short conclusion interpreting the results and pointing to further reading.
> 
> 
> It may be that the topic is too big to summarise in the introduction / background in which case it will be out of scope, but the investigation should reveal this for us.

I am willing to make a try for it..

**Comment by frankharkins** [comment]
@Aniruddha120 yes please post it here so the community can see it.

**Comment by frankharkins** [comment]
@Aniruddha120 are you still working on this?

**Comment by Aniruddha120** [comment]
> 
> 
> @Aniruddha120 are you still working on this?

I am now working for my qiskit advocate test . Sorry, I didnt get back to you in this regard. But, I wish to work for it... I am extremely sorry about that...

**Comment by Aniruddha120** [comment]
I want to start my writing according to your "good guidance"

**Comment by frankharkins** [comment]
Don't apologise! There is no deadline, I was only checking. To clarify, at this point please just propose a plan for each subsection (I'm most interested in the introduction and background) and investigate whether it can be achieved sensibly in a single chapter.

**Comment by frankharkins** [comment]
@Aniruddha120 how is this going? In attempt to reorganise the issues I am closing this and adding it to a porject board [here](https://github.com/qiskit-community/qiskit-textbook/projects/3).
