### ISSUE TITLE
[4.1.2] Mathematical mistake

### ISSUE THREAD

**Issue by CodieKev** [qiskit-community/qiskit-textbook#631]
**Describe the issue**
4.1.2 Simulating Molecules using VQE, section: Structure of Common Variational Forms

There is a mistake done in the formulation of total no of Ry gate in linear as well as full entanglement.

**Describe what you expect to see**

 Ry with linear entanglement has  n×(d+1) parameters instead of 2n×(d+1/2)parameters
same for full engagement
 Ry with full entanglement has  n×(d+1) parameters
![SharedScreenshot](https://user-images.githubusercontent.com/59618255/89112151-4c569f80-d47c-11ea-8eb4-4576127d0e2a.jpg)
In the example given. We have 16 Ry parameters for both full as well as linear entanglement.
But the formulation gives an answer of 24 for linear entanglement and 34 for full entanglement.

**Comment by divshacker** [comment]
May I work on this issue?

**Comment by frankharkins** [comment]
closed in #1004
