### ISSUE TITLE
Add short explanation of quantum annealing

### ISSUE THREAD

**Issue by frankharkins** [qiskit-community/qiskit-textbook#635]
**Is your feature request related to a problem? Please describe.**
Quantum annealing is a talked-about area of quantum computing and it should be acknowledged in the textbook. A chapter is out of scope (see #532) but readers are likely to come across the term and will want to know how it relates to what they're learning.

**Describe the solution you'd like**
A short paragraph summarising the concept of adiabatic QC / quantum annealing, how it relates to the gate based quantum computation model and maybe even a few proposed advantages / disadvantages. I believe this paragraph would fit well at the end of [2.5 Proving Universality](https://qiskit.org/textbook/ch-gates/proving-universality.html#5.-Proving-Universality-) 

**Additional context**
See #532 for related discussion.

**Comment by charmerDark** [comment]
I think I could take up this and give you a draft in about two days.

**Comment by frankharkins** [comment]
@charmerDark thank you!

**Comment by charmerDark** [comment]
> In fact, the gate model of quantum computing is not the only universal model of quantum computation. There exist other forms of quantum computing such as the adiabatic quantum computing or the measurement based quantum computing. This means that it has been proven that there is a polynomial time and resource mapping from the  circuit gate model to these models of computing.These often leverage other quantum mechanical properties also in order to perform their computation.

> Quantum Annealing is another quantum computing model which is not universal nevertheless has some interesting applications.This means it cannot run the Shor's ,Grover's and many other quantum algorithms. It involves encoding problems into an energy landscape of sorts and then letting a wave function evolve into the landscape. While normal waves may get trapped at a local optima, quantum tunneling effect ensures the wave function reaches the global optima or really close levels. This can help with many optimization problems like the traveling salesman problem. 
> 
I was thinking of this for the paragraph. Please do let me know if this comes out as too popular science-ey or lacking in detail.

**Comment by frankharkins** [comment]
@charmerDark thank you!

> In fact, the gate model of quantum computing is not the only universal model of quantum computation.

Need to mention the gate model is the model we've been using (not sure if that's mentioned earlier)

> There exist other forms of quantum computing such as the adiabatic quantum computing or the measurement based quantum computing.

Need to make clear to the reader that they do not need to understand adiabatic quantum / MBQC computing, just that these other forms exist.

For the second paragraph, I think maybe start with something like "Other forms of quanutm computation are not universal, but are applicable to specfic applications. For example quantum annealing..."

> It involves encoding problems into an energy landscape of sorts and then letting a wave function evolve into the landscape. While normal waves may get trapped at a local optima, quantum tunneling effect ensures the wave function reaches the global optima or really close levels.

We need to be careful here as quantum physics is not a prerequisite. I actually believe you can zoom out more here and should avoid 'tunnelling' and 'wave function. Maybe something like "...letting quantum particles (not sure particles is the best word) explore the landscape to find the lowest point. While normal waves may get trapped in troughs which are lower than their surroundings (local minima), quantum effects increase the speed at which the particles (again, not sure about 'particles') find the true lowest point on the landscape (global minima)." This sentence still needs work (and checking for accuracy) but hopefully you see what I'm getting at.

**Comment by charmerDark** [comment]
Thank you @frankharkins 
Maybe this would be better? Please do advice me

> Everything we have discussed in this chapter and most of this book follows the circuit model of computation. However, the circuit model is not the only universal model of quantum computation. There exists other forms of quantum computing such as the adiabatic quantum computing or the measurement based quantum computer. This means that it has been proven that there is a polynomial time and resource mapping from the  circuit model to these models of computing.These often leverage other quantum mechanical properties also in order to perform their computation. However we  do not need to delve these other forms for our purposes..
There are other forms of quantum computation that are not universal, but are applicable to specific applications. For example quantum annealing is very useful to optimization and sampling problems. Annealing is the process of heating a metal to a high temperature and then allowing it to cool down slowly. This causes molten metal to flow over the surface of the metal piece and redistributes itself. This process changes many properties of the metal in question. Quantum annealing is analogous to this in some sense.  It involves encoding problems into an energy landscape of sorts and then letting a quantum state explore the landscape.While normal waves may get trapped in troughs which are lower than their surroundings (local minima), quantum effects increase the speed at which the quantum states find the true lowest point on the landscape (global minima).

**Comment by charmerDark** [comment]
@frankharkins maybe I should put in a PR for this now?
