### ISSUE TITLE
Redraw Images in Grover's Algorithm (3.10)

### ISSUE THREAD

**Issue by frankharkins** [qiskit-community/qiskit-textbook#644]
**Is your feature request related to a problem? Please describe.**
Some characters are difficult to read and the style does not fit the design of the textbook.

**Describe the solution you'd like**
The images will be redrawn professionally.

**Additional context**
This is already assigned and underway. This purpose of this issue is to alert others and to avoid duplication of effort.

**Comment by Aniruddha120** [comment]
I think I have pulled a request for it. Please kindly check my pull
https://github.com/qiskit-community/qiskit-textbook/pull/628/files

**Comment by Aniruddha120** [comment]
If I can understand the remaining graphs,angels and notation or if you provide some clearly hand-drawn picture of them, I can complete it

**Comment by frankharkins** [comment]
@Aniruddha120 thanks for offering to contribute. The image redrawings are already underway, I made this issue so other people can see this and avoid duplicating effort.

**Comment by Aniruddha120** [comment]
> 
> 
> @Aniruddha120 thanks for offering to contribute. The image redrawings are already underway, I made this issue so other people can see this and avoid duplicating effort.

Recently I just learned that, you were thinking about making a app for the textbook. would you let us to contribute something?

**Comment by frankharkins** [comment]
Resolved in #737
