### ISSUE TITLE
A chapter on quantum biology 

### ISSUE THREAD

**Issue by Aniruddha120** [qiskit-community/qiskit-textbook#646]
**What should the reader gain from this new content?**
The readers will get an example of equations related to quantum biology(though it can be related to quantum chemistry ) that can be performed using qiskit. 

**Where do you expect this new content to fit in with the current content?**
Under section 4 
Where will this place in the current table of contents? And what other content will need to change to accomodate it (prerequisite material etc.)?

*Are you proposing to write this new content?* (y/n)

Related link:[ link](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjn4KqJuILrAhVNzDgGHS58AoYQFjAVegQIChAB&url=https%3A%2F%2Farxiv.org%2Fpdf%2F1903.03454&usg=AOvVaw0Fmsne9hxEwCz8koEIAKaA)

**Comment by frankharkins** [comment]
@Aniruddha120 Are you aware of any applications of quantum computing to quantum biology that could fit in a single chapter and provide a useful demonstration? The paper you linked simulated a ion using VQE (which we already have a chapter on), and only mentions quantum biology in passing.

**Comment by frankharkins** [comment]
I am closing this issue as it is not clear what the new chapter should contain.
