### ISSUE TITLE
Suggestion to add a section for different types of qubits

### ISSUE THREAD

**Issue by Hirmay** [qiskit-community/qiskit-textbook#647]
**What should the reader gain from this new content?**

There are many types of qubits which a quantum computer can be made from like Silicon spin qubit, Superconducting transmon qubit, Topological qubit to name a few. So I believe that student should at least have an idea of what types of qubits can be used and some knowledge about each of them

**Where do you expect this new content to fit in with the current content?**

I'm not sure but maybe Investigating Quantum Hardware Using Quantum Circuits would be the most appropriate

**What material should this new content be based on?**

**Are you proposing to write this new content?** (y/n)

**Comment by frankharkins** [comment]
I am closing this and adding it to a project board [here](https://github.com/qiskit-community/qiskit-textbook/projects/3).

**Comment by Hirmay** [comment]
Yeah, I think that would be better.

**Comment by charmerDark** [comment]
Hey @frankharkins  Maybe I could try writing this section.? I feel the introduction page to the `Investigating Quantum Hardware using Quantum Circuits ` section could have this content . All the sections before it seemed to have some introductory matter in the first pages. And as for content, some intuition on superconducting dot qubits, NV center qubits, trapped ion qubits and the continuous variable photonic quantum computers should fit without making it too long?
