### ISSUE TITLE
Add description of the qsphere

### ISSUE THREAD

**Issue by diemilio** [qiskit-community/qiskit-textbook#649]
Given the growing interest in utilizing the qsphere to visualize multi-qubit states (particularly showcased in the latest update in the IBM Q circuit composer), it might be worth including a description (and some examples) somewhere in chapter 2. 

Section "1.3 Representing Qubit States" includes a subsection entitled "Visually Representing a Qubit State", where the Bloch sphere is introduced. Perhaps something similar can be done under "2.2 Multiple Qubits and Entangled States", where some of the features of the qsphere could be highlighted.

**Comment by frankharkins** [comment]
@diemilio yes this is a good idea. I have actually been writing a section that will discuss multiple quantum state visualisations and discuss the pros / cons of each, and this will include the qsphere.
