### ISSUE TITLE
Introduction to Complex Algebra

### ISSUE THREAD

**Issue by bytesalad** [qiskit-community/qiskit-textbook#653]
**What should the reader gain from this new content?**
I want to propose an addition to the Linear Algebra section of the textbook to cover the basic mathematics regarding complex algebra. While the Linear Algebra section is already quite well written, it assumes the reader has a good understanding of complex algebra. This may not always be the case especially if the reader is only familiar with classical computing or is not well-versed in mathematics. Complex algebra is a key part of the mathematics required to understand quantum computing, quantum gates, and the Bloch sphere. So after reading the material, the reader will be able to understand how to manipulate complex numbers, perform conjugates, represent complex numbers, and understand quantum gates that rely on the use of complex numbers.

**Where do you expect this new content to fit in with the current content?**
I think it will be best to include this section as a separate preliminary to the Linear Algebra section of the Appendix or as a chapter in the Linear Algebra section.

**What material should this new content be based on?**
Complex algebra mathematics and notation as required for quantum computing.

**Are you proposing to write this new content?** Yes.

**Comment by frankharkins** [comment]
@bytesalad can you give a brief outline of what the chapter would look like please? I.e. the topics and order they'd be covered in.

**Comment by bytesalad** [comment]
Yes of course. As a brief outline, I think it can be useful to cover:
This may not be an accurate reflection of the final order and subsection names. I'm super open on advice on feedback on how to tackle the concept to make it fit in well with the rest of the textbook. I think it would be best to add this to the Appendix chapter of the textbook.

- Real-imaginary form of a complex number (a + ib).
- Addition, subtraction, multiplication, and division of complex numbers in this form.
- How to take a conjugate of a complex number in real-imaginary form.
- Representing a complex number graphically.
- The modulus-argument form (r(cos(theta) + i(sin(theta)). (The reason for this form is to make the transition to Euler's formula which is very useful in chapters of the textbook such as the one dealing with the Bloch sphere.)
- Multiplication and Division of complex numbers in this form.
- Representing them graphically.
- Euler's formula (e^i(theta)). (This subsection, in particular, may be able to clarify some of the mathematics regarding the Bloch sphere and rotations.)
- Operations of complex numbers in this form.
- Graphical representation and intuition for Euler's formula.

**Comment by frankharkins** [comment]
@bytesalad okay great. I'm happy for you to start writing this. I will assign the issue to you. Please make a PR once you have a first draft (#651 is a good example of the process).

**Comment by bytesalad** [comment]
Awesome! Will do.

**Comment by frankharkins** [comment]
@bytesalad to keep the issues organised, I am closing this and adding it to a project board [here](https://github.com/qiskit-community/qiskit-textbook/projects/3). How are you getting along?

**Comment by bytesalad** [comment]
Hello! I'm sorry that it's taking some time. What took the longest is collecting resources in a relevant way. I will have a draft up very soon of the content. What I'm also trying to do is arrange it and write it in a way that fits well with the rest of the textbook.

**Comment by frankharkins** [comment]
@bytesalad that's great! There's no rush, let me know if I can help in any way. When you're ready please make a draft PR.

**Comment by bytesalad** [comment]
Thank you! Yes, I will.

**Comment by bytesalad** [comment]
@frankharkins I'm busy writing the first draft of the notebook on complex algebra. I have a question. I would like to include examples of where complex numbers are used in the textbook so that the reader can have better insight. But to do so, I may run the risk of exposing the reader to something they haven't encountered yet. Since it's just a part of the appendix, should I just give a general explanation of complex numbers?

Let me know if you don't understand my question.

**Comment by frankharkins** [comment]
yes just a general explanation without referencing the rest of the textbook would be best please
