### ISSUE TITLE
Deutsch-Jozsa Algorithm notebook fails to open on IBM Quantum Experience

### ISSUE THREAD

**Issue by elsalmi** [qiskit-community/qiskit-textbook#656]
Issue: 
- When opening the Deutsch-Jozsa Algorithm notebook found [here](https://qiskit.org/textbook/ch-algorithms/deutsch-jozsa.html), IBM Quantum Experience a 404: Not Found Error is returned.

Expected Response: 
- The notebook should open in IBM Quantum Experience like all of the other subsections in the textbook.

**Comment by kitaev-chen** [comment]
I see these links have been removed from the textbook ...

**Comment by frankharkins** [comment]
This is now fixed
