### ISSUE TITLE
Toolbar not appearing for Chapter 7, Set 3

### ISSUE THREAD

**Issue by elsalmi** [qiskit-community/qiskit-textbook#657]
Bug:

- The toolbar to the right of the browser is not showing for Chapter 7, set 3 - Building the Best AND Gate.

1. [Link](https://qiskit.org/textbook/ch-ex/ex3.html)
2. See error

**Expected behavior**

- The Toolbar should appear to the right of the window. 

OS: MacOS Catalina, Version: 10.15.6
Browser: Safari, Version: 13.1.2

**Comment by frankharkins** [comment]
While this is a valid issue, I'm assigning this "won't fix" and closing as chapter 7 is being replaced soon.
