### ISSUE TITLE
Summary of Notation Subsection 

### ISSUE THREAD

**Issue by elsalmi** [qiskit-community/qiskit-textbook#658]
#### New Feature Request 

- The textbook could be aided with a small section at the beginning with a summary of notation used throughout the book. This acts as a good primer for the symbols used in the textbook as well as providing a handy reference for quick recaps. 

- If approved, I would be happy to write it up.

**Comment by frankharkins** [comment]
Yes this is a good idea, should go in the appendix.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
