### ISSUE TITLE
Deutsch-Jozsa Algorithm: Subscript

### ISSUE THREAD

**Issue by rifat19331279** [qiskit-community/qiskit-textbook#660]
Hi, I have been studying DJ Algorithm from IBM Qiskit book and come across this problem. How do the subscripts turn into 10 or 11 from 1?

![image](https://user-images.githubusercontent.com/69009277/89876125-0c13c180-dbe0-11ea-808a-6ff0e4131a45.png)

**Comment by frankharkins** [comment]
This notation is not clear and needs either explaining or changing.

**Comment by aditya-giri** [comment]
It looks like the first subscript is the register and the second subscript is the qubit within the register. 
We could add a note explaining what the subscripts denote. 
On the other hand, maybe we don't need the subscripts at all? Given that there are only 3 qubits the ordering is fairly obvious. Also, until the last step, the qubits are being grouped by the register they belong to. So it's fairly easy to understand.

**Comment by frankharkins** [comment]
@aditya-giri that's true, I would vote to leave them out and mention we use the convention:

>  |q2> \otimes |q1> \otimes |q0>

**Comment by aditya-giri** [comment]
Let me try and make it clearer, and we can review it?

**Comment by aditya-giri** [comment]
I've tried to make it clearer, let me know what you think! 😄
