### ISSUE TITLE
Error 404 page not found

### ISSUE THREAD

**Issue by Fascaf** [qiskit-community/qiskit-textbook#661]
BUG DESCRIPTION
If one open the chapter called "Calibrating Qubits with Qiskit Pulse" and then click on link "Contribute to Github" the page is not found (error 404).

SOLUTION
There is a name error in the link:
https://github.com/qiskit-community/qiskit-textbook/tree/master/content/ch-quantum-hardware/calibrating-qubits-openpulse.ipynb

 it should be changed from "Open Pulse" to "Qiskit Pulse"

**Comment by shadab-entrepreneur** [comment]
Which script creates contribute to the Github link on documentation page?

**Comment by frankharkins** [comment]
I believe this issue is because the github master branch has been updated, but the website has not yet. Hopefully should be fixed by #676.

**Comment by frankharkins** [comment]
This took longer to fix than I anticipated. For some reason, the changes were not reflected correctly in the stable branch. Should be working now!
