### ISSUE TITLE
Introducing pro & cons of different type of pulses

### ISSUE THREAD

**Issue by Fascaf** [qiskit-community/qiskit-textbook#663]
**What should the reader gain from this new content?**
The goal of the section would be explaining the effect (pro and cons) of the different type of pulses available in Qiskit Pulse such as Gaussian, Gaussiansquare, Drag. 

**Where do you expect this new content to fit in with the current content?**
I would add a specific paragraph in the section called "Finding the qubit Frequency using a Frequency Sweep"

**What material should this new content be based on?**
The Qiskit documentation related to the type of pulses: 
https://qiskit.org/documentation/apidoc/pulse.html

**Comment by frankharkins** [comment]
@Fascaf are you proposing you write this content?

**Comment by Fascaf** [comment]
I honestly do not have the knowledge for comparing the effects on different type of pulses on a Qubit but surely I offer my help. I think Nick Bronn, Daniel Egger or some other people which have directly worked at the interface between the hardware and Qiskit Pulse could help with that.

**Comment by frankharkins** [comment]
I am closing this and adding it to a project board [here](https://github.com/qiskit-community/qiskit-textbook/projects/3).
