### ISSUE TITLE
Incorporate Qiskit Blog Quantum Volume content into Quantum Volume Textbook Chapter

### ISSUE THREAD

**Issue by ryanfmandelbaum** [qiskit-community/qiskit-textbook#685]
**Is your feature request related to a problem? Please describe.**
At present, the Qiskit textbook chapter titled [Measuring Quantum Volume](https://qiskit.org/textbook/ch-quantum-hardware/measuring-quantum-volume.html) is basically just copy-pasted from the Cross et al 2019 paper (https://arxiv.org/pdf/1811.12926.pdf) and it suffers from legibility issues. I think this chapter's content can be greatly improved.

**Describe the solution you'd like**
On 8/20/2020, the Qiskit Blog will publish an exhaustive explainer on Quantum Volume. This article will be meant for general audiences yet still rigorous and fact-checked by the IBM Quantum team. I would like to paraphrase or quote directly much of this article in order to improve the quantum volume textbook chapter.

**Describe alternatives you've considered**
I thought about linking to external resources or to the blog, but I think we should keep the textbook chapter as the best, clearest place to understand quantum topics.

**Additional context**
I volunteer to make the updates after 8/20 when the Qiskit blog is published, and will link the blog to this issue ticket.

**Comment by frankharkins** [comment]
This would be great, thanks!

**Comment by HuangJunye** [comment]
This is awesome! Look forward to the blog and new textbook chapter!

**Comment by frankharkins** [comment]
To keep the issues organised, I am closing this and adding it to [this project board](https://github.com/qiskit-community/qiskit-textbook/projects/3).
