### ISSUE TITLE
[5.4] Quantum volume measurement requires >= 100 trials

### ISSUE THREAD

**Issue by HuangJunye** [qiskit-community/qiskit-textbook#687]
**Describe the issue**
According to the quantum volume paper (https://arxiv.org/abs/1811.12926), QV measurement requires >= 100 trials to ensure approximation of binimial distribution to normal distribution and to obtain one-sided 2-sigma confidence interval of 97.5%. (Equation C2) However the example used in the chapter only has 50 trials.

**Describe what you expect to see**
Change number of trials from 50 to 100

**Comment by HuangJunye** [comment]
A related suggestion is to suppress the print statement in the loop of trials which prints a lot of lines.

**Comment by HuangJunye** [comment]
@ ShellyGarion are you the original author of the textbook chapter / tutorial? Do you think my understanding of the 100 circuits requirement is right?

**Comment by ShellyGarion** [comment]
I wrote the textbook chapter based on the following tutorial written by @dcmckayibm (who wrote the QV code in qiskit-ignis):
https://qiskit.org/documentation/tutorials/noise/5_quantum_volume.html
as well as the paper: https://arxiv.org/pdf/1811.12926.pdf
So, I would recommend that you ask David, Andrew or Lev (as you already did in the qiskit-ignis issue)

**Comment by HuangJunye** [comment]
@levbishop confirmed in https://github.com/Qiskit/qiskit-ignis/issues/473 that QV measurement requires >= 100 trials. (Algorithm 1 in the QV paper, n_c >= 100)

**Comment by frankharkins** [comment]
@HuangJunye thank you!
