### ISSUE TITLE
Little bit confusion regarding the linear algebra part under appendix

### ISSUE THREAD

**Issue by Peiqi-Hu** [qiskit-community/qiskit-textbook#690]
**Is your feature request related to a problem? Please describe.**
The content I have confusion about is _under the linear algebra appendix, close to the references part_. The problem is about the "last important fact about matrix exponentials". I attached a screen capture below. 

As I wrote on the side, I was not able to figure out why the proof is straightforward from M^n to v^n, and I searched online found A=PDP^-1 and substitute PDP^-1 back to the M which may work out eventually but takes a long way to get to the final proof. Until then, I recalled the equation A|V> = lambda*|v>, and the formula about why we need determinant to be zero which is det(A-lambda*I) = 0. That was why I finally get I can simply plug lambda*I into M. (Correct me if I still make mistakes on this part). 

**Describe the solution you'd like**
So I am wondering if someone can add a simple line saying "based on the formula det(A-lambda*I) = 0 we can prove balabala" instead of simply saying "much more straightforward to prove" if the textbook is targeting for those who are new to the quantum and linear algebra. 

And one last quick question, just to clarify, the tensor product of two matrices is also called Kronecker product, is that right? I searched on the wiki and pretty sure it is the same thing or maybe I am wrong on that. If so, is it possible to add a simple keyword mention it in the textbook? It is also _under the linear algebra appendix, the part right above eigenvectors and eigenvalues_. Since the content does give an example of a tensor product between two matrices other than two vectors and made me wonder a little bit when I typed tensor product on Google. 
Let me know if I misunderstand those concepts. 

Overall, I have to say the appendix is so good for going over the basic concept in linear algebra. Thank you all for that! 

**Additional context**
![one_property_about_matrix_exponentials](https://user-images.githubusercontent.com/26306522/90681038-c0d95e80-e230-11ea-8580-ab361c4c023f.jpg)

**Comment by frankharkins** [comment]
It is given that |𝑣⟩ is an eigenvector of 𝑀, so we have 𝑀|𝑣⟩ = 𝑣|𝑣⟩ as per 𝐴|𝑣⟩ = 𝜆|𝑣⟩. Then 𝑀^n|𝑣⟩ = 𝑀^{n-1}𝑣|𝑣⟩ = 𝑣^n|𝑣⟩ etc. Would the modified line:

> This one is much more straightforward to prove, from the eigenvalue equation 𝑀|𝑣⟩ = 𝑣|𝑣⟩ [(maybe even include a link)](https://qiskit.org/textbook/ch-appendix/linear_algebra.html#Eigenvectors-and-Eigenvalues) :

be sufficient?

**Comment by Peiqi-Hu** [comment]
Looks great!  Thank you.
