### ISSUE TITLE
Provide a way to run notebooks during CI without a real device

### ISSUE THREAD

**Issue by mriedem** [qiskit-community/qiskit-textbook#693]
**Is your feature request related to a problem? Please describe.**

We're packaging the qiskit textbooks from this repo into a docker image and would like to be able to run Travis CI against the notebooks and the version of qiskit that we have packaged in the image. However, we don't have real devices to run the notebooks against.

We need a way to run the notebooks (we're using `nbconvert` for running [qiskit-tutorials](https://github.com/Qiskit/qiskit-tutorials)) but ensure they don't need to run on a real device. If that means running them against the Aer simulator or just skipping notebooks that can't work in this type of environment would probably be OK as long as we still get a decent representation of knowing that the textbooks, for the most part, will run against the qiskit version we have packaged.

**Describe the solution you'd like**

We just need an entrypoint to run the textbooks as a test, maybe similar to the [run_notebooks.py script](https://github.com/qiskit-community/qiskit-textbook/blob/master/scripts/run_notebooks.py) or it could be a bash script or something invoked via `make` which would align with how [Travis CI runs against _this_ repo](https://github.com/qiskit-community/qiskit-textbook/blob/master/.travis.yml#L11).

**Describe alternatives you've considered**

Currently we're just packaging updates of the textbooks on demand and hoping someone will manually test them in our packaged image (which is available later via the [IQX JupyterHub site](https://quantum-computing.ibm.com/jupyter)) but we need to automate that process.

**Additional context**
n/a

**Comment by mriedem** [comment]
>At the moment this just prints the results. What would the output of this script need to be to incorporate into your workflow?

We need a pass/fail, so I'm not sure if `nbconvert` will handle that for us (that's how the qiskit-tutorials are tested) or if we need the script to exit with a non-0 code if any of the notebooks fail.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
