### ISSUE TITLE
Add Solutions for clarity of students reading the book

### ISSUE THREAD

**Issue by AnDa-creator** [qiskit-community/qiskit-textbook#695]
**Is your feature request related to a problem? Please describe.**
Not a problem, an appendix with answers to the exercises would be helpful for everyone reading the book.

**Describe the solution you'd like**
There are many questions left for the exercises. It would be helpful for the solutions for each unit.

**Describe alternatives you've considered**
Not an alternative, simply an enhancement.

**Additional context**
The solutions ribbon can be placed after each unit, like "Quantum States and Qubits", "Multiple Qubits and entanglement" etc.

**Comment by frankharkins** [comment]
[Here are my solutions to most of the quick exercises in sections 1 & 2](https://github.com/qiskit-community/qiskit-textbook/tree/solutions/content/solutions). Before we publish them we need to:
- Review the solutions.
- Review the questions ([e.g. this question isn't great](https://qiskit.org/textbook/ch-gates/more-circuit-identities.html#Quick-Exercise:) and should be changed / removed).

**Comment by AnDa-creator** [comment]
Hello frank, the solutions are pretty good. I have found small issues and suggestions and have noted them here: 
[https://docs.google.com/document/d/15a0dxxgZnBLz_hby1uSKYz8zI3gkPmb9zt9614THtxc/edit?usp=sharing](url)
Also I am writing it here directly too:
**Chapter: single qubit gates**
_Quick Exercises 1 :_ 
Q4: Can represent in polar coords than bloch coords
_Quick Exercises 3:_
Q3: got this error “TypeError '>' not supported between instances of 'int' and 'NoneType'”(bloch_Mulivector for single qubit bug already issued)

**Chapter: Phase Kickback**
_Quick Exercises:_
Q2: CU1 should be by -pi/2 (did pi/2)

Also textbook bugs found: 
Same Question number for all the questions in this exercise(Phase Kickback).
In chapter single qubit gates, on the right pane of contents, can’t move from one quick exercise to another by clicking.(_QE1_ and _Quick Exercises 3_ especially, minor bug)

**Comment by ms-O** [comment]
+1 on providing solutions for the exercises.  This would be beneficial to educators like myself who would like to use the Qiskit textbook in their courses.

**Comment by Jwala-1908** [comment]
I've uploaded my [solutions](https://github.com/Jwala-1908/my-qiskit-textbook-solutions) to the exercises from chapters 1 and 2 on . Would love comments and/or suggestions, and hope I can contribute something directly to the textbook as well.

**Comment by hritiksauw199** [comment]
I have developed solutions for all unsolved questions. 
If there are any mistakes or issues please let me know. 

https://github.com/hritiksauw199/Qiskit-textbook-solutions.git

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
