### ISSUE TITLE
state_vector_exercise gives correct but answer doesn't work. 

### ISSUE THREAD

**Issue by sod1684** [qiskit-community/qiskit-textbook#698]
**Describe the issue**

Code from this page: https://qiskit.org/textbook/ch-states/representing-qubit-states.html

The code is: 

```
# Run the code in this cell to interact with the widget
from qiskit_textbook.widgets import state_vector_exercise
state_vector_exercise(target=1/3)
```

This creates a UI. Entering in the following: 

`[0.5773, 0.81654]
`

This returns the answer: "Correct". 

Running the following code (which is copied from the page): 

```
initial_state = [0.5773, 0.81654]
qc = QuantumCircuit(1) # Must redefine qc
qc.initialize(initial_state, 0) # Initialise the 0th qubit in the state `initial_state`
state = execute(qc,backend).result().get_statevector() # Execute the circuit
print(state) 
```

This fails with:

`QiskitError: 'Sum of amplitudes-squared does not equal one.'`

**Describe what you expect to see*

Code should work if the answer is correct. 

I had a look at the state_vector_exercise code versus the `qiskit/extensions/quantum_initializer/initializer.py` code. 

In `qc.initialize()` it uses the following code to determine if it is equal to 1.0 

```
_EPS=1e-10
math.isclose(sum(np.absolute(params) ** 2), 1.0,  abs_tol=_EPS)
```
It's a much higher accuracy than state_vector_exercise

**Comment by frankharkins** [comment]
This is intended behaviour. The exercise is purposefully lenient to make sure the reader can enter something like `[sqrt(0.333), sqrt(0.666)]`, which indicates they understand the problem, and not be tripped up on a technicality. I think it's quite unlikely a reader would happen upon the vector `[0.5773, 0.81654]` (that has a magnitude of `1.00001`) without having correctly understood the concept.

Would it be sufficient if the tolerance was mentioned next to the exercise?

**Comment by sod1684** [comment]
I originally did the math on paper which is why I got the rounding error.  It wasn't obvious to me at the time that you would allow eval() in a form.

After going through the code for both in hindsight it became obvious that this was the most simple answer `[sqrt(1/3), sqrt(2/3)]`. Maybe mentioning tolerance, or that it accepts sqrt/etc is a good idea. Thanks for the follow up.
