### ISSUE TITLE
wrong table about superdense coding (chapter 3.3)

### ISSUE THREAD

**Issue by immaryw** [qiskit-community/qiskit-textbook#710]
**Describe the issue**

In chapter 3.3 superdense coding - **2.3 step 3**, the last row of the table is wrong.

According to step 2, Bob receives |10> - |01>, which becomes |10> - |11> after CNOT, but the final result (|11>) is correct.

**Describe what you expect to see**

The last row of that table should be "|10> - |01>, |10> - |11>, |11>".

<img width="441" alt="qk" src="https://user-images.githubusercontent.com/17716760/91651116-65cc1680-ea3d-11ea-904c-e6908635144d.png">

**Comment by rochisha0** [comment]
Actually, |01> - |10> and |10> -|11> represent the same thing because they differ by only a global phase. Though I do think they should change that cause it might be confusing to beginners.
