### ISSUE TITLE
Inconsistency with Quantum Teleportation circuit from chapter 3.1 and 3.2

### ISSUE THREAD

**Issue by wmurphy-collabstar** [qiskit-community/qiskit-textbook#714]
**Describe the issue**
Right now, in chapter 3.1, the quantum teleportation circuit shown in section 3. Example: Quantum Teleportation applies the Z gate and then the X gate on the third qubit after measuring the first two qubits. Whereas in chapter 3.2, the quantum teleportation circuit applies the X gate and then the Z gate, the exact flip. The circuit in chapter 3.2 is the correct version of the quantum teleportation algorithm while the circuit shown in chapter 3.1 is not.
**Describe what you expect to see*
I expect to see the image of the circuit in section 3 of chapter 3.1 to be updated so that it is consistent with the circuit in chapter 3.2.

**Comment by Hirmay** [comment]
I think you're correct, the picture in section 3 of chapter 3.1 should be changed with the picture in chapter 3.2.

**Comment by wmurphy-collabstar** [comment]
Actually, I found another small typo in the Quantum Teleportation Circuit in chapter 3.1. The labelling of the classical registers is flipped. Should I address it here or create a new issue?
