### ISSUE TITLE
Typo in the quantum teleportation circuit in chapter 3.1

### ISSUE THREAD

**Issue by wmurphy-collabstar** [qiskit-community/qiskit-textbook#721]
**Describe the issue**
In the last part of the circuit, when the X gate and then the Z gate are applied to the third qubit, the classical registers are labelled 'z_meas' where the X gate is applied and 'x_meas' where the Z gate is applied. 
**Describe what you expect to see**
I expect to see the names of the classical registers flipped so that the X gate corresponds to the x_meas register and the Z gate corresponds to the z_meas register.

**Comment by paniash** [comment]
@wmurphy-collabstar Thank you for pointing this out. I have made the changes and will make a PR for it.

**Comment by wmurphy-collabstar** [comment]
Thank you very much @paniash

**Comment by frankharkins** [comment]
This was fixed in #724
