### ISSUE TITLE
No module named 'numexpr'

### ISSUE THREAD

**Issue by SivaKarthickb** [qiskit-community/qiskit-textbook#726]
**Describe the bug**
I am facing ModuleNotFoundError when I executed the second cell in "The Atoms of Computation" section of the Qiskit textbook.

**To Reproduce**
1. Go to 'https://qiskit.org/textbook/ch-states/atoms-computation.html'
2. Run the code cell above the title: `Splitting information into bits`
3. Scroll down to 'https://qiskit.org/textbook/ch-states/atoms-computation.html#1.-Splitting-information-into-bits-'
4. Run the code cell below this line: `In this we are expressing numbers as multiples of 2, 4, 8, 16, 32, etc. instead of 10, 100, 1000, etc.`
5. See the error: `ModuleNotFoundError: No module named 'numexpr'`

**Expected behavior**
Run the code cell successfully and import plot_bloch_vector.

**Version info***
For qiskit problems, please provide the output of:
```
import qiskit
qiskit.__qiskit_version__
```
{'qiskit-terra': '0.14.2',
 'qiskit-aer': '0.5.2',
 'qiskit-ignis': '0.3.3',
 'qiskit-ibmq-provider': '0.7.2',
 'qiskit-aqua': '0.7.3',
 'qiskit': '0.19.6'}

For website problems please state Dell / Windows / Chrome.

**Screenshots**
![image](https://user-images.githubusercontent.com/41999143/92136243-68f24880-ee29-11ea-9208-29aa06263db1.png)

**Comment by frankharkins** [comment]
@SivaKarthickb I think I might have fixed this since you posted the issue. Can you please check if you have the same problem now?

**Comment by SivaKarthickb** [comment]
@frankharkins Now it's working. Thank you.
![image](https://user-images.githubusercontent.com/41999143/92299865-e75b0180-ef73-11ea-8e70-409e5c84a778.png)

**Comment by max-simon** [comment]
I use a virtual environment on my local machine and I had the same issue. I had to run `pip install numexpr` manually to make this work.
