### ISSUE TITLE
"not invertible" might be misleading in measurement-error-mitigation

### ISSUE THREAD

**Issue by YumaNK** [qiskit-community/qiskit-textbook#731]
**Describe the issue**
In the chapter of measurement-error-mitigation, there is phrase "This time we find a more interesting matrix, and one that is not invertible."

If one read it in straightforward way,  "not invertible" will be understood that the matrix does not have inverse matrix.
However, this matrix do have inverse matrix as its determinant is not zero.

Considering the context, one may infer that this phrase means that the matrix cannot reproduce ideal result. 
It would be great if the phrase is rephrased in the way that one can clearly understand what it actually mean.

![image](https://user-images.githubusercontent.com/19603134/92318678-08daec80-f04b-11ea-8447-d1522d9155fc.png)

**Describe what you expect to see*

**Comment by paniash** [comment]
@YumaNK Thank you for pointing this out and apologies for the delay. I have made the PR for it and have changed it as follows:
"This time we find a more interesting matrix, and one that we cannot use in the approach that we described earlier."

Please feel free to correct me if you don't find this correction convincing enough.
