### ISSUE TITLE
|00⟩+|11> is not mapped (1,0,0,1) but (0,1,1,0) in measurement-error-mitigation

### ISSUE THREAD

**Issue by YumaNK** [qiskit-community/qiskit-textbook#732]
**Describe the issue**
the measurement count of  (1/√2 ) (|00⟩+|11>) in 10000 shots is expected to be {00: 5000, 11: 5000} and should be mapped column vector as (5000, 0, 0, 5000)^T. 

However, in textbook this quantum state is mapped to column vector (0, 5000, 5000, 0)^T.

![image](https://user-images.githubusercontent.com/19603134/92318884-57898600-f04d-11ea-9cdb-4a32a147a562.png)

**Describe what you expect to see*
Vector C should be (5000, 0, 0, 5000)^T.

**Comment by tgag17** [comment]
Hi! Can I make the necessary changes
