### ISSUE TITLE
Error in diagram for Quantum Teleportation on QisKit webpage

### ISSUE THREAD

**Issue by hum99yw** [qiskit-community/qiskit-textbook#741]
Please view web-page https://qiskit.org/textbook/ch-algorithms/defining-quantum-circuits.html
where a quantum circuit diagram is shown under section 3. Example : Quantum Teleportation.
In an earlier post raised at https://github.com/qiskit-community/qiskit-textbook/issues/714
a request to swap the X gate and Z gate corrected an previous inconsistency but
now the diagram still has the following errors.
(a) The X-gate control signal comes from q0 line (error) and should be modified to connect to the q1 line.
(b) The Z-gate control signal comes from q1 line (error) and should be modified to connect to the q0 line.
(c) The labels at the bottom left for Zmeas and Xmeas are incorrect and should be swapped.

**Comment by paniash** [comment]
Thank you. The related PR #724 has already been merged.
