### ISSUE TITLE
Chapter 6.2: 'qiskit.pulse.commands' module was removed in 0.13.0 release

### ISSUE THREAD

**Issue by kifumi** [qiskit-community/qiskit-textbook#749]
**Describe the bug**
At Chapter 6.2 "Accessing Higher Energy States", in the first cell of importing dependencies, "from qiskit.pulse.commands import SamplePulse" is exist, but I got the error "ModuleNotFoundError: No module named 'qiskit.pulse.commands'".

[Release Notes](https://qiskit.org/documentation/release_notes.html) say;
"The qiskit.pulse.commands module containing Commands classes was deprecated in the 0.13.0 release and has now been removed. "
"The SamplePulse class from qiskit.pulse has been renamed to Waveform. SamplePulse is deprecated and will be removed in a future release."

**To Reproduce**
1. Go to https://qiskit.org/textbook/ch-quantum-hardware/accessing_higher_energy_states.html.
2. Click 'Try' on the first cell starting with 'import numpy as np'.
3. Click 'click here to go to the IBM Quantum Experience'.
4. Run the first cell starting with 'import numpy as np'.
5. Get the error as below;
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-27d91a133b7e> in <module>
     11 import qiskit.pulse.pulse_lib as pulse_lib
     12 from qiskit.compiler import assemble
---> 13 from qiskit.pulse.commands import SamplePulse
     14 
     15 from qiskit.tools.monitor import job_monitor

ModuleNotFoundError: No module named 'qiskit.pulse.commands'

**Expected behavior**
It should be run without error.

**Version info***
{'qiskit-terra': '0.15.2',
 'qiskit-aer': '0.6.1',
 'qiskit-ignis': '0.4.0',
 'qiskit-ibmq-provider': '0.8.0',
 'qiskit-aqua': '0.7.5',
 'qiskit': '0.20.1'}

**Comment by paniash** [comment]
@kifumi Hi! This appears to have already been corrected. The import is now done as
```python
from qiskit.pulse.library import SamplePulse
```
Cheers!

**Comment by vabarbosa** [comment]
Resolved by https://github.com/qiskit-community/qiskit-textbook/pull/789
