### ISSUE TITLE
Section name problem in QFT chapter

### ISSUE THREAD

**Issue by loic-broyer** [qiskit-community/qiskit-textbook#756]
In chapter "Quantum Fourier Transform", section 6 is named 1-qubit QFT.
However, the example given corresponds to a 3-qubit QFT.

**Comment by tgag17** [comment]
Yes. Also, in the index section 6 is named 3-qubit QFT but on clicking it we are directed to example 1 only

**Comment by tgag17** [comment]
Can I work on this issue?

**Comment by frankharkins** [comment]
@tgag17 I have assigned you, thank you!
