### ISSUE TITLE
Variational Quantum Regression

### ISSUE THREAD

**Issue by clearya1** [qiskit-community/qiskit-textbook#762]
Hi there! Over the summer, I wrote an algorithm which performs polynomial regression using the Qiskit software. The algorithm is a variational one, in that it computes a cost function using quantum hardware, coupled with classical optimisers. 

This algorithm takes two data sets - an independent data set (x) and dependent data set (y) and attempts to return the line of best fit for an n-th order polynomial. The inputs to the algorithm are the data sets (x & y) and the polynomial order (n).

**What should the reader gain from this new content?**

After the content, the student will understand how to compute the inner product of two states. They will gain a deeper understanding of the principle of variational quantum computing, which has been discussed in Section 4 of the Qiskit textbook. Putting these two learnings together, they will learn a method to perform polynomial regression.

**Where do you expect this new content to fit in with the current content?**

I was thinking that this work might be a nice addition to the textbook under the Implementations of Recent Quantum Algorithms section (4.2), so I created a Jupyter notebook similar to the Qiskit textbook style. Everything can be found at this repo: [VQR](https://github.com/clearya1/Variational-Quantum-Regression.git)

**What material should this new content be based on?**

This work was inspired by the section 4.2.1 of the Qiskit textbook. 
The method for computing inner products is based on this [paper](https://arxiv.org/pdf/1902.10394.pdf). 
The variational computing aspect of the work is based on this [paper](https://arxiv.org/pdf/1909.05820.pdf).

**Are you proposing to write this new content?** (y/n)

I have already written this [repo](https://github.com/clearya1/Variational-Quantum-Regression.git). I am of course willing to edit the Jupyter notebook as appropriate!

**Comment by frankharkins** [comment]
@clearya1 I apologise for the slow response. Can you please make a WIP pull request to the textbook with this? Please put the notebook in `content/ch-applications/`.

**Comment by frankharkins** [comment]
@clearya1 are you still able to work on this? If not, I will close this issue.

**Comment by clearya1** [comment]
Hi Frank, apologies for not having made the pull request yet. I am definitely still able to work on this, and will make the pull request this afternoon.
