### ISSUE TITLE
\mathbb{I} shows as a square on MacOS

### ISSUE THREAD

**Issue by fmauquie** [qiskit-community/qiskit-textbook#768]
On MacOS, the `\mathbb{I}` symbol for the identity matrix shows as a square :
<img width="184" alt="square identity matrix" src="https://user-images.githubusercontent.com/5713440/94269249-b3557980-ff3e-11ea-9ad5-12d9ee02db93.png">

This symbol can be found in the Linear Algebra chapter :
https://github.com/qiskit-community/qiskit-textbook/blob/5decfaf6e39d805eb1eef0e98ed5d9a1db9a3a53/content/ch-appendix/linear_algebra.ipynb#L4430

Verified on Firefox, Chrome, Safari and Edge. It is also a square in the GitHub-rendered notebook.

**Comment by frankharkins** [comment]
@fmauquie what do you expect to see? (I assume the attached image, below). 
<img width="23" alt="Screenshot 2020-09-29 at 16 18 10" src="https://user-images.githubusercontent.com/36071638/94578400-9aff9a80-026f-11eb-90f1-95187c2c5b46.png">
If the latex is correct, I believe this is likely a problem with mathjax and not something we can fix.

**Comment by fmauquie** [comment]
I think I expected to see a uppercase italic bold I, like the one in [the Wikipedia page about the identity matrix](https://en.wikipedia.org/wiki/Identity_matrix), but from the unicode code point your image is what should be rendered.

Copy-pasting the character (𝕀) in a [unicode search table](http://xahlee.info/comp/unicode_index.html) gives me this character:
MATHEMATICAL DOUBLE-STRUCK CAPITAL I
120128
U+1d540

On my mac it is rendered as:
```html
<span class="texatom" id="MathJax-Span-902">
  <span class="mrow" id="MathJax-Span-903">
    <span class="mi" id="MathJax-Span-904" style="font-family: STIXGeneral;">𝕀</span>
  </span>
</span>
```
The character looks like a square in the dev tools too. Firefox says that font STIXGeneral is a system font, e.g. not included in the webpage. [It looks like](https://bugzilla.mozilla.org/show_bug.cgi?id=1336058) it is a legacy font used for math, and Stix Math should be used instead. Maybe this is a parameter that can be changed on the page generator.

I actually got Firefox to render the MathML present on the equation, and it rendered the same square with the same font.
