### ISSUE TITLE
Shots should be not 1024 but 10000 to much the context [Chapter 5.1]

### ISSUE THREAD

**Issue by YumaNK** [qiskit-community/qiskit-textbook#769]
**Describe the issue**
The phrase  
"We'll repeat the process shots=1024 times to see how likely different results are."  
does not much the following phrase 
" In total, much less than 100 samples come out with a majority of 1s. When using this circuit to encode a 0, this means that P < 1%"

**Describe what you expect to see**

shots = 10000 should be correct. 

Then the cell before the phrase;
```
from qiskit import QuantumCircuit, execute, Aer

qc0 = QuantumCircuit(3,3,name='0') # initialize circuit with three qubits in the 0 state

qc0.measure(qc0.qregs[0],qc0.cregs[0]) # measure the qubits

# run the circuit with th noise model and extract the counts
counts = execute( qc0, Aer.get_backend('qasm_simulator'),noise_model=noise_model).result().get_counts()

print(counts)
```

should be

```
from qiskit import QuantumCircuit, execute, Aer

qc0 = QuantumCircuit(3,3,name='0') # initialize circuit with three qubits in the 0 state

qc0.measure(qc0.qregs[0],qc0.cregs[0]) # measure the qubits

# run the circuit with th noise model and extract the counts
counts = execute( qc0, Aer.get_backend('qasm_simulator'),noise_model=noise_model, shots=10000).result().get_counts()

print(counts)
```

**Comment by tgag17** [comment]
Hi! Should the number of shots be changed or the percentage mentioned in the notebook?

**Comment by YumaNK** [comment]
I guess shots should be changed.

**Comment by tgag17** [comment]
Yes I checked by changing the shots and the cases with majority of '1's were generated which were not there with 1024 shots.
Can I fix this in the main notebook?

**Comment by YumaNK** [comment]
Sure. Please fix it. Thanks
