### ISSUE TITLE
Auto update bib file for citing Qiskit textbook

### ISSUE THREAD

**Issue by HuangJunye** [qiskit-community/qiskit-textbook#774]
**Describe the problem**
I notice that bib file for citing Qiskit is updated automatically based on contributors but not the textbook. 

**Describe the expected solution**
Automatically update bib files based on github contributors similar to Qiskit package.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
