### ISSUE TITLE
[4.1.2] `get_probability_distribution` may not handle fringe cases correctly

### ISSUE THREAD

**Issue by frankharkins** [qiskit-community/qiskit-textbook#779]
**Describe the issue**
The following function can be found in the "[Example with a Single Qubit Variational Form](https://qiskit.org/textbook/ch-applications/vqe-molecules.html#Example-with-a-Single-Qubit-Variational-Form)" section of the VQE chapter.

```
def get_probability_distribution(counts):
    output_distr = [v / NUM_SHOTS for v in counts.values()]
    if len(output_distr) == 1:
        output_distr.append(0)
    return output_distr
```

It appears to convert the `counts` from an experiment result to a 'probability vector'. I believe the line `output_distr.append(0)`, conditioned on `len(output_distr) == 1`, is for the case in which the no. of counts for |1> is 0, so the returned list will be `[1, 0]`. If this is the intended function, in the case in which the counts for |0> is 0, this function will still return `[1, 0]` when it should instead return `[0, 1]`.

**Describe what you expect to see**
A solution that deals with both edge cases, possibly as simple as `output_distr.append(1 - output_distr[0])`.

**Comment by rochisha0** [comment]
I'll like to fix this.
