### ISSUE TITLE
[Chapter 5.1] "process_results" method cause confusion due to inconsistency among explanation, method behavior and examples.

### ISSUE THREAD

**Issue by YumaNK** [qiskit-community/qiskit-textbook#780]
**Describe the issue**
There are two main issues.
(1)
`code.process_results( raw_results )` causes reversed order of syndrome bits.
However, textbook explains syndrome bits after `process_results`  as it is still in regular order.
It makes readers hard to interpret how the syndrome bits are processed for topological codes.

In addition, strictly speaking  the expression "bitwise OR" in "It is therefore the bitwise OR of the syndrome measurement results from the second round with those from the first." should be "bitwise XOR" accord with python script of `process_results`.

For clarity, the last processed  syndrome should be explained more. From the python script, I managed to understand how the `raw_result` is processed (see following image). 
 
![image](https://user-images.githubusercontent.com/19603134/94715149-09d01700-0388-11eb-8aca-970d7cdcc59b.png)

(2)
"Example 3: 0 1  0000 0001 0000 represents a $d=5$, $T=2$ repetition code with encoded 1."
seems encoding not 1 but 0.
Pre-processed bit strings corresponds '00001 0001 0000'.
But even considering the reverse order of processed syndrome bit and encoding 0, this example bit string seems not match the explanation in textbook. 
I am not sure what bit string match the context, since it depends on which of `raw_results` and `process_result` actually corresponds the order of syndrome bits.

Though it is minor error, I noticed "$d=5$, $T=2$" should be "$n=5$, $T=2$" to match the definition before.

**Describe what you expect to see*

**Comment by frankharkins** [comment]
Fixed in #897
