### ISSUE TITLE
6.3 Small phi

### ISSUE THREAD

**Issue by HTransistor** [qiskit-community/qiskit-textbook#794]
**Describe the issue**
If E_J / E_C << 1 than phi, will be big as it is proportional to the inverse (despite the 4th root).
e.g. it is 1000 then phi would be 10, so phi << 1 is not true
![6_3_small_phi](https://user-images.githubusercontent.com/43704364/96598125-d7fb0200-12ee-11eb-8930-0f6e13907f1f.png)

**Comment by tgag17** [comment]
Hi! Kindly correct me if I am wrong but if the ratio Ej/Ec >>1 (say 1000) then phi= (2*Ec/Ej)^(1/4) would be proportional to the 4th root of 1/1000 (around 0.177) which is <<1

**Comment by HTransistor** [comment]
Yes, you are right. As you can see in the first words I typed, I have misread the >> as <<.
