### ISSUE TITLE
6.4 Equation references and confusing ordering of explanations

### ISSUE THREAD

**Issue by HTransistor** [qiskit-community/qiskit-textbook#798]
**Describe the issue**
This passage is really hard to read. First the perturbation is calculated in the first equation
The sentence about S does not to do anything with it, but "Now we know" implies it.
Apperently the text beneath the equation explains why it should have the form. I suggest Moving the text until the last sentence (ending with "even n") moving above the equation.

Futhermore the equation is written down generally, so without the perturbation parameter lambda as prefactor for H_1 and H_2. This is especially confusing when reading the next equation as we suddenly have it there, but also expand in S in lambda.

Later on the very first equation is used to get the result of H_eff (not in the screenshot), but as so many calculations happened it is not directly clear that there is a refference.

All in all references between the equation in form of \eqref would help a lot.
![6_4_perturbation_eq](https://user-images.githubusercontent.com/43704364/96734164-8a4bcb80-13ba-11eb-9198-c570b6521376.png)

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
