### ISSUE TITLE
New Sections for the Qiskit Textbook!

### ISSUE THREAD

**Issue by Lucaman99** [qiskit-community/qiskit-textbook#8]
Hello! I would like to propose that the following sections be added to the Qiskit textbook:

1. Introduction to Linear Algebra for Quantum Computing (Concepts ranging from intro to vectors and matrices, all the way to Hilbert spaces, matrix exponentials and eigenvector/eigenvalues)

2. Introduction to Quantum Computing (Concepts like quantum state vectors, observables, the generalized statistical interpretation, wavefunctions, etc.) --> This section definitely is applicable to quantum computing (and will include applications to quantum computing), but is not as readily useful when doing quantum programming with Qiskit as other sections. Despite this, I think having a section on some basic quantum mechanics is super important, in order for Qiskit users/quantum computing enthusiasts to get a taste and appreciate some of the underlying physics behind quantum computation.

3. Advanced Quantum States (This would include mixed vs. pure states and the density matrix)

**Comment by jwoehr** [comment]
It's easy to contribute a tutorial to [Qiskit/qiskit-community-tutorials](https://github.com/Qiskit/qiskit-community-tutorials) ... can you author such a document, @Lucaman99 ?

**Comment by Lucaman99** [comment]
@jwoehr Absolutely, that was always the intention! I’ve been corresponding with Abraham over the Qiskit Slack about contribuent some new sections to the textbook, and he told me to open an issue so he could assign these sections to me!

**Comment by quantumjim** [comment]
There's certainly a gap for advanced lin alg, advanced states and more in-depth QI topics (such as Von-Neumann entropy, Holevo bound, etc).

I think that both the states and gates chapters would be needed as a prerequisite for this. So how about having it all in a later chapter on 'quantum information'?

**Comment by Lucaman99** [comment]
@quantumjim Yeah, as it is right now, the linear algebra and quantum mechanics sections are almost done. I think the quantum mechanics part could definitely be in a more external section, as it isn't as applicable to quantum programming, but still useful for quantum info/quantum hardware/deeper understanding. The linear algebra section ranges from ultra-basic to advanced right now, and it includes topics that would be useful for understanding sections throughout the textbook, so I think putting that section at the beginning would be beneficial. 

I agree with you about the advanced states section though, it could definitely go in a "quantum info" section at the end.

**Comment by quantumjim** [comment]
This has all made we realize that we need to have some sort of roadmap for the book, specifying what each chapter is for, and how they relate to each other. So I made one in PR #10

**Comment by Lucaman99** [comment]
@quantumjim Yeah, I definitely think the advanced states section could go in a quantum info section, and that the quantum mechanics section should maybe go into the quantum hardware section (as I think it is probably most applicable as an introduction to how quantum systems behave). For the linear algebra section, I'm not totally sure. I'm almost done the Notebook, so I was thinking maybe I submit a pull request with the Notebook in another separate file, then you guys can take a look at it and decide where it would make most sense to place it, in the textbook. Would that be Ok with you?

**Comment by diemilio** [comment]
Has there been any progress made towards completing the chapter on advanced quantum states? I have been looking for ways to contribute to the qiskit community and would love to help authoring that chapter. It would cover definitions of the density matrix, pure states, mixed states; representing mixed states in the Bloch sphere; traces and partial density matrixes, etc. Qiskit’s quantum_info module would be use to generate examples.

After that I could potentially help with content related to Schmidt decomposition, measurement of entanglement and Von Neumann entropy.

**Comment by Lucaman99** [comment]
Hi @diemilio - That sounds awesome! I haven't gotten around to making any progress on this particular chapter, so if you want to take it on, that would be great. @aasfaw @frankharkins what do you think?

**Comment by diemilio** [comment]
Great. Thanks @Lucaman99. I can start working on this right away, and will obviously wait for @aasfaw and @frankharkins to decide how to proceed.

**Comment by frankharkins** [comment]
Hi, sorry I missed this comment. I think we need to work out the structure of the new chapter. I will try and form a proposal as soon as possible and then we can start populating it with content.

**Comment by frankharkins** [comment]
I am closing this as I believe the chapters initially suggested are either merged or have a PR in progress.
