### ISSUE TITLE
6.4 Transformation

### ISSUE THREAD

**Issue by HTransistor** [qiskit-community/qiskit-textbook#800]
**Describe the issue**
Why we transform with the -i*Dagger(D)*D' part?
**Describe what you expect to see*
![6_4_transform](https://user-images.githubusercontent.com/43704364/96859521-e4539c00-1461-11eb-9730-3554e4c06358.png)

**Comment by paniash** [comment]
@HTransistor Hi! I'm not very clear with your question. Is it a doubt that you have or is it an issue present in the textbook per se? Also, it would be great if you would mention the chapter from where is portion is from. Thanks!

**Comment by HTransistor** [comment]
The chapter is 6.4 as stated in the title, the name of the subchapter is circuit quantum electrodynamic in chapter investigating quantum hardware using micro waves.

D is the glauber operator. 
The question is why we use exactly this transformation (is it a common transformation)? There is no comment on this passage, why this expression is even calculated. In the end you get a simplified Hamiltonian with another differential equation...

Also there are precalculation are for D^+ H D, but not for D^+ D^•
It is also not clear how the derivative in this approximation should be taken.

**Comment by Rukhsan** [comment]
@HTransistor  The Glauber operator is part of time dependent Schrieffer-Wolff transformation. Myself and Nick Bronn are working to add more content around SWT to make it more accessible.

**Comment by Rukhsan** [comment]
@frankharkins Just to keep you posted that me and @nbronn are going to fix this very soon.
