### ISSUE TITLE
Deutsch-Jozsa: last figure legend obviously wrong (run on actual hardware)

### ISSUE THREAD

**Issue by stanescuUW** [qiskit-community/qiskit-textbook#804]
**Describe the issue**

The last figure (at the bottom) in the presentation of the D-J algorithm (Qiskit Textbook), which shows results from a run on actual hardware, is obviously wrong. The legend states "As we can see, the most likely result is 1111" while the highest bar in the histogram is at 1101.

**Describe what you expect to see*

**Comment by tgag17** [comment]
Hi! Yes, there is an error with the figure. I checked the code by running it and the resultant figure gives the correct result (highest count for 1111). Can I make the necessary changes?

**Comment by stanescuUW** [comment]
Not sure whether the question about the changes is for me or not, but as far as I'm concerned please do change it - absolutely!
