### ISSUE TITLE
Quantum Teleportation notebook code is wrong

### ISSUE THREAD

**Issue by the-legend-of-lia** [qiskit-community/qiskit-textbook#810]
**Describe the issue**
https://qiskit.org/textbook/ch-algorithms/teleportation.html
Screenshot 1:
![image](https://user-images.githubusercontent.com/16793587/97992249-57ea9700-1dda-11eb-8005-c8f2fa29e36c.png)
Screenshot 2:
![image](https://user-images.githubusercontent.com/16793587/97992268-5de07800-1dda-11eb-9f09-826282304979.png)
Above are 2 screenshots from the Qiskit textbook. I think the first image above is right. The second image the order of the CX and CZ gate at the end of the circuit should be the other way around; this mistake contributes to a global phase s.t. the state vector is multiplied by -1 (hence why the measurement probabilities are fine)

**Describe what you expect to see*
The code verbatim from the textbook below

> def new_bob_gates(qc, a, b, c):
    qc.cz(a, c)
    qc.cx(b, c)

should be

> def new_bob_gates(qc, a, b, c):
    qc.cx(b, c)
    qc.cz(a, c)

**Comment by the-legend-of-lia** [comment]
Note: I found this content bug because Dayeong Kang (tula3and on github) made slides about quantum teleportation in Qiskit with the right circuit :)

**Comment by paniash** [comment]
@the-legend-of-lia Thank you for pointing this out. I have made a PR for it, let me know if it is fine.
