### ISSUE TITLE
Grover's Algorithm Matrix Size

### ISSUE THREAD

**Issue by carlklier** [qiskit-community/qiskit-textbook#812]
**Describe the issue**
Shouldn't the matrix go from f(0) to f(2^(n-1)) rather than f(2^n). For 3 qubits the array matrix would be 8x8 like in the example shown, but the matrix shown right below/after "oracle's matrix will be a diagonal matrix of the form:" appears to be larger than 8x8 for n=3.
![image](https://user-images.githubusercontent.com/48186448/98034909-b79a6f80-1de5-11eb-82e9-ce4a3b72a8f9.png)

**Comment by paniash** [comment]
Thank you for pointing this out. I have the relevant PR for it. :)
