### ISSUE TITLE
Grammatical Error in the Linear Algebra Section of the Qiskit Textbook

### ISSUE THREAD

**Issue by heinzay1999** [qiskit-community/qiskit-textbook#816]
**Describe the issue**

" is said to be linearly dependent if there exist corresponding coefficients for each vector ..." This a sentence under the Spanning Sets, Linear Dependence, and Bases section of the textbook. I feel like the phrase "if there exist" is grammatically incorrect. 

https://qiskit.org/textbook/ch-appendix/linear_algebra.html

**Describe what you expect to see*

My suggestion would be to change it to " if there are existing corresponding coefficients ...". I am open to suggestions and comments on this issue. 
<img width="601" alt="I think the grammer is off here   there are" src="https://user-images.githubusercontent.com/64345115/98369450-fa875d80-2006-11eb-81fa-b70ceac73369.png">

**Comment by paniash** [comment]
@heinzay1999 Hi! Pardon me but I don't really find the sentence grammatically incorrect. In general, you'll find such phrases used in math textbooks all the time.

**Comment by heinzay1999** [comment]
@paniash Hi!! You could be correct as well. When I came across it, it sounded weird to me. Lets see what others have to say.

**Comment by jwoehr** [comment]
The sentence is correct as stands. The verb **exist** is conjugated here in the **present subjunctive 3rd person plural** form in agreement with its plural subject **coefficients**.

The syntactic order can be puzzling ... reordering the sentence one could say with grammatical and syntactic soundness, "_If corresponding coefficients for each vector exist there, then ..._"

**Comment by heinzay1999** [comment]
Ok then. Well thanks to both @paniash and @jwoehr for helping out.
