### ISSUE TITLE
6.3 Disconnect between Transmon Hamiltonian and qubit Hamiltonian

### ISSUE THREAD

**Issue by diemilio** [qiskit-community/qiskit-textbook#817]
**Is your feature request related to a problem? Please describe.**

The introduction for "[6.3 Introduction to Transmon Physics](https://qiskit.org/textbook/ch-quantum-hardware/transmon-physics.html)" suggests that this chapter will explain how the Transmon can be used as a qubit. To do this, the Hamiltonian for the Transmon is first derived very nicely in [section 4](https://qiskit.org/textbook/ch-quantum-hardware/transmon-physics.html#4.-The-Quantized-Transmon-) as:
![image](https://user-images.githubusercontent.com/65074936/98371195-c5303f00-2009-11eb-98a2-6d512cd7fda5.png)

But then in [section 6](https://qiskit.org/textbook/ch-quantum-hardware/transmon-physics.html#6.-Qubit-Drive-and-the-Rotating-Wave-Approximation-), the Hamiltonian of the qubit is simply given as:
![image](https://user-images.githubusercontent.com/65074936/98371540-53a4c080-200a-11eb-956b-6c246a1691d7.png)

There is no explanation on how the two are related to each other, making it impossible to understand how the Transmon Hamiltonian is related in any way to the qubit. Also, there seems to be a very abrupt change in notation from the oscillator representation to a spin representation that needs some clarification.

**Describe the solution you'd like**

I would suggest adding another section in between sections 5 and 6 explaining how one arrives to the Qubit Hamiltonian from the Transmon Hamiltonian.

**Comment by diemilio** [comment]
wow! That was quick! Thanks @nbronn

**Comment by nbronn** [comment]
No problem @diemilio! I was adding another derivation in the same notebook, so thought I'd fix up that Hamiltonian at the same time.
