### ISSUE TITLE
Image text readability issue when viewed in dark mode

### ISSUE THREAD

**Issue by paniash** [qiskit-community/qiskit-textbook#821]
**Describe the bug**
When the textbook is viewed in dark mode (using addons like [Dark Reader](https://darkreader.org/)), the text in the images becomes difficult to read, owing to the fact that the images are .png files.

**Expected behavior**
Using alternate image formats like .jpg would render the background of the images to be opaque and hence improve readability of text when viewed in dark mode.

**Version info***
For website problems please state device / OS / browser.
Device: Laptop
OS: Artix Linux
Browser: Firefox with dark reader addon

**Screenshots**

*Light mode*
![light](https://user-images.githubusercontent.com/59497618/98634462-62141480-2349-11eb-9dd4-80a1255f5924.png)

*Dark mode*
![dark](https://user-images.githubusercontent.com/59497618/98634505-748e4e00-2349-11eb-9d3f-d3fe340732d1.png)

**Comment by frankharkins** [comment]
This is something that needs to be fixed on darkreader's side ([see here](https://github.com/darkreader/darkreader/issues/356)). We don't support a dark mode yet, but it is low-priority in the backlog (#377).

**Comment by paniash** [comment]
@frankharkins Thank you!
