### ISSUE TITLE
Unable to display image in Chapter 1.2 

### ISSUE THREAD

**Issue by rakaar** [qiskit-community/qiskit-textbook#822]
**Describe the issue**
In Chapter 1.2 - `The Atoms of Computation` in section 4.3, a image doesn't show up in both `qiskit.org/textbook` and `IBM Quantum Experience`. Below are the attached screenshots
![image](https://user-images.githubusercontent.com/44907757/98801646-1724fa80-2438-11eb-80d3-88341993553b.png)
![image](https://user-images.githubusercontent.com/44907757/98801656-1db37200-2438-11eb-8849-eed6d75ea00c.png)

**Describe what you expect to see**
I expect to see the image that is described in the text just above it

**Comment by frankharkins** [comment]
Looks like for some reason this image was hosted elsewhere and is no longer available. I know what this image should look like so I'll recreate it with qiskit and add it to textbook repo so it can be hosted on the textbook website.
