### ISSUE TITLE
Inconsistent quibit notation in 3.2 Quantum teleportation

### ISSUE THREAD

**Issue by gonzrubio** [qiskit-community/qiskit-textbook#830]
**Describe the issue**
In section: 4. Understanding Quantum Teleportation, under step 1, it reads:
Alice and Bob each possess one qubit of the entangled pair (denoted as A and B respectively). The Bell state vector labels Alice's and Bob's qubit in the reverse order.

**Describe what you expect to see*
|psi> = (1/sqrt(2))(|0>_B|0>_A+|1>_B|1>_A)

**Comment by paniash** [comment]
@gonzrubio Hi! The mathematics assumes big-endian notation whereas qiskit uses little-endian notation. I understand that this is inconsistent with the particular chapter in question but I find it perfectly understandable. Let me know if you feel otherwise.

**Comment by gonzrubio** [comment]
Thank you @paniash. I find it perfectly understandable - I just wanted to let you know it was inconsistent with the chapter and qiskit's notation.
