### ISSUE TITLE
Subscript at improper places in Grover's Algorithm

### ISSUE THREAD

**Issue by rakaar** [qiskit-community/qiskit-textbook#835]
**Describe the issue**
Though this is not a serious issue. But felt it can be changed. The subscripts for `U` above the circuit are not at the proper place at [this](https://qiskit.org/textbook/ch-algorithms/grover.html) link. 
![image](https://user-images.githubusercontent.com/44907757/99905650-23426f00-2cf8-11eb-8089-dba4bc415c4e.png)
![image](https://user-images.githubusercontent.com/44907757/99905654-289fb980-2cf8-11eb-9d0f-560547af67e0.png)
![image](https://user-images.githubusercontent.com/44907757/99905656-2dfd0400-2cf8-11eb-8f8a-ae4b873ac137.png)

**Describe what you expect to see**
Subscript of `U` to be at proper places(o,s)-just beside of `U`

**Comment by paniash** [comment]
@rakaar Hi! This seems to be specific to your system. It looks fine on my end though. Can you tell me which browser you're on? Maybe try changing the monospace font in your browser settings.

**Comment by rakaar** [comment]
@paniash 
The above images are from Microsoft Edge Browser.
The issue is also on Chrome and Firefox
Chrome:
![image](https://user-images.githubusercontent.com/44907757/100068942-2bb4ba00-2e5e-11eb-9322-9aaa5a8b9112.png)
Firefox:
![image](https://user-images.githubusercontent.com/44907757/100068954-31120480-2e5e-11eb-9a63-a35f1c41418c.png)

**Comment by paniash** [comment]
> Maybe try changing the monospace font in your browser settings.

@rakaar Have you tried doing this? 

This is strange. I don't see it on my laptop but it does seem to be an issue when I view it on Android.

**Comment by rakaar** [comment]
@paniash 
how are font settings related to it, this is a image right?

![image](https://user-images.githubusercontent.com/44907757/100132848-02bb1600-2eac-11eb-9423-61aa56bed3fe.png)

**Comment by paniash** [comment]
@rakaar Yes but I as I said, I don't see the issue on my end. No harm in fiddling with the fonts, just in case it rectifies the issue ;)

The below are screenshots from my system: (In order: Chromium and Firefox)

![pic-full-201124-2331-16](https://user-images.githubusercontent.com/59497618/100136616-45cbb800-2eb1-11eb-8584-a5d1184f2fb9.png)


![pic-full-201124-2331-47](https://user-images.githubusercontent.com/59497618/100136630-495f3f00-2eb1-11eb-82d1-c3763e4f0367.png)

**Comment by frankharkins** [comment]
I believe this is a browser issue instead of a problem on our end. Either way, this is low priority and will most likely become redundant soon as images are changed. I am closing this but feel free to re-open if you think this is unfair.
