### ISSUE TITLE
[3.1] Improvement on section 3.1: Describing the Restricted Qubit State

### ISSUE THREAD

**Issue by theinlinaung2010** [qiskit-community/qiskit-textbook#843]
I think section **3.1** could be improved for more clarity to the beginners like me. First, rewriting the qubit state with <img src="https://render.githubusercontent.com/render/math?math=\alpha ,\beta ,\phi \in \R"> could be elaborated a little, possibly showing how two complex numbers can be written with two real numbers with a phase difference. This is similar to the proposal #415.

Moreover, the explanation of the logical link between:
<img src="https://render.githubusercontent.com/render/math?math=\sqrt{\alpha^2 %2B \beta^2} = 1">
and
<img src="https://render.githubusercontent.com/render/math?math=\sqrt{\sin^2{x} %2B \cos^2{x}} = 1">
then
<img src="https://render.githubusercontent.com/render/math?math=\alpha = \cos{\tfrac{\theta}{2}}, \quad \beta=\sin{\tfrac{\theta}{2}}">
seems arbitrary. Hence I propose an alternative explanation.

Since the first equation can be thought of as the equation of unit circle, <img src="https://render.githubusercontent.com/render/math?math=\alpha"> and <img src="https://render.githubusercontent.com/render/math?math=\beta"> can be derived from the unit vector at an angle of <img src="https://render.githubusercontent.com/render/math?math=\theta/2"> as shown in the figure below.

![qubit_real_plane](https://user-images.githubusercontent.com/4274363/100514384-a01d8f00-31b7-11eb-862e-27b6eab05a59.png)

Note the figure shows the real plane ignoring the phase difference. Why is the angle <img src="https://render.githubusercontent.com/render/math?math=\theta /2">? Because we want to show the equal superposition of |0> and |1> on the X axis of Bloch sphere in which |0> and |1> are 180 degrees apart.

![qubit_bloch](https://user-images.githubusercontent.com/4274363/100514526-d6a7d980-31b8-11eb-838a-b74cff7b16f5.png)

According to these axes, when <img src="https://render.githubusercontent.com/render/math?math=\theta=90 ^\circ, \alpha=\cos{\frac{\theta}{2}}=\frac{1}{\sqrt{2}}, \beta=\sin{\frac{\theta}{2}}=\frac{1}{\sqrt{2}}">. Relative phase <img src="https://render.githubusercontent.com/render/math?math=\phi"> can be visualized as the rotation around the Z axis.

Section 3.2 can be followed after this.

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
