### ISSUE TITLE
Quantum Key Distribution section is better after Superdense Coding

### ISSUE THREAD

**Issue by attp** [qiskit-community/qiskit-textbook#844]
In Chapter 3 _Quantum Protocols and Algorithms_, the **Quantum Key Distribution** section logically fits better after the **Superdense Coding** one, rather than at the end. This groups all the communication protocols together in the chapter. 

![tb-qkd](https://user-images.githubusercontent.com/9410731/100556266-41f6c600-32f5-11eb-8d61-52f9dd0f60d9.png)

**Comment by quantumjim** [comment]
Another thing to note here: this section does not seem to name the protocol. Is it BB84?
