### ISSUE TITLE
Image links in the book are broken

### ISSUE THREAD

**Issue by westaf2000** [qiskit-community/qiskit-textbook#853]
It appears that some assets stored on s3 are no longer there.

For example, in chapter 1.1, Introduction, after the first paragraph, there's an image reference:

```
{
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "![image1](https://s3.us-south.cloud-object-storage.appdomain.cloud/strapi/b37a8ea62054452f83a2c051e7de12efatoms10.png)\n"
   ]
  },

```

The asset no longer exists, as shown below:

```
C:\Users\xin > wget --no-check-certificate https://s3.us-south.cloud-object-storage.appdomain.cloud/strapi/b37a8ea62054452f83a2c051e7de12efatoms10.png
--2020-12-08 10:32:06--  https://s3.us-south.cloud-object-storage.appdomain.cloud/strapi/b37a8ea62054452f83a2c051e7de12efatoms10.png
Resolving s3.us-south.cloud-object-storage.appdomain.cloud... 169.46.118.100
Connecting to s3.us-south.cloud-object-storage.appdomain.cloud|169.46.118.100|:443... connected.
WARNING: cannot verify s3.us-south.cloud-object-storage.appdomain.cloud's certificate, issued by '/C=US/O=DigiCert Inc/CN=DigiCert TLS RSA SHA256 2020 CA1':
  Self-signed certificate encountered.
HTTP request sent, awaiting response... 404 Not Found
2020-12-08 10:32:06 ERROR 404: Not Found.
```

**Comment by theinlinaung2010** [comment]
Broken links at [S2.4](https://qiskit.org/textbook/ch-gates/more-circuit-identities.html) too. 

https://s3.us-south.cloud-object-storage.appdomain.cloud/strapi/4efe86a907a64a59a720b4dc54a98a88iden1.png
https://s3.us-south.cloud-object-storage.appdomain.cloud/strapi/693974b222d24dba9111e02ae25e9151iden2.png
https://s3.us-south.cloud-object-storage.appdomain.cloud/strapi/b3cbeb9b7d674d60a75bed351e4f2bcbiden3.png

**Comment by vabarbosa** [comment]
@westaf2000 thanks. working on getting them restored.
