### ISSUE TITLE
4.1.1. [HHL] Inconsistency in circuit_depth

### ISSUE THREAD

**Issue by paniash** [qiskit-community/qiskit-textbook#865]
**Describe the bug**

After executing the following code under the general method section (4A),
```python
print("circuit_width:\t", result['circuit_info']['width'])
print("circuit_depth:\t", result['circuit_info']['depth'])
print("CNOT gates:\t", result['circuit_info']['operations']['cx'])
```

```python
[Out]: 
circuit_width:	 7
circuit_depth:	 102
CNOT gates:	 54
```

The actual "circuit_depth" that I get is 101 as opposed to the textbook example of 102.

**Expected behavior**
The textbook depicts real code output and hence circuit_depth should be 101.

**Version info***
For qiskit problems, please provide the output of:
```
import qiskit
qiskit.__qiskit_version__
```

```python
{'qiskit-terra': '0.16.1',
 'qiskit-aer': '0.7.1',
 'qiskit-ignis': '0.5.1',
 'qiskit-ibmq-provider': '0.11.1',
 'qiskit-aqua': '0.8.1',
 'qiskit': '0.23.1'}
```

**Comment by frankharkins** [comment]
@paniash is the problem here that the text says:

> ...saw that it uses 7 qubits, has a depth of **102** gates and requires...
?

**Comment by paniash** [comment]
> @paniash is the problem here that the text says:
> 
> > ...saw that it uses 7 qubits, has a depth of **102** gates and requires...
> 
> which contradicts the code output?

This as well as the code output. The expected circuit_depth should be 101.

**Comment by hykavitha** [comment]
@frankharkins  can you please assign this issue to @https://github.com/amitracal, As discussed Abhijith Mitra will work with me on HHL issues.

**Comment by amitracal** [comment]
![image](https://user-images.githubusercontent.com/69091655/112914750-6ce60080-90c2-11eb-8e4a-e424d75e11ea.png)
![image](https://user-images.githubusercontent.com/69091655/112914938-ce0dd400-90c2-11eb-9679-0bbcfe4d2c3d.png)

The output is 101 running the notebook as well as in the textbook, where are you getting 102 from ?
