### ISSUE TITLE
[2.1] Minor improvement to section 2.1

### ISSUE THREAD

**Issue by prakity** [qiskit-community/qiskit-textbook#870]
**Describe the issue**
Should mention that |> is a column vector and define complex transpose.  The * notation is not defined. SEE CAPS BELOW
**Describe what you expect to see**
A Very Important Rule 

There is a simple rule for measurement. To find the probability of measuring a state 
|ψ⟩
 in the state 
|x⟩
 we do:
p(|x⟩)=|⟨x|ψ⟩|2
The symbols 
⟨ and | tell us ⟨x| is a row vector AND |> iS A COLUMN VECTOR.  In quantum mechanics we call the column vectors kets and the row vectors bras. Together they make up bra-ket notation. Any ket 
|a⟩
 has a corresponding bra 
⟨a|
, and we convert between them using the conjugate transpose.

Reminder: The Inner Product (Click here to expand).  CHANGE TITLE TO CONJUGATE TRANSPOSE
There are different ways to multiply vectors, here we use the inner product. The inner product is a generalisation of the dot product which you may already be familiar with. In this guide, we use the inner product between a bra (row vector) and a ket (column vector), and it follows this rule:

ADD DEFINE for *. AS IN IT CHANGES THE SIGN OF THE COMPLEX PART OF THE NUMBER

**Comment by paniash** [comment]
@prakity Hi! Pardon but your issue is not very clear. Could you make it concise and understandable?

**Comment by prakity** [comment]
Original text




Extend sentence “... is a row vector.” “and < | is a column vector”

Reminder section is not helpful here it should include definition of conjugate transpose.

Philip
IPaw Powered

**Comment by prakity** [comment]
Ops. ‘and  |> is a column vector’.  See below for other more important comment

IPaw Powered

**Comment by prakity** [comment]
![D7783619-07B6-4F6A-AF38-DC501434F864](https://user-images.githubusercontent.com/1106259/104816163-29912b00-5811-11eb-8501-e6bfb495e2a6.png)


inner product note is not appropriate.  DescRibe conjugate transpose

**Comment by shil-m** [comment]
> **Describe the issue**
> Should mention that |> is a column vector and define complex transpose. The * notation is not defined. SEE CAPS BELOW
> **Describe what you expect to see**
> A Very Important Rule
> 
> There is a simple rule for measurement. To find the probability of measuring a state
> |ψ⟩
> in the state
> |x⟩
> we do:
> p(|x⟩)=|⟨x|ψ⟩|2
> The symbols
> ⟨ and | tell us ⟨x| is a row vector AND |> iS A COLUMN VECTOR. In quantum mechanics we call the column vectors kets and the row vectors bras. Together they make up bra-ket notation. Any ket
> |a⟩
> has a corresponding bra
> ⟨a|
> , and we convert between them using the conjugate transpose.
> 
> Reminder: The Inner Product (Click here to expand). CHANGE TITLE TO CONJUGATE TRANSPOSE
> There are different ways to multiply vectors, here we use the inner product. The inner product is a generalisation of the dot product which you may already be familiar with. In this guide, we use the inner product between a bra (row vector) and a ket (column vector), and it follows this rule:
> 
> ADD DEFINE for *. AS IN IT CHANGES THE SIGN OF THE COMPLEX PART OF THE NUMBER

Hi, I want to work on this. I understood the change you expect with mentioning the column vector, could you tell me, do you wish to change the title to conjugate transpose or add a new section with conjugate transpose or incorporate within Inner product?

**Comment by prakity** [comment]
Hi,

I believe both changes are needed.  

Philip

IPaw Powered

**Comment by divshacker** [comment]
btw it's [1.3#[2.1]] @frankharkins. I wouldn't have know if screenshot wasn't there. XD

**Comment by shil-m** [comment]
Hi, I am sorry I didn't understand the other change you expect. You want a new Reminder Section with Conjugate Transpose in it?

> Hi, I believe both changes are needed. Philip IPaw Powered
> […](#)
> On 7 Jun 2021, at 11:15, Shilpa Mahato ***@***.***> wrote: ﻿ Describe the issue Should mention that |> is a column vector and define complex transpose. The * notation is not defined. SEE CAPS BELOW Describe what you expect to see A Very Important Rule There is a simple rule for measurement. To find the probability of measuring a state |ψ⟩ in the state |x⟩ we do: p(|x⟩)=|⟨x|ψ⟩|2 The symbols ⟨ and | tell us ⟨x| is a row vector AND |> iS A COLUMN VECTOR. In quantum mechanics we call the column vectors kets and the row vectors bras. Together they make up bra-ket notation. Any ket |a⟩ has a corresponding bra ⟨a| , and we convert between them using the conjugate transpose. Reminder: The Inner Product (Click here to expand). CHANGE TITLE TO CONJUGATE TRANSPOSE There are different ways to multiply vectors, here we use the inner product. The inner product is a generalisation of the dot product which you may already be familiar with. In this guide, we use the inner product between a bra (row vector) and a ket (column vector), and it follows this rule: ADD DEFINE for *. AS IN IT CHANGES THE SIGN OF THE COMPLEX PART OF THE NUMBER Hi, I want to work on this. I understood the change you expect with mentioning the column vector, could you tell me, do you wish to change the title to conjugate transpose or add a new section with conjugate transpose or incorporate within Inner product? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by prakity** [comment]
Yes please.  Explain conjugate transpose

IPaw Powered

**Comment by shil-m** [comment]
Great, will do that.

**Comment by shil-m** [comment]
Also, do I need to get assigned to make a pr? If yes, pl assign me. Thank you :)
