### ISSUE TITLE
[5.2] Mathematical inaccuracy in Measurement Error Mitigation

### ISSUE THREAD

**Issue by mentesniker** [qiskit-community/qiskit-textbook#871]
**Describe the issue**
In the middle of the tutorial there's a part that says that counts must be Integers. I think It should say positive integers since you can't really have a negative number of experiments. 
![Screenshot from 2020-12-27 10-03-03](https://user-images.githubusercontent.com/35209340/103174884-70e85500-482b-11eb-86c9-4a0093284032.png)
**Describe what you expect to see**
The correct description has to be "Of course, counts should be positive integers, so these values need to be rounded and only take into account the positive values. This gives us a very nice result."

**Comment by paniash** [comment]
@melvin2016 Hi! I think it is implicitly assumed that counts are positive. However, technically speaking this correction needs to be made.

**Comment by frankharkins** [comment]
Agreed, I don't think this needs explaining. Please reopen if you disagree.
