### ISSUE TITLE
Equation getting covered by side panel

### ISSUE THREAD

**Issue by Aniruddha120** [qiskit-community/qiskit-textbook#877]
**Is your feature request related to a problem? Please describe.**
in this notebook , some equations getting covered by the side panel and it is hard to read the equation. I tried to zoom out to see if that was my browser's problem but it seems a real issue. It is a request to see if there is any solution.
**Describe the solution you'd like**
It can be solved by editing the notebook. 
**Describe alternatives you've considered**
A clear and concise description of any alternative solutions you've considered, e.g. linking to external resources.

**Additional context**
Add any other context or screenshots about the request here.
![image](https://user-images.githubusercontent.com/34673269/103442074-cddc7480-4c4a-11eb-8df3-8296d29cdb6b.png)

**Comment by paniash** [comment]
@Aniruddha120 Looks like this is an issue specific to your local browser settings. It looks fine on my end (running on firefox).

**Comment by Aniruddha120** [comment]
> 
> 
> @Aniruddha120 Looks like this is an issue specific to your local browser settings. It looks fine on my end (running on firefox).

I am also using firefox(for windows) in my laptop. but when i zoom out to 80% then it seems fine.

**Comment by Aniruddha120** [comment]
I am closing this issue as the textbook is working fine in my other browser.
