### ISSUE TITLE
The widget used in the Gate Demo of widgets-index.ipynb is Q-sphere, not bloch sphere.

### ISSUE THREAD

**Issue by kUmezawa** [qiskit-community/qiskit-textbook#879]
Hello, Team.

**Describe the issue**
I think the widget used in the Gate Demo of widgets-index.ipynb is Q-sphere, not bloch sphere. Is it correct?

**Describe what you expect to see**
If the document is correct, modify the widget. If the widget is correct, modify the document and modify the bloch sphere used in Single Qubit Gates to Q-sphere.

Thank you.

**Comment by oscar-defelice** [comment]
I think it is Bloch sphere actually. 
You can plot Q-sphere, by the optional parameter (by default set to `False`) `qsphere` in the `gate_demo`

e.g.

```
gate_demo(gates='pauli', qsphere=True)
```

**Comment by frankharkins** [comment]
This was fixed in the `master` branch but wasn't pushed through to the live site. Thanks for bringing this to my attention. Just fixed in #884 but the kernel might now take a while to load (this happens every time we update `thebe-stable` which is why we avoid doing it frequently).
