### ISSUE TITLE
[4.1.1] Why a probability appeared in the HHL textebook can exceed 1 ?

### ISSUE THREAD

**Issue by Kuma-quant** [qiskit-community/qiskit-textbook#881]
**Describe the issue**

[Solving Linear Systems of Equations using HHL](https://qiskit.org/textbook/ch-applications/hhl_tutorial.html)

In sec. 3. (Example: 4-qubit HHL,),
_6. Without using extra gates, we can compute ...._
![image](https://user-images.githubusercontent.com/77182983/104082609-fe3f9680-527a-11eb-8f77-9fe1ca83e5df.png)

However, the calculation seems strange since 45/32 is larger than 1, Any Probability can't exceed 1.

How should I interpret this?

**Comment by mbuchberger1967** [comment]
I came to the same problem, how can a probability exceed 1?

**Comment by zyzhang1992** [comment]
C is the scaling factor used in the rotation of the auxiliary qubit, conditioned on the eigenvalue. The rotational angle is given by arcsin(C/lamda), so C should be less than or eequal to the smallest eigenvalue. 

When running the HHL algorithm, the lowest eigenvalue from QPE is unknown, so the chosen C may end up higher than some of the eigenvalues in eigenvalue register. In that case, it should up to the Reciprocal class used for the HHL algorithm to make sure that test for the value of C.
