### ISSUE TITLE
3.3 Error in gate operation for message "11"

### ISSUE THREAD

**Issue by paniash** [qiskit-community/qiskit-textbook#888]
**Describe the issue**
The gate operation `ZX` is applied when sending the classical message "11". In the table, the `X` gate is applied first, followed by the `Z` gate. However, when implementing the circuit in qiskit, the `Z` gate is applied first, followed by `X`.

**NOTE**: Both the operations yield the same state except a global phase of -1 differing between the two. This might make things confusing to the novice reader.

**Describe what you expect to see**

The "resulting state" for "11" as the message must be `|01> - |10>` instead (for it to be consistent with the implementation in qiskit).

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
