### ISSUE TITLE
Textbook with Github Pages

### ISSUE THREAD

**Issue by firmai** [qiskit-community/qiskit-textbook#913]
Hi guys, I love 😍  your project, If I want to use what you have developed up to now, is there a way to get it up and running with GitHub pages, I had a few stumbling blocks with rclone, secrets, and actions. If anyone knows how qiskit-community/qiskit-textbook can be used as a template, I would be forever grateful and so would other communities. While we are on the topic, I would enjoy taking the advice here and making it easier for others who want to do the same. 

Any help would be appreciated, this is not my expertise, so even if you just know a little bit on the subject, it will help. Thanks :)

**Comment by frankharkins** [comment]
@firmai are you looking to host a clone or derivative of the textbook? We currently use an outdated version of jupyter book: https://legacy.jupyterbook.org/intro.html. Depending on what you want to achieve, you may find it easier to use the existing notebooks with the new version of jupyter book: https://jupyterbook.org/ which has advice on using github pages: https://jupyterbook.org/publish/gh-pages.html

**Comment by firmai** [comment]
Thanks, @frankharkins, I will have a go at the new version. Thank you for helping out, I might come back to borrow some elements over time. Cheers.
