### ISSUE TITLE
Quantum Simulation and Trotter Suzuki Formalism

### ISSUE THREAD

**Issue by kaelynj** [qiskit-community/qiskit-textbook#924]
Hi all!  As part of my candidacy prospectus, I wrote a quantum simulation algorithm for a one-dimensional Hubbard system using Qiskit.  The algorithm time evolves an excitation in a 1D chain of n sites using the Fermi-Hubbard Hamiltonian.  

The code itself takes the hopping energy _t_, and onsite energy _U_, as well as a time step size, a total number of time steps, and the chain size.  It creates an excitation by placing two electrons of opposite spin close to the middle of the chain, and records and plots the occupation of each fermionic mode (site and spin).

**What should the reader gain from this new content?**
After reading this chapter, the student will have an understanding of how digital quantum simulation algorithms work and how large exponentiated Hamiltonian operators can be separated into more manageable pieces using the Trotter-Suzuki formalism.  They will also have an understanding of the Jordan-Wigner transformation and an introduction to the Fermi-Hubbard model and why it is an interesting problem that near-term quantum computers might be able to solve.

**Where do you expect this new content to fit in with the current content?**
I can see this being placed in either section 3 or 4.2.  If it sits in Section 3, perhaps going over quantum simulation with more detail and an example system that is simpler than the Fermi-Hubbard model (perhaps particle-in-a-box) would be prudent.  If it sits in 4.2, more focus could be put on current variational algorithms to find the ground state of the 2d system.  I can also see this content suggestion getting split into two different sections (one on quantum simulation, and the other on the Fermi-Hubbard model specifically).

**What material should this new content be based on?**
The quantum simulation/Trotter piece of this suggestion is based on section 4.7.2 in the Nielsen and Chuang [textbook](http://mmrc.amss.cas.cn/tlb/201702/W020170224608149940643.pdf)
The variational approach to the Fermi-Hubbard model is based on [this paper](https://journals.aps.org/prb/abstract/10.1103/PhysRevB.102.235122)
The Jordan-Wigner transformation is based on the section in the [Microsoft Q# docs](https://docs.microsoft.com/en-us/azure/quantum/user-guide/libraries/chemistry/concepts/jordan-wigner)

**Are you proposing to write this new content?** (y/n)
I would be happy to!  The code and a WIP to a writeup can be found in this [repo](https://github.com/kaelynj/Qiskit-HubbardModel) I've written that either me or someone else could add to.

**Comment by quantumjim** [comment]
Note that the Trotter-Suzuki method is briefly used in [Section 2.5](https://qiskit.org/textbook/ch-gates/proving-universality.html). So it should be written with an awareness of that.

**Comment by kaelynj** [comment]
Yeah that makes sense to me.  Potentially the piece on Trotter could be made briefer with a reference to the end of section 2.5 and noting that the method proving universality was done using the Trotter-Suzuki method.

**Comment by frankharkins** [comment]
I'm going to close this issue as the textbook content is being reworked in the new beta version. Please let me know if you have any questions.
