### ISSUE TITLE
Error in Lab 01

### ISSUE THREAD

**Issue by quantumjim** [qiskit-community/qiskit-textbook#927]
**Describe the issue**

In Lab 1, there is a typo in the OR gate exercise. The lines

```
    if inp=='1':
        qc.x(0)
    if inp=='1':
        qc.x(1)
```

which ignore the actual inputs `inp1` and `inp2` should be

```
    if inp1=='1':
        qc.x(0)
    if inp2=='1':
        qc.x(1)
``

**Comment by HwajungKang** [comment]
Just fixed it. Thanks!
