### ISSUE TITLE
"statevector" vs "state vector"

### ISSUE THREAD

**Issue by omarcostahamido** [qiskit-community/qiskit-textbook#933]
**Describe the issue**
Though we might want to refer to "statevector" as direct reference to how we type it in python, "statevector" (one word) has been adopted in current language among qiskitters to be synonymous of "state vector" (two words) in any situation.

**Describe what you expect to see**
I noticed that there are some places [here](https://qiskit.org/textbook/ch-states/representing-qubit-states.html) where it appears "state vector" instead of "statevector".
For the sake of consistency I would propose change it to "statevector".
Or not. I'm open to hear what other people think about this.

Thanks

**Comment by rupeshknn** [comment]
"Stave Vector" is technically the correct word. Many terms in python have no spaces in between like `qiskit.pulse.ShiftPhase` etc but in all those cases qiskit has appropriate uppercasing to emphasise that. However `qiskit.quantum_info.Statevector` doesn't seem to follow that nomenclature. I personally feel we must use "StateVector"

**Comment by shil-m** [comment]
> **Describe the issue**
> Though we might want to refer to "statevector" as direct reference to how we type it in python, "statevector" (one word) has been adopted in current language among qiskitters to be synonymous of "state vector" (two words) in any situation.
> 
> **Describe what you expect to see**
> I noticed that there are some places [here](https://qiskit.org/textbook/ch-states/representing-qubit-states.html) where it appears "state vector" instead of "statevector".
> For the sake of consistency I would propose change it to "statevector".
> Or not. I'm open to hear what other people think about this.
> 
> Thanks

Hi, could you cite where you found this anomaly? From what I saw, places where simulator has been referred to it is "statevector"  and other wise in content it is "state vector" which is the correct way of representing I suppose. Could you highlight where are you expecting to change it? In the documentation or content?

**Comment by rupeshknn** [comment]
Check out 1.3 in the qiskit textbook. The same was linked by @omarcostahamido.

**Comment by shil-m** [comment]
> Check out 1.3 in the qiskit textbook. The same was linked by @omarcostahamido in the issue.

Thank you! I completely missed it. So, I would like to work on this issue. I believe "state vector" is the correct representation of the word/words but in the python code it is referred to as "statevector" and not  "StateVector" so indicating that it is one word. Any suggestions on which one to implement? I believe we should go with the grammatically correct representation i.e. "state vector". What do you think?

**Comment by rupeshknn** [comment]
So there are two parts to this. The First would be to replace "statevector" in the textbook contents with "state vector". The second would be to replace "statevector" in qiskit terra with "StateVector".

I actually wanted to take care of this issue. You could maybe open one on terra?

**Comment by omarcostahamido** [comment]
I am glad other people are engaging with this issue now.
I have to admit that, even though I recognize "state vector" as the technically _correct_ word, I thought it would be nice to have the new formulation "statevector" that is immediately recognized as a "state vector" being referred to in the context of QC. "statevector" is also easier and faster to write. In any case, going with one or two word variant, consistency is a must.
Thank you.

**Comment by shil-m** [comment]
> So there are two parts to this. The First would be to replace "statevector" in the textbook contents with "state vector". The second would be to replace "statevector" in qiskit terra with "StateVector".
> 
> I actually wanted to take care of this issue. You could maybe open one on terra?

I am not sure if I can work on the issue with qiskit terra.

**Comment by frankharkins** [comment]
I have been writing 'statevector' but agree we should go with 'state vector' in the textbook. This can be fixed with a find/replace over all the notebooks. If I were to do this myself, I would use [nbconvert](https://nbconvert.readthedocs.io/en/latest/) to distinguish between text in markdown vs code cells, similar to [this script](https://github.com/qiskit-community/qiskit-textbook/blob/main/scripts/replace_code_cells.py).

**Comment by frankharkins** [comment]
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.
