### ISSUE TITLE
Pulse code example updates (Qiskit Advocate Project)

### ISSUE THREAD

**Issue by nkanazawa1989** [qiskit-community/qiskit-textbook#934]
Currently some pulse code examples are written in the old programming model based on `Schedule`. I'll update these code examples with the _pulse builder_ syntax which is becoming a new standard of Qiskit Pulse programming. This work will be done as a part of the qiskit advocate project, with the contribution of the team @faraimazh @kUmezawa @0sophy1 @splch.

See below for details:
https://github.com/qiskit-community/qiskit-advocate-mentorship-program/issues/2

**Comment by 0sophy1** [comment]
so excited to join!

**Comment by faraimazh** [comment]
Let's hack on!

**Comment by kUmezawa** [comment]
Hello !

**Comment by aasfaw** [comment]
Well done Naoki and team. Good luck!

**Comment by splch** [comment]
You can't beat🎶 Pulse!🎵

**Comment by nkanazawa1989** [comment]
Thanks @frankharkins for assignment :)

**Comment by frankharkins** [comment]
Thanks everyone for your great work!
