### ISSUE TITLE
3.2 Deutsch-Jozsa Algorithm Possible Typo in Formula

### ISSUE THREAD

**Issue by trippalamb** [qiskit-community/qiskit-textbook#936]
In section "1.2 The Classical Solution" of Chapter "3.2 Deutsch-Jozsa Algorithm" there is a math formula for the probability of the function being constant. In that formula it is noted that the formula holds true "for k <= 2^(n-1)". 

I definitely could be mistaken, but I believe this is a typo and should read "for k <= n",

Edit: Upon further inspection it strikes me that something more might be off. For the current function @ k = 0 the probability is -1, and @ k=1 probability is 0.

Edit 2: The best suggestion I could come up with after thinking about it for a while is that the formula should read:
P_constant(k) = 1 - 1/(2^k) for 0 < k <= 2^(n-1)

**Comment by frankharkins** [comment]
@trippalamb if we set limit 1 < k <= 2^(n-1), does this eq. work correctly in your opinion? We can't get any guesses about probability before k is at least 2 so it makes sense to limit it to this.

**Comment by trippalamb** [comment]
Yes, that definitely makes sense if we cannot make a guess about the probability before k=2.
