### ISSUE TITLE
Replace all instances of "ancilla" with "auxiliary" 

### ISSUE THREAD

**Issue by ryanfmandelbaum** [qiskit-community/qiskit-textbook#941]
**Describe the problem**

Ancilla is Latin for "maid" or "slave girl." We've been pushing internally for this word to be removed and replaced with the synonymous auxiliary. The Qiskit Textbook should follow suit and use the more appropriate term.

The word appears:
https://qiskit.org/textbook/ch-paper-implementations/vqls.html
https://qiskit.org/textbook/ch-applications/hhl_tutorial.html
https://qiskit.org/textbook/ch-labs/Lab07_QuantumSimulationSearchAlgorithm.html
https://qiskit.org/textbook/ch-labs/Lab04_IterativePhaseEstimation.html

**Describe the expected solution**

Replace all instances of "ancilla" with "auxiliary."

**Comment by aasfaw** [comment]
Thank you @ryanfmandelbaum! I agree with this, let's make it happen. Would you like to take action on this?

**Comment by mmcelaney** [comment]
This would be a great first issue for someone in our community to tack. Thanks for submitting! I hope someone has the time to tackle this soon!

**Comment by ryanfmandelbaum** [comment]
Agreed -- I would say this would be a nice first issue for a potential textbook contributor to get them up to speed on the textbook updating process.
