### ISSUE TITLE
Inconsistent labels for Bell state and the qubit to be sent in Teleportation (Ch. 3.10)

### ISSUE THREAD

**Issue by dhruvbhq** [qiskit-community/qiskit-textbook#954]
**Describe the issue**
https://qiskit.org/textbook/ch-algorithms/teleportation.html
While going through the section on quantum teleportation, I observed some inconsistencies in the notations which might be potentially confusing for a novice reader:

1. In the early part of the section, from 'Overview' (https://qiskit.org/textbook/ch-algorithms/teleportation.html#overview) to 'Using the QASM simulator' (https://qiskit.org/textbook/ch-algorithms/teleportation.html#simulating-qs), $\ket{\psi}$ is used to denote the qubit that Alice wants to send to Bob via quantum teleportation.
However, in the following section 'Understanding Quantum Teleportation' (https://qiskit.org/textbook/ch-algorithms/teleportation.html#understanding-qt), there is an abrupt and unexplained change of notation. $\ket{\psi}$ is now being used to denote the shared Bell state of 2 qubits. The qubit to be sent is now denoted by $\ket{q}$. This is in disagreement with the notation being used till the point of 'Using the QASM simulator'.

2. With reference to the same sections, from 'Overview' to 'Using the QASM simulator', the probability amplitudes for the state to be transmitted (ie $\ket{\psi}$) are taken to be $\alpha$ and $\beta$. However, in 'Understanding Quantum Teleportation', the probability amplitudes are now given by $a$ and $b$ for the qubit to be sent. To make things potentially even more convoluted for a beginner, the function create_bell_pair() in an intervening section (https://qiskit.org/textbook/ch-algorithms/teleportation.html#how) uses 'a' and 'b' as arguments for qubits to initialize in a Bell state.

**Describe what you expect to see**
It might be a good idea to keep the notation in the section 'Understanding Quantum Teleportation' (https://qiskit.org/textbook/ch-algorithms/teleportation.html#understanding-qt) consistent with the preceding matter. The following could be possible solutions to the above respectively:

1.  In 'Understanding Quantum Teleportation' , the qubit to be sent should be labelled by $\psi$ and the Bell state should use a letter other than $\psi$.
2. In 'Understanding Quantum Teleportation', the probability amplitudes for the state to be transmitted (ie $\ket{\psi}$) should be taken as $\alpha$ and $\beta$ in the ensuing explanation, in place of $a$ and $b$.

**Comment by dhruvbhq** [comment]
If you believe this is a good first issue, I would like to attempt the fix, as I am new to contributing.

**Comment by frankharkins** [comment]
@dhruvbhq yes these are great suggestions- will assign you. Thank you.
