### ISSUE TITLE
Use of qobj in `run()`

### ISSUE THREAD

**Issue by quantumjim** [qiskit-community/qiskit-textbook#957]
**Describe the issue**

Qiskit is currently giving the following warning when using an IBMQ backend.

```
Passing a Qobj to Backend.run is deprecated and will be removed in a future release. Please pass in circuits or pulse schedules instead.
```

This seems inconsistent with the efforts that have been made to remove `execute` from the textbook.

**Comment by jwoehr** [comment]
It's not `run()` that's deprecated, it's passing a `Qobj`. `run()` will take a `QuantumCircuit` object. `Qobj` is being relegated to the hinterlands.

**Comment by quantumjim** [comment]
Good to know. Though I think to there's been a lot of recent effort to add
it to the textbook when replacing execute.

**Comment by jwoehr** [comment]
In the 2000's, I used to browse quantum computing papers at my leisure.
Now keeping up with Qiskit alone is a fulltime job :)

**Comment by jwoehr** [comment]
Reading qiskit-terra/qiskit/providers/backend.py allows one to wallow in the complexity of the spec as it currently stands:

    @abstractmethod
    def run(self, run_input, **options):
        """Run on the backend.

        This method that will return a :class:`~qiskit.providers.Job` object
        that run circuits. Depending on the backend this may be either an async
        or sync call. It is the discretion of the provider to decide whether
        running should  block until the execution is finished or not. The Job
        class can handle either situation.

        Args:
            run_input (QuantumCircuit or Schedule or list): An individual or a
                list of :class:`~qiskit.circuits.QuantumCircuit` or
                :class:`~qiskit.pulse.Schedule` objects to run on the backend.
                For legacy providers migrating to the new versioned providers,
                provider interface a :class:`~qiskit.qobj.QasmQobj` or
                :class:`~qiskit.qobj.PulseQobj` objects should probably be
                supported too (but deprecated) for backwards compatibility. Be
                sure to update the docstrings of subclasses implementing this
                method to document that. New provider implementations should not
                do this though as :mod:`qiskit.qobj` will be deprecated and
                removed along with the legacy providers interface.
            options: Any kwarg options to pass to the backend for running the
                config. If a key is also present in the options
                attribute/object then the expectation is that the value
                specified will be used instead of what's set in the options
                object.
        Returns:
            Job: The job object for the run
        """
        pass

**Comment by Dreamsoobinms** [comment]
And now, can you solve this problem? Please tell me the way. Because I still can't fix this problem at all.

**Comment by mavzolej** [comment]
I am getting this warning not when using `run()` manually but when calling

    qiskit.aqua.operators.converters.CircuitSampler( q_instance ).convert( expectation )

(where `q_instance` has IMBQ backend )
Is there a way to avoid this Warning?

**Comment by rawanaziz** [comment]
hi ,I have faced the same problem, may please help me , or what did you do .
"Passing a Qobj to Backend.run is deprecated and will be removed in a future release. Please pass in circuits or pulse schedules instead."

**Comment by frankharkins** [comment]
@mavzolej is that code somewhere in the textbook? If not please open an issue in qiskit https://github.com/qiskit
@rawanaziz instead of:
```
qobj = assemble(qc)
backend.run(qobj)
```
Just do:
```
backend.run(qc)
```

**Comment by rawanaziz** [comment]
thanks alot
