### ISSUE TITLE
Links are not working in Japanese translation website

### ISSUE THREAD

**Issue by kifumi** [qiskit-community/qiskit-textbook#960]
**Describe the bug**
In Japanese version of website, the two icons of “Open in IBM Quantum Lab” and “Download as Jupyter Notebook” go to the error.

**To Reproduce**
1. Go to 'https://qiskit.org/textbook/ja/ch-algorithms/deutsch-jozsa.html'
2. Click on 'IBM Quantum Labを開く'
3. See error "404 : Not Found You are requesting a page that does not exist!"
and
1. Go to 'https://qiskit.org/textbook/ja/ch-algorithms/deutsch-jozsa.html'
2. Click on 'Jupyter Notebookのダウンロード'
3. See error "Page Not Found Sorry, but the page you were trying to view does not exist."

**Expected behavior**
Same behavior as English version of website.

**Version info***
device: Mac
OS: macOS Catalina
browser: Firefox, Chrome

**Screenshots**
![image](https://user-images.githubusercontent.com/19249007/111245636-4ba7fd80-8648-11eb-9645-1cd0bda9c573.png)

@vabarbosa , could you please take a look?

**Comment by frankharkins** [comment]
Finally fixed, sorry for the wait
