### ISSUE TITLE
[3.5] Inconsistency with indexes in section 5 of the chapter 3.5

### ISSUE THREAD

**Issue by filippotramonto** [qiskit-community/qiskit-textbook#964]
**Describe the issue**
There is an inconsistency in [section 5 of the chapter 3.5 ](https://qiskit.org/textbook/ch-algorithms/quantum-fourier-transform.html#5.-The-Circuit-that-Implements-the-QFT-).
In the sentence that starts with "The action of $CROT_k$ on the two-qubit state $\vert x_j x_k\rangle$" the order of the indexes, j and k, of the state $\vert x_j x_k\rangle$ is inconsistent respect to the subsequent 2 mathematical expressions, it is reversed.

**Describe what you expect to see**
I expect the state mentioned above to be $\vert x_k x_i\rangle$

**Comment by filippotramonto** [comment]
Upon further analysis of the explained circuit implementation shown in the figure and in steps 1 through 4, it becomes clear that the index k is not the same index as the state of the target qubit to which the $UROT_k$ rotation is applied. This occurs only for when the target qubit is qubit 1. So it would be more correct to indicate the state two qubits with two indices different from k, for example the first index with the letter $l$ and the second with the letter $j$, as in the next two mathematical expressions.

**Comment by HwajungKang** [comment]
I think CROT should have different subscript... So, in the sentence that @filippotramonto pointed out, the subscript of CROT should be 'j-k+1' instead of 'k' with  j-th qubit as control and k-th as target qubit.  
Therefore, the sentence should be " The actions of $CROT_{j-k+1}$ on the two-qubit state..." to be consistent with the index of UROT in the QFT circuit figure in section 5 and the explanation in the steps 1-4.

**Comment by filippotramonto** [comment]
Yes, of course, what @HwajungKang says is correct to maintain a perfect consistency with the figure in section 5 and the explanation in the steps 1-4.
But I think that sentence is referring to a general $CROT_k$ applied to a general two-qubit state. In this point of the section it is not explained yet how the CROTs are applyied. So I think the important thing is that the index of CROT should be different from the indexes of two-qubit state, because the power of $2$ at the denominator of the phase of the controlled rotation does not necessarily correspond to one of the indexes of the two-qubit state and it is important to do not induce the reader to think that the index of CROT should be equal to one of the the indexes of the state.

@HwajungKang if you agree I proceed to submit the PR, with the following index notation: $CROT_k$  and $| x_l x_j \rangle$.

**Comment by HwajungKang** [comment]
Yeah, that makes sense! I agree.
