### ISSUE TITLE
[1.2] Half-adder diagram doesn't seem to match the description below it

### ISSUE THREAD

**Issue by ausmarton** [qiskit-community/qiskit-textbook#966]
**The issue**
The half-adder diagram seems to be missing the `barrier`s here: [4.3 Adding with Qiskit](https://qiskit.org/textbook/ch-states/atoms-computation.html#4.3-Adding-with-Qiskit-)

The image used is: ![half adder without barriers](https://github.com/qiskit-community/qiskit-textbook/blob/1dcb286efbf883d6007bb6a2d494f31e75ef22d8/content/ch-states/images/half-adder.svg?raw=true)

And the text below it has got two lines which don't seem to match the image:
The first one being,
> All that remains is to fill in the actual program, which lives in the blank space in the middle

where I'm not quite sure if the "blank space" being referred to, is supposed to be within the image, or if the image itself needs to be modified for this 
and
> The dashed lines in the image are just to distinguish the different parts of the circuit (although they can have more interesting uses too). They are made by using the barrier command.

where I'm not sure if the text is in the wrong place, or the image.

**Expectation**
I'm not quite sure how the first item is to be resolved, but for the second issue, I think an image which looks somewhat like this might work:
![half-adder](https://user-images.githubusercontent.com/427908/111539834-42ad4e00-8766-11eb-9e36-ef94ab3eb9d9.png)

If there's any information missing in this issue description, please let me know.

**Comment by lebinyu** [comment]
I think the article is trying to show how to build a quantum adder step by step. The image you mentioned should be something like this:

![circuit-kmdyqkdm](https://user-images.githubusercontent.com/37998880/111543620-9d00db80-8773-11eb-907d-e080ae0d93a9.png)

It would be better if there is more space between two dash lines, but I don't know how to do that.

**Comment by ausmarton** [comment]
@lebinyu Thanks for clarifying that. I think I get the intent there.
Is this what it should look like?
![half-adder-without-operations](https://user-images.githubusercontent.com/427908/111544989-3bd60980-876d-11eb-82f9-8eb0aa8bfb09.png)

Or would it be better without the labels and the arrows, like this?
![half-adder-without-operations-and-labels](https://user-images.githubusercontent.com/427908/111545090-6d4ed500-876d-11eb-8db0-2c272caa91b8.png)

**Comment by lebinyu** [comment]
Yes, that's exactly what I mean. I think is better to keep the label.
How did you draw the circuits with emplty space in the middle, by the way?

**Comment by ausmarton** [comment]
Actually, it was a very low-tech solution - I just modified the original image and got rid of the CX gates in Inkscape.
I was wondering how you generated an image which was styled a bit different from the original. Were you trying to render it from an actual circuit?

**Comment by lebinyu** [comment]
I drew on the [IBM Q composer](https://quantum-computing.ibm.com/composer/files/new?initial=N4IgdghgtgpiBcICqYAuBLVAbGATABAMboBOhArpiADQgCOEAzlAiAPIAKAogHICKAQQDKAWXwAmAHQAGANwAdMOjCEs5XDHzz6MLOgBGARknLC2hWEV0SMAOb46AbQAsAXQuEb9wo-HvFigAeDo7S-mDBTobh%2BhAkJOgwJCFh1FGuab4ZTgDMMXEJSSnZjtGZfpl5FrBM5DYhfvgAtAB8RKHhNYx1mrmuzW0%2B0bI0IBqMnugADhgA9mCsIAC%2BQA), which the design has changed a little over time.

**Comment by quantumjim** [comment]
For reference, here is image in the original version.

![image](https://user-images.githubusercontent.com/18051574/111596459-7b344280-87cd-11eb-9541-e1389c588f38.png)

The images @ausmarton made seem like great updates. I think the one with arrows is better for the explanation.

**Comment by ausmarton** [comment]
@quantumjim Thanks for confirming that, I've now got a PR #967 with the image changed. Please let me know if there's anything that needs to be changed there

**Comment by frankharkins** [comment]
Closed in  #967
