### ISSUE TITLE
[3.5] Inconsistency with the notation in chapter 3.5

### ISSUE THREAD

**Issue by byulen** [qiskit-community/qiskit-textbook#970]
**Describe the issue**
There is an inconsistency with the notation in chapter 3.5 in particular between section 1 (introduction) 
and section 4 (The Quantum Fourier Transform).

In section 1, |x> state is not defined at all. Actually, I think |x> is the same thing with |i> mentioned in the expression sum_{i=0}^{N-1} x_i |i>, that is, it is one of the basis states. Here, the vectors (x_0,x_1,...,x_{N-1}) and (y_0,y_1,...,y_{N-1}) are mentioned. The values of these coefficents are complex numbers. In section 4, |x> and |y> states are defined as |x_1 x_2 x_3 ... x_N> and |y_1 y_2 y_3 ... y_n> where now y_1, y_2, y_3 etc. are bit values taking values 0 and 1.  

Summarizing, the vector (x_0,x_1,...,x_{N-1}) in section 1 should be clearly distinguishable from the state |x_1 x_2 x_3 ... x_N> in section 4.

**Describe what you expect to see**

In order to remove any ambiguity, I recommend to use different notations for probability amplitudes and basis states. It would be much better if the notation is consistent everywhere in chapter 3.5.

I suggest to use |X> =  (x_0,x_1,...,x_{N-1}) = sum_{i=0}^{N-1} x_i |i> for the vector that carries the coefficients to be Fourier transformed. Similarly, 
|Y> = (y_0,y_1,...,y_{N-1}) =sum_{i=0}^{N-1} y_i |i> in section 1. Also, I think using the notation |k> and |j> instead of |x> and |y> will be more appropriate.

Note that now |Y> = U_{QFT} |X> where U_{QFT} = 1/sqrt{N} sum_j sum_k w_N^{jk} |j> <k| can be written without ambiguity with the new notation.

**Comment by singhmeet11** [comment]
can I work on this ? @frankharkins
