### ISSUE TITLE
Calculating state purity after applying controlled gates to pure states

### ISSUE THREAD

**Issue by thepadguy** [qiskit-community/qiskit-textbook#972]
**What should the reader gain from this new content?**
After reading this chapter the student will understand how purity of two (previously pure) states (target and control) changes when a controlled gate is applied to the system. He/she should be able to calculate this change of the purity, and with that knowledge be able to set up more precise and advanced experiments, that make better use of quantum entanglement.

**Where do you expect this new content to fit in with the current content?**
I expect this content to fit in the folder qiskit-textbook/content and between chapters 2.2-2.3 in qiskit.org/textbook.

**What material should this new content be based on?**
This material is only based on knowledge gained from qiskit.org/textbook

**Are you proposing to write this new content?** (y/n)
y

**Comment by frankharkins** [comment]
Hi, really sorry for the slow response. Thanks for offering to contribute to the textbook, unfortunately we're not accepting new content at this time. We still think community-driven content is really valuable, and we're working to create an appropriate place for it within the textbook platform. Until then, I highly encourage you to continue to share your work through other channels. 

I'm going to close this issue, but please let me know if I can support or help in any way.
