### ISSUE TITLE
[1.2] The Atoms of Computation - Image inconsistent with the description

### ISSUE THREAD

**Issue by navaneethsdk** [qiskit-community/qiskit-textbook#984]
While explaining the implementation of the [half adder using Qiskit](https://qiskit.org/textbook/ch-states/atoms-computation.html#4.3-Adding-with-Qiskit-), there is a paragraph that states "The dashed lines in the image are just to distinguish the different parts of the circuit". But clearly, the image does not feature any dashed lines causing confusion to an absolute beginner.
NOTE: 
1. There is a section towards the end that enables the learner to execute the code and see the barrier for himself/herself.
2. There is also an image featuring barriers at the top but nowhere near its reference. 

There are 2 possible solutions to this:
1. Either shift the paragraph towards the section where the user can create the barrier and execute the code.
2. Or to replace the current image with another, featuring the barriers.

![qiskitissue](https://user-images.githubusercontent.com/56035039/112421961-1e4d0500-8d56-11eb-93a2-8f039976ac2c.png)

**Comment by paniash** [comment]
@navaneethsdk Thanks for pointing this out. Looks like the chapter has undergone some updates the last time I checked and this wasn't an issue then. Possibly the paragraphs were not appropriately updated. I think it would be good to shift the order of the paragraph as you mentioned. Let's hear what others have to say. @frankharkins

**Comment by lebinyu** [comment]
I believe this issue has been discussed before in issue #966

**Comment by frankharkins** [comment]
Closed in #967
