### ISSUE TITLE
[4.1.2] Qiskit Textbook VQE Example Bug

### ISSUE THREAD

**Issue by Karl-Grantham** [qiskit-community/qiskit-textbook#989]
**Describe the bug**
I have been trying to run the Qiskit Textbook VQE Example (https://qiskit.org/textbook/ch-applications/vqe-molecules.html#VQE-Implementation-in-Qiskit) with molecules other then LiH.
However, when I try and change the given molecule to anything else (H2, for example), it crashes with the following error message:
AttributeError: 'int' object has no attribute 'num_qubits'

**To Reproduce**
1. Go to  the Qiskit Textbook VQE Example (https://qiskit.org/textbook/ch-applications/vqe-molecules.html#VQE-Implementation-in-Qiskit)
2. Replace the "Li" in the molecule data with "H"
3. Run the example

**Expected behavior**
The code should run with H2 exactly as it has done with LiH, however I expect the actual calculated energies to differ.
**Version info***
Qiskit version: 0.16.4
{'qiskit-terra': '0.16.4', 'qiskit-aer': '0.7.6', 'qiskit-ignis': '0.5.2', 'qiskit-ibmq-provider': '0.12.1', 'qiskit-aqua': '0.8.2', 'qiskit': '0.24.0'}

**Screenshots**
![image](https://user-images.githubusercontent.com/81432195/112659005-5b82c700-8e2a-11eb-914a-0d0a674bf358.png)
![image](https://user-images.githubusercontent.com/81432195/112659473-cfbd6a80-8e2a-11eb-9b98-44e7da5a1ffb.png)

**Comment by paniash** [comment]
@Karl-Grantham Hi! The code output is already rendered correctly in the relevant notebook but is yet to be deployed to the site. Expect the same until the deployment.

**Comment by frankharkins** [comment]
Closed in #947

**Comment by Karl-Grantham** [comment]
@paniash
Hi!
Could you please let me know when the next deployment will be?
