### ISSUE TITLE
QGAN example with two dimentional dataset like 100 rows 10 columns

### ISSUE THREAD

**Issue by kitrakatpug21** [qiskit-community/qiskit-textbook#990]
I was using qiskit.aqua.algorithms.QGAN library and using the QGAN method found difficulty in loading data of dimension 1000 rows x 10 columns. I was following qiskit's github tutorial for QGAN Learning and Loading Random Samples, I copied the exact code, just changed the dimension of dataset from [1000,] to [100,10]. However I did tested out that the tutorial with 1000 rows and 1 column data is working and it works till 2 columns but for more than 2 columns it does not work.
I am unable to understand that if the same dataset is working for 1 row and 2 rows then what is the issue in it to work for 4 or more rows.
PS: I had changed num_qubits to [2,2,2,2,2,2,2,2,2,2] and bounds to [[0,3],[0,3],[0,3],[0,3],[0,3],[0,3],[0,3],[0,3],[0,3],[0,3]] both to later charged to numpy array.
>

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-39-1df19589f511> in <module>
>       6 
>       7  # Initialize qGAN
> ----> 8 qgan = QGAN(real_data, bounds, num_qubits, batch_size, num_epochs, snapshot_dir=None)
>       9 qgan.seed = 1
> 
> D:\Users\bro\anaconda3\lib\site-packages\qiskit\aqua\algorithms\distribution_learners\qgan.py in __init__(self, data, bounds, num_qubits, batch_size, num_epochs, seed, discriminator, generator, tol_rel_ent, snapshot_dir, quantum_instance)
>     126                 self._num_qubits = np.array([3])
>     127         self._data, self._data_grid, self._grid_elements, self._prob_data = \
> --> 128             discretize_and_truncate(self._data, self._bounds, self._num_qubits,
>     129                                     return_data_grid_elements=True,
>     130                                     return_prob=True, prob_non_zero=True)
> 
> D:\Users\bro\anaconda3\lib\site-packages\qiskit\aqua\utils\dataset_helper.py in discretize_and_truncate(data, bounds, num_qubits, return_data_grid_elements, return_prob, prob_non_zero)
>     214             for grid_element in grid_elements:
>     215                 for element_current in elements_current_dim:
> --> 216                     temp.append(deepcopy(grid_element).append(element_current))
>     217             grid_elements = deepcopy(temp)
>     218             data_grid.append(elements_current_dim)
> 
> AttributeError: 'NoneType' object has no attribute 'append'

Any solution for the same??

**Comment by paniash** [comment]
@kitrakatpug21 Hi! Could you specify to which chapter in the textbook this pertains to?

**Comment by frankharkins** [comment]
@kitrakatpug21 hi, it's not clear how this relates to the textbook so I'm closing this. I think this is an issue with qiskit terra / aqua so you should open an issue there. If you disagree, please reopen with some more information about where you found this in the textbook.
